#!/bin/sh

if [ "$1" = "configure" ] ; then

  if [ -e "/lib/systemd/system/centreon_vmware-systemd" ]; then
    mv /lib/systemd/system/centreon_vmware-systemd /lib/systemd/system/centreon_vmware.service
  fi

  if [ -e "/etc/centreon/centreon_vmware-conf.pm" ]; then
    mv /etc/centreon/centreon_vmware-conf.pm /etc/centreon/centreon_vmware.pm
  fi

  if [ "$(getent passwd centreon)" ]; then
    chown centreon:centreon /etc/centreon/centreon_vmware.pm
  fi

  systemctl daemon-reload
  systemctl enable centreon_vmware.service
  systemctl restart centreon_vmware.service

fi
exit 0 