*** Settings ***
Documentation       Test suite for Apache CXF JMX
Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}     ${CURDIR}${/}javacxf.mockoon.json

${CMD}              ${CENTREON_PLUGINS}
...                 --plugin=apps::java::cxf::jmx::plugin
...                 --mode=services
...                 --url=http://${HOSTNAME}:${APIPORT}/jolokia
...                 --username=XXX
...                 --password=XXX
...                 --timeout=5


*** Test Cases ***
services ${tc}
    [Tags]    network    api
    ${command}    Catenate
    ...    ${CMD}
    ...    ${extraoptions}

    Ctn Run Command And Check Result As Regexp    ${command}    ${expected_regexp}

    Examples:         tc    extraoptions                                   expected_regexp    --
            ...       1     ${EMPTY}                                       ^OK: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] invocations : Buffer creation, inflight: 8 - number of faults faults-checked-application : Buffer creation, faults-unchecked-application : Buffer creation, faults-logical-runtime : Buffer creation, faults-runtime : Buffer creation \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0;
            ...       2     ${EMPTY}                                       ^OK: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of invocations: 0, inflight: 8 - number of faults checked application: \\\\d, unchecked application: \\\\d, logical runtime: \\\\d, runtime: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=0;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...       3     --filter-service='nene'                        ^UNKNOWN: no services found
            ...       4     --custom-perfdata-instances='\\\%(port)'       OK: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of invocations: \\\\d, inflight: 8 - number of faults checked application: \\\\d, unchecked application: \\\\d, logical runtime: \\\\d, runtime: \\\\d \\\\| 'TestJobXXXX#service.invocations.count'=\\\\d;;;0; 'TestJobXXXX#service.inflight.count'=8;;;0; 'TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...       5     --warning-inflight=:1                          WARNING: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] inflight: 8 \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;0:1;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...       6     --critical-inflight=:1                         CRITICAL: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] inflight: 8 \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;0:1;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...       7     --warning-invocations=1:                       WARNING: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of invocations: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=\\\\d;1:;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...       8     --critical-invocations=1:                      CRITICAL: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of invocations: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=\\\\d;;1:;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...       9     --warning-faults-checked-application=1:        WARNING: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of faults checked application: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;1:;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...      10     --critical-faults-checked-application=1:       CRITICAL: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of faults checked application: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;1:;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...      11     --warning-faults-unchecked-application=1:      WARNING: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of faults unchecked application: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;1:;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...      12     --critical-faults-unchecked-application=1:     CRITICAL: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of faults unchecked application: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=0;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;1:;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...      13     --warning-faults-logical-runtime=1:            WARNING: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of faults logical runtime: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=0;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;\\\\d; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;1:;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
            ...      14     --critical-faults-logical-runtime=1:           CRITICAL: Service 'http://operation_test.dmt/' \\\\[port: TestJobXXXX\\\\] number of faults logical runtime: \\\\d \\\\| 'http://operation_test.dmt/~TestJobXXXX#service.invocations.count'=0;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.inflight.count'=8;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.checked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.unchecked.application.count'=\\\\d;;;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.logical.runtime.count'=\\\\d;;1:;0; 'http://operation_test.dmt/~TestJobXXXX#service.faults.runtime.count'=\\\\d;;;0;
