#!/bin/bash
#
# Copyright 2026-Present Centreon (http://www.centreon.com/)
#
# Centreon is a full-fledged industry-strength solution that meets
# the needs in IT infrastructure and application monitoring for
# service performance.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Mock AWS CLI for testing - returns static JSON data based on --metric-name

metric_name=""
prev=""
for arg in "$@"; do
    if [[ "$prev" == "--metric-name" ]]; then
        metric_name="$arg"
        break
    fi
    prev="$arg"
done

case "$metric_name" in
    Latency)
        cat <<EOF
{"Label":"Latency","Datapoints":[{"Timestamp":"2023-01-01T00:00:00+00:00","Average":400.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:01:00+00:00","Average":500.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:02:00+00:00","Average":600.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:03:00+00:00","Average":700.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:04:00+00:00","Average":800.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:05:00+00:00","Average":900.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:06:00+00:00","Average":1000.0,"Unit":"Milliseconds"}]}
EOF
        ;;
    IntegrationLatency)
        cat <<EOF
{"Label":"IntegrationLatency","Datapoints":[{"Timestamp":"2023-01-01T00:00:00+00:00","Average":200.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:01:00+00:00","Average":300.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:02:00+00:00","Average":400.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:03:00+00:00","Average":500.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:04:00+00:00","Average":600.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:05:00+00:00","Average":700.0,"Unit":"Milliseconds"},{"Timestamp":"2023-01-01T00:06:00+00:00","Average":800.0,"Unit":"Milliseconds"}]}
EOF
        ;;
esac
