#!/bin/bash
#
# Copyright 2026-Present Centreon (http://www.centreon.com/)
#
# Centreon is a full-fledged industry-strength solution that meets
# the needs in IT infrastructure and application monitoring for
# service performance.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Mock AWS CLI for testing - returns static JSON data based on --metric-name

metric_name=""
prev=""
for arg in "$@"; do
    if [[ "$prev" == "--metric-name" ]]; then
        metric_name="$arg"
        break
    fi
    prev="$arg"
done

case "$metric_name" in
    Count)
        cat <<EOF
{"Label":"Count","Datapoints":[{"Timestamp":"2023-01-01T00:00:00+00:00","Sum":20.0,"Unit":"None"},{"Timestamp":"2023-01-01T00:01:00+00:00","Sum":30.0,"Unit":"None"},{"Timestamp":"2023-01-01T00:02:00+00:00","Sum":50.0,"Unit":"None"}]}
EOF
        ;;
    4XXError)
        cat <<EOF
{"Label":"4XXError","Datapoints":[{"Timestamp":"2023-01-01T00:00:00+00:00","Sum":2.0,"Unit":"None"},{"Timestamp":"2023-01-01T00:01:00+00:00","Sum":3.0,"Unit":"None"}]}
EOF
        ;;
    5XXError)
        cat <<EOF
{"Label":"5XXError","Datapoints":[{"Timestamp":"2023-01-01T00:00:00+00:00","Sum":1.0,"Unit":"None"},{"Timestamp":"2023-01-01T00:01:00+00:00","Sum":1.0,"Unit":"None"}]}
EOF
        ;;
esac
