#!/bin/bash
case "$*" in
    --version)
        cat <<'EOF'
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
EOF
        ;;
    '-a --no-pager --plain --no-legend')
        cat <<'EOF'
proc-sys-fs-binfmt_misc.automount             loaded    active   waiting   Arbitrary Executable File Formats File System 
dev-disk-by\x2did-scsi\x2d0QEMU_QEMU_HARDDISK_drive\x2dscsi0\x2d0\x2d0\x2d0.device loaded    active   plugged   QEMU_HARDDISK
dev-disk-by\x2did-scsi\x2d0QEMU_QEMU_HARDDISK_drive\x2dscsi0\x2d0\x2d0\x2d0\x2dpart1.device loaded    active   plugged   QEMU_HARDDISK 1
dev-disk-by\x2dpath-pci\x2d0000:00:04.0\x2dscsi\x2d0:0:0:0.device loaded    active   plugged   QEMU_HARDDISK
dev-disk-by\x2dpath-pci\x2d0000:00:04.0\x2dscsi\x2d0:0:0:0\x2dpart1.device loaded    active   plugged   QEMU_HARDDISK 1
dev-disk-by\x2duuid-85ea49f1\x2d50e9\x2d4dc2\x2d83e4\x2d76499dffa11b.device loaded    active   plugged   QEMU_HARDDISK 1
dev-sda.device                                loaded    active   plugged   QEMU_HARDDISK
dev-sda1.device                               loaded    active   plugged   QEMU_HARDDISK 1
dev-ttyS0.device                              loaded    active   plugged   /dev/ttyS0
dev-ttyS1.device                              loaded    active   plugged   /dev/ttyS1
dev-ttyS2.device                              loaded    active   plugged   /dev/ttyS2
dev-ttyS3.device                              loaded    active   plugged   /dev/ttyS3
dev-virtio\x2dports-org.qemu.guest_agent.0.device loaded    active   plugged   /dev/virtio-ports/org.qemu.guest_agent.0
dev-vport2p1.device                           loaded    active   plugged   /dev/vport2p1
sys-devices-pci0000:00-0000:00:03.0-virtio0-net-eth0.device loaded    active   plugged   Virtio network device
sys-devices-pci0000:00-0000:00:04.0-virtio1-host2-target2:0:0-2:0:0:0-block-sda-sda1.device loaded    active   plugged   QEMU_HARDDISK 1
sys-devices-pci0000:00-0000:00:04.0-virtio1-host2-target2:0:0-2:0:0:0-block-sda.device loaded    active   plugged   QEMU_HARDDISK
sys-devices-pci0000:00-0000:00:05.0-virtio2-virtio\x2dports-vport2p1.device loaded    active   plugged   /sys/devices/pci0000:00/0000:00:05.0/virtio2/v
sys-devices-platform-serial8250-tty-ttyS1.device loaded    active   plugged   /sys/devices/platform/serial8250/tty/ttyS1
sys-devices-platform-serial8250-tty-ttyS2.device loaded    active   plugged   /sys/devices/platform/serial8250/tty/ttyS2
sys-devices-platform-serial8250-tty-ttyS3.device loaded    active   plugged   /sys/devices/platform/serial8250/tty/ttyS3
sys-devices-pnp0-00:04-tty-ttyS0.device       loaded    active   plugged   /sys/devices/pnp0/00:04/tty/ttyS0
sys-module-configfs.device                    loaded    active   plugged   /sys/module/configfs
sys-subsystem-net-devices-eth0.device         loaded    active   plugged   Virtio network device
-.mount                                       loaded    active   mounted   /
dev-hugepages.mount                           loaded    active   mounted   Huge Pages File System
dev-mqueue.mount                              loaded    active   mounted   POSIX Message Queue File System
proc-sys-fs-binfmt_misc.mount                 loaded    inactive dead      Arbitrary Executable File Formats File System
run-user-0.mount                              loaded    active   mounted   /run/user/0
sys-fs-fuse-connections.mount                 loaded    inactive dead      FUSE Control File System
sys-kernel-config.mount                       loaded    active   mounted   Configuration File System
sys-kernel-debug.mount                        loaded    active   mounted   Debug File System
sysroot.mount                                 not-found inactive dead      sysroot.mount
tmp.mount                                     loaded    inactive dead      Temporary Directory
var-run.mount                                 not-found inactive dead      var-run.mount
brandbot.path                                 loaded    active   waiting   Flexible branding
systemd-ask-password-console.path             loaded    inactive dead      Dispatch Password Requests to Console Director
systemd-ask-password-plymouth.path            loaded    active   waiting   Forward Password Requests to Plymouth Director
systemd-ask-password-wall.path                loaded    active   waiting   Forward Password Requests to Wall Directory Wa
session-187554.scope                          loaded    active   running   Session 187554 of user root
atd.service                                   loaded    active   running   Job spooling tools
auditd.service                                loaded    active   running   Security Auditing Service
brandbot.service                              loaded    inactive dead      Flexible Branding Service
cbd.service                                   loaded    active   running   Centreon Broker watchdog
centcore.service                              not-found inactive dead      centcore.service
centengine.service                            loaded    active   running   Centreon Engine
centreon-map.service                          loaded    failed   failed    Centreon Studio map server
centreon-nrpe3.service                        loaded    active   running   Nagios Remote Program Executor
centreon.service                              loaded    active   exited    One Service to rule them all.
chronyd.service                               loaded    active   running   NTP client/server
cloud-config.service                          loaded    active   exited    Apply the settings specified in cloud-config
cloud-final.service                           loaded    active   exited    Execute cloud user/final scripts
cloud-init-local.service                      loaded    active   exited    Initial cloud-init job (pre-networking)
cloud-init.service                            loaded    active   exited    Initial cloud-init job (metadata service crawl
cpupower.service                              loaded    inactive dead      Configure CPU power related settings
crond.service                                 loaded    active   running   Command Scheduler
dbus.service                                  loaded    active   running   D-Bus System Message Bus
display-manager.service                       not-found inactive dead      display-manager.service
dm-event.service                              loaded    inactive dead      Device-mapper event daemon
dracut-cmdline.service                        loaded    inactive dead      dracut cmdline hook
dracut-initqueue.service                      loaded    inactive dead      dracut initqueue hook
dracut-mount.service                          loaded    inactive dead      dracut mount hook
dracut-pre-mount.service                      loaded    inactive dead      dracut pre-mount hook
dracut-pre-pivot.service                      loaded    inactive dead      dracut pre-pivot and cleanup hook
dracut-pre-trigger.service                    loaded    inactive dead      dracut pre-trigger hook
dracut-pre-udev.service                       loaded    inactive dead      dracut pre-udev hook
dracut-shutdown.service                       loaded    inactive dead      Restore /run/initramfs
ebtables.service                              loaded    inactive dead      Ethernet Bridge Filtering tables
emergency.service                             loaded    inactive dead      Emergency Shell
exim.service                                  not-found inactive dead      exim.service
firewalld.service                             loaded    active   running   firewalld - dynamic firewall daemon
getty@tty1.service                            loaded    active   running   Getty on tty1
gorgoned.service                              loaded    active   running   Centreon Gorgone
haproxy.service                               loaded    active   running   HAProxy Load Balancer
httpd24-httpd.service                         loaded    active   running   The Apache HTTP Server
initrd-cleanup.service                        loaded    inactive dead      Cleaning Up and Shutting Down Daemons
initrd-parse-etc.service                      loaded    inactive dead      Reload Configuration from the Real Root
initrd-switch-root.service                    loaded    inactive dead      Switch Root
initrd-udevadm-cleanup-db.service             loaded    inactive dead      Cleanup udevd DB
ip6tables.service                             not-found inactive dead      ip6tables.service
ipset.service                                 not-found inactive dead      ipset.service
iptables.service                              not-found inactive dead      iptables.service
irqbalance.service                            loaded    inactive dead      irqbalance daemon
kdump.service                                 loaded    active   exited    Crash recovery kernel arming
kmod-static-nodes.service                     loaded    active   exited    Create list of required static device nodes fo
lvm2-activation.service                       not-found inactive dead      lvm2-activation.service
lvm2-lvmetad.service                          loaded    active   running   LVM2 metadata daemon
lvm2-lvmpolld.service                         loaded    inactive dead      LVM2 poll daemon
lvm2-monitor.service                          loaded    active   exited    Monitoring of LVM2 mirrors, snapshots etc. usi
mariadb.service                               loaded    active   running   MariaDB 10.5.17 database server
microcode.service                             loaded    inactive dead      Load CPU microcode update
network.service                               loaded    active   exited    LSB: Bring up/down networking
NetworkManager-wait-online.service            loaded    active   exited    Network Manager Wait Online
NetworkManager.service                        loaded    active   running   Network Manager
ntpd.service                                  not-found inactive dead      ntpd.service
ntpdate.service                               not-found inactive dead      ntpdate.service
php-fpm.service                               loaded    active   running   The PHP FastCGI Process Manager
plymouth-quit-wait.service                    loaded    inactive dead      Wait for Plymouth Boot Screen to Quit
plymouth-quit.service                         loaded    inactive dead      Terminate Plymouth Boot Screen
plymouth-read-write.service                   loaded    inactive dead      Tell Plymouth To Write Out Runtime Data
plymouth-start.service                        loaded    inactive dead      Show Plymouth Boot Screen
plymouth-switch-root.service                  loaded    inactive dead      Plymouth switch root service
polkit.service                                loaded    active   running   Authorization Manager
postfix.service                               loaded    active   running   Postfix Mail Transport Agent
rc-local.service                              loaded    inactive dead      /etc/rc.d/rc.local Compatibility
rescue.service                                loaded    inactive dead      Rescue Shell
rhel-autorelabel-mark.service                 loaded    inactive dead      Mark the need to relabel after reboot
rhel-autorelabel.service                      loaded    inactive dead      Relabel all filesystems, if necessary
rhel-configure.service                        loaded    inactive dead      Reconfigure the system on administrator reques
rhel-dmesg.service                            loaded    active   exited    Dump dmesg to /var/log/dmesg
rhel-domainname.service                       loaded    active   exited    Read and set NIS domainname from /etc/sysconfi
rhel-import-state.service                     loaded    active   exited    Import network configuration from initramfs
rhel-loadmodules.service                      loaded    inactive dead      Load legacy module configuration
rhel-readonly.service                         loaded    active   exited    Configure read-only root support
rpcbind.service                               loaded    active   running   RPC bind service
rsyslog.service                               loaded    active   running   System Logging Service
selinux-policy-migrate-local-changes@targeted.service loaded    inactive dead      Migrate local SELinux policy changes from the 
sendmail.service                              not-found inactive dead      sendmail.service
snmpd.service                                 loaded    active   running   Simple Network Management Protocol (SNMP) Daem
sntp.service                                  not-found inactive dead      sntp.service
sshd-keygen.service                           loaded    inactive dead      OpenSSH Server Key Generation
sshd.service                                  loaded    active   running   OpenSSH server daemon
syslog.service                                not-found inactive dead      syslog.service
systemd-ask-password-console.service          loaded    inactive dead      Dispatch Password Requests to Console
systemd-ask-password-plymouth.service         loaded    inactive dead      Forward Password Requests to Plymouth
systemd-ask-password-wall.service             loaded    inactive dead      Forward Password Requests to Wall
systemd-binfmt.service                        loaded    inactive dead      Set Up Additional Binary Formats
systemd-firstboot.service                     loaded    inactive dead      First Boot Wizard
systemd-fsck-root.service                     loaded    active   exited    File System Check on Root Device
systemd-hwdb-update.service                   loaded    inactive dead      Rebuild Hardware Database
systemd-initctl.service                       loaded    inactive dead      /dev/initctl Compatibility Daemon
systemd-journal-catalog-update.service        loaded    inactive dead      Rebuild Journal Catalog
systemd-journal-flush.service                 loaded    active   exited    Flush Journal to Persistent Storage
systemd-journald.service                      loaded    active   running   Journal Service
systemd-logind.service                        loaded    active   running   Login Service
systemd-machine-id-commit.service             loaded    inactive dead      Commit a transient machine-id on disk
systemd-modules-load.service                  loaded    inactive dead      Load Kernel Modules
systemd-random-seed.service                   loaded    active   exited    Load/Save Random Seed
systemd-readahead-collect.service             loaded    inactive dead      Collect Read-Ahead Data
systemd-readahead-done.service                loaded    inactive dead      Stop Read-Ahead Data Collection
systemd-readahead-replay.service              loaded    inactive dead      Replay Read-Ahead Data
systemd-reboot.service                        loaded    inactive dead      Reboot
systemd-remount-fs.service                    loaded    active   exited    Remount Root and Kernel File Systems
systemd-shutdownd.service                     loaded    inactive dead      Delayed Shutdown Service
systemd-sysctl.service                        loaded    active   exited    Apply Kernel Variables
systemd-sysusers.service                      not-found inactive dead      systemd-sysusers.service
systemd-timesyncd.service                     not-found inactive dead      systemd-timesyncd.service
systemd-tmpfiles-clean.service                loaded    inactive dead      Cleanup of Temporary Directories
systemd-tmpfiles-setup-dev.service            loaded    active   exited    Create Static Device Nodes in /dev
systemd-tmpfiles-setup.service                loaded    active   exited    Create Volatile Files and Directories
systemd-udev-trigger.service                  loaded    active   exited    udev Coldplug all Devices
systemd-udevd.service                         loaded    active   running   udev Kernel Device Manager
systemd-update-done.service                   loaded    inactive dead      Update is Completed
systemd-update-utmp-runlevel.service          loaded    inactive dead      Update UTMP about System Runlevel Changes
systemd-update-utmp.service                   loaded    active   exited    Update UTMP about System Boot/Shutdown
systemd-user-sessions.service                 loaded    active   exited    Permit User Sessions
systemd-vconsole-setup.service                loaded    active   exited    Setup Virtual Console
tuned.service                                 loaded    active   running   Dynamic System Tuning Daemon
xdm.service                                   not-found inactive dead      xdm.service
ypbind.service                                not-found inactive dead      ypbind.service
yppasswdd.service                             not-found inactive dead      yppasswdd.service
ypserv.service                                not-found inactive dead      ypserv.service
ypxfrd.service                                not-found inactive dead      ypxfrd.service
-.slice                                       loaded    active   active    Root Slice
system-getty.slice                            loaded    active   active    system-getty.slice
system-selinux\x2dpolicy\x2dmigrate\x2dlocal\x2dchanges.slice loaded    active   active    system-selinux\x2dpolicy\x2dmigrate\x2dlocal\x
system.slice                                  loaded    active   active    System Slice
user-0.slice                                  loaded    active   active    User Slice of root
user.slice                                    loaded    active   active    User and Session Slice
dbus.socket                                   loaded    active   running   D-Bus System Message Bus Socket
dm-event.socket                               loaded    active   listening Device-mapper event daemon FIFOs
lvm2-lvmetad.socket                           loaded    active   running   LVM2 metadata daemon socket
lvm2-lvmpolld.socket                          loaded    active   listening LVM2 poll daemon socket
nrpe.socket                                   not-found inactive dead      nrpe.socket
rpcbind.socket                                loaded    active   running   RPCbind Server Activation Socket
sshd.socket                                   loaded    inactive dead      OpenSSH Server Socket
syslog.socket                                 loaded    inactive dead      Syslog Socket
systemd-initctl.socket                        loaded    active   listening /dev/initctl Compatibility Named Pipe
systemd-journald.socket                       loaded    active   running   Journal Socket
systemd-shutdownd.socket                      loaded    active   listening Delayed Shutdown Socket
systemd-udevd-control.socket                  loaded    active   running   udev Control Socket
systemd-udevd-kernel.socket                   loaded    active   running   udev Kernel Socket
basic.target                                  loaded    active   active    Basic System
cloud-config.target                           loaded    active   active    Cloud-config availability
cloud-init.target                             loaded    active   active    Cloud-init target
cryptsetup.target                             loaded    active   active    Local Encrypted Volumes
emergency.target                              loaded    inactive dead      Emergency Mode
final.target                                  loaded    inactive dead      Final Step
firewalld.target                              not-found inactive dead      firewalld.target
getty-pre.target                              loaded    inactive dead      Login Prompts (Pre)
getty.target                                  loaded    active   active    Login Prompts
graphical.target                              loaded    inactive dead      Graphical Interface
initrd-fs.target                              loaded    inactive dead      Initrd File Systems
initrd-root-fs.target                         loaded    inactive dead      Initrd Root File System
initrd-switch-root.target                     loaded    inactive dead      Switch Root
initrd.target                                 loaded    inactive dead      Initrd Default Target
local-fs-pre.target                           loaded    active   active    Local File Systems (Pre)
local-fs.target                               loaded    active   active    Local File Systems
multi-user.target                             loaded    active   active    Multi-User System
network-online.target                         loaded    active   active    Network is Online
network-pre.target                            loaded    active   active    Network (Pre)
network.target                                loaded    active   active    Network
nss-lookup.target                             loaded    inactive dead      Host and Network Name Lookups
nss-user-lookup.target                        loaded    inactive dead      User and Group Name Lookups
paths.target                                  loaded    active   active    Paths
remote-fs-pre.target                          loaded    inactive dead      Remote File Systems (Pre)
remote-fs.target                              loaded    active   active    Remote File Systems
rescue.target                                 loaded    inactive dead      Rescue Mode
rpcbind.target                                loaded    active   active    RPC Port Mapper
shutdown.target                               loaded    inactive dead      Shutdown
slices.target                                 loaded    active   active    Slices
sockets.target                                loaded    active   active    Sockets
swap.target                                   loaded    active   active    Swap
sysinit.target                                loaded    active   active    System Initialization
syslog.target                                 not-found inactive dead      syslog.target
time-sync.target                              loaded    inactive dead      System Time Synchronized
timers.target                                 loaded    active   active    Timers
umount.target                                 loaded    inactive dead      Unmount All Filesystems
systemd-readahead-done.timer                  loaded    inactive dead      Stop Read-Ahead Data Collection 10s After Comp
systemd-tmpfiles-clean.timer                  loaded    active   waiting   Daily Cleanup of Temporary Directories
EOF
        ;;
    *)
        echo "Unknown option"
        ;;
esac

