*** Settings ***
Documentation       Check Huawei equipments in SNMP.

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}resources/import.resource

Test Timeout        120s
Test Setup          Ctn Generic Suite Setup

*** Variables ***
${CMD}      ${CENTREON_PLUGINS} --plugin=network::huawei::standard::snmp::plugin


*** Test Cases ***
list-interfaces ${tc}
    [Tags]    network    Stormshield
    ${command}    Catenate
    ...    ${CMD}
    ...    --mode=list-interfaces
    ...    --hostname=${HOSTNAME}
    ...    --snmp-version=${SNMPVERSION}
    ...    --snmp-port=${SNMPPORT}
    ...    --snmp-community=network/huawei/wlc/snmp/slim_huawei_wlc
    ...    --snmp-timeout=1
    ...    ${extra_options}
 
    Ctn Verify Command Output    ${command}    ${expected_result}

    Examples:        tc   extra_options                                               expected_result    --
            ...      1    --verbose                                                   List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][type = ethernetCsmacd] 'Anonymized 232' [speed = 10000][status = down][id = 104][type = ethernetCsmacd]
            ...      2    --interface=1                                               List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback]
            ...      3    --name                                                      List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][type = ethernetCsmacd] 'Anonymized 232' [speed = 10000][status = down][id = 104][type = ethernetCsmacd]
            ...      4    --speed                                                     List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][type = ethernetCsmacd] 'Anonymized 232' [speed = 10000][status = down][id = 104][type = ethernetCsmacd]
            ...      5    --skip-speed0                                               Argument "" isn't numeric in numeric eq (==) at /home/code/src/snmp_standard/mode/listinterfaces.pm line 164. Argument "" isn't numeric in numeric eq (==) at /home/code/src/snmp_standard/mode/listinterfaces.pm line 164. Argument "" isn't numeric in numeric eq (==) at /home/code/src/snmp_standard/mode/listinterfaces.pm line 164. Argument "" isn't numeric in numeric eq (==) at /home/code/src/snmp_standard/mode/listinterfaces.pm line 164. Argument "" isn't numeric in numeric eq (==) at /home/code/src/snmp_standard/mode/listinterfaces.pm line 164. Argument "" isn't numeric in numeric eq (==) at /home/code/src/snmp_standard/mode/listinterfaces.pm line 164.
            ...      6    --oid-filter='ifName'                                       List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][type = ethernetCsmacd] 'Anonymized 232' [speed = 10000][status = down][id = 104][type = ethernetCsmacd]
            ...      7    --oid-display='ifAlias'                                     List interfaces: '' [speed = ][status = up][id = 1][type = softwareLoopback] '' [speed = 10000][status = down][id = 10][type = ethernetCsmacd] '' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] '' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 102][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 103][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 104][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 105][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 106][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 107][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 108][type = ethernetCsmacd] '' [speed = 10000][status = down][id = 109][type = ethernetCsmacd]
            ...      8    --display-transform-src --display-transform-dst             List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][type = ethernetCsmacd] 'Anonymized 232' [speed = 10000][status = down][id = 104][type = ethernetCsmacd]
            ...      9    --add-extra-oid='alias,.1.3.6.1.2.1.31.1.1.1.18'            List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][alias = ][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][alias = ][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][alias = ][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][alias = ][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][alias = ][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][alias = ][type = ethernetCsmacd]
            ...      10   --add-mac-address                                           List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][macaddress = 41:6e:6f:6e:79:6d:69:7a:65:64:20:32:34:38][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][macaddress = 41:6e:6f:6e:79:6d:69:7a:65:64:20:30:38:34][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][macaddress = 41:6e:6f:6e:79:6d:69:7a:65:64:20:30:30:33][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][macaddress = 41:6e:6f:6e:79:6d:69:7a:65:64:20:31:36:33][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][macaddress = 41:6e:6f:6e:79:6d:69:7a:65:64:20:31:31:33][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][macaddress = 41:6e:6f:6e:79:6d:69:7a:65:64:20:30:31:38][type = ethernetCsmacd]
            ...      11   --filter-status='up'                                        List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback] skipping interface 'Anonymized 012': no matching filter status 'Anonymized 179' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] skipping interface 'Anonymized 221': no matching filter status skipping interface 'Anonymized 003': no matching filter status skipping interface 'Anonymized 232': no matching filter status skipping interface 'Anonymized 109': no matching filter status skipping interface 'Anonymized 034': no matching filter status skipping interface 'Anonymized 012': no matching filter status skipping interface 'Anonymized 016': no matching filter status skipping interface 'Anonymized 214': no matching filter status
            ...      12   --use-adminstatus='up'                                      List interfaces: 'Anonymized 250' [speed = ][status = up][id = 1][type = softwareLoopback] 'Anonymized 012' [speed = 10000][status = down][id = 10][type = ethernetCsmacd] 'Anonymized 179' [speed = 1000][status = up][id = 100][type = ethernetCsmacd] 'Anonymized 254' [speed = 1000][status = up][id = 101][type = ethernetCsmacd] 'Anonymized 221' [speed = 10000][status = down][id = 102][type = ethernetCsmacd] 'Anonymized 003' [speed = 10000][status = down][id = 103][type = ethernetCsmacd] 'Anonymized 232' [speed = 10000][status = down][id = 104][type = ethernetCsmacd]