name: "deb-delivery"
description: "Deliver DEB packages"
inputs:
  cache-key:
    description: "The plugin packaged cache key"
    required: true
  plugin-list:
    description: "plugin names to install from the cache"
    required: true
  package-extension:
    description: "either rpm or deb, used to install the plugin with the correct binary"
    required: true

runs:
  using: "composite"
  steps:

    - name: get plugin cached
      uses: actions/cache/restore@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: ./*.${{ inputs.package-extension }}
        key: ${{ inputs.cache-key }}
        fail-on-cache-miss: true

    - name: install plugin for deb distrib
      shell: bash
      run: |  
        echo "plugin list is : \n\n " 
        echo ${{inputs.plugin-list}}
        echo "\n\n executing....\n\n"
        python3 .github/scripts/test-all-plugins.py ${{inputs.package-extension}} ${{inputs.plugin-list}}
