name: "release-sources"
description: "Release sources on download.centreon.com"
inputs:
  bucket_directory:
    description: The bucket directory
    required: true
  module_directory:
    description: The module directory
    required: true
  module_name:
    description: The module name
    required: true
  version:
    description: The module version
    required: true
  release:
    description: The module release
    required: true
  token_download_centreon_com:
    description: The token to call download.centreon.com api
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup awscli
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        sudo unzip -q awscliv2.zip
        sudo ./aws/install
      shell: bash

    - name: Publish on download.centreon.com
      env:
        MODULE_NAME: ${{ inputs.module_name }}
        VERSION: ${{ inputs.version }}
        MODULE_DIRECTORY: ${{ inputs.module_directory }}
        BUCKET_DIRECTORY: ${{ inputs.bucket_directory }}
        TOKEN_DOWNLOAD: ${{ inputs.token_download_centreon_com }}
        RELEASE: ${{ inputs.release }}
      run: |
        SRC_FILE="${MODULE_NAME}-${VERSION}.tar.gz"

        mv "$MODULE_DIRECTORY" "${MODULE_NAME}-${VERSION}"
        tar czf $SRC_FILE "${MODULE_NAME}-${VERSION}"

        SRC_HASH=$(md5sum $SRC_FILE | cut -d ' ' -f 1)
        SRC_SIZE=$(stat -c '%s' $SRC_FILE)

        aws s3 cp --acl public-read "$SRC_FILE" "s3://centreon-download/public/${BUCKET_DIRECTORY}/$SRC_FILE"
        curl --fail "https://download.centreon.com/api/?token=${TOKEN_DOWNLOAD}&product=${MODULE_NAME}&release=${RELEASE}&version=${VERSION}&extension=tar.gz&md5=$SRC_HASH&size=$SRC_SIZE&ddos=0&dryrun=0"
      shell: bash
