#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Constants/AttributeLength.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Constants;

%AttributeLength =
  (
   2027                                  => 12,
   2028                                  => 8,
   2001                                  => 256,
   2019                                  => 48,
   2002                                  => 48,
   2052                                  => 64,
   2039                                  => 12,
   2026                                  => 128,
   2029                                  => 48,
   2030                                  => 48,
   2034                                  => 32,
   2033                                  => 128,
   2003                                  => 48,
   2004                                  => 12,
   2005                                  => 8,
   2006                                  => 48,
   2025                                  => 48,
   2007                                  => 128,
   2008                                  => 48,
   2009                                  => 64,
   2010                                  => 48,
   2011                                  => 64,
   2012                                  => 48,
   2013                                  => 64,
   2014                                  => 64,
   2032                                  => 48,
   2015                                  => 48,
   2016                                  => 48,
   2017                                  => 48,
   2018                                  => 48,
   2035                                  => 48,
   2036                                  => 48,
   2022                                  => 8,
   2023                                  => 64,
   2021                                  => 128,
   2024                                  => 48,
  );

1;
