#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Constants/AttributeString.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Constants;

%AttributeString =
  (
   2027                                  => "AlterationDate",
   2028                                  => "AlterationTime",
   2001                                  => "ApplId",
   2019                                  => "BackoutRequeueName",
   2002                                  => "BaseQName",
   2026                                  => "ChannelAutoDefExit",
   2037                                  => "ClusterDate",
   2029                                  => "ClusterName",
   2030                                  => "ClusterNamelist",
   2031                                  => "QMgrName",
   2038                                  => "ClusterTime",
   2034                                  => "ClusterWorkLoadData",
   2033                                  => "ClusterWorkLoadExit",
   2003                                  => "CommandInputQName",
   2004                                  => "CreationDate",
   2005                                  => "CreationTime",
   2006                                  => "DeadLetterQName",
   2025                                  => "DefXmitQName",
   2007                                  => "EnvData",
   2008                                  => "InitiationQName",
   2009                                  => "NamelistDesc",
   2010                                  => "NamelistName",
   2020                                  => "Names",
   2011                                  => "ProcessDesc",
   2012                                  => "ProcessName ",
   2012                                  => "ProcessName",
   2013                                  => "QDesc",
   2014                                  => "QMgrDesc",
   2032                                  => "QMgrIdentifier",
   2015                                  => "QMgrName",
   2016                                  => "QName",
   2017                                  => "RemoteQMgrName",
   2018                                  => "RemoteQName",
   2035                                  => "RepositoryName",
   2036                                  => "RepositoryNamelist",
   2023                                  => "TriggerData",
   2021                                  => "UserData",
   2024                                  => "XmitQName",

   1                                     => "ApplType",
   47                                    => "AuthorityEvent",
   22                                    => "BackoutThreshold",
   55                                    => "ChannelAutoDef",
   56                                    => "ChannelAutoDefEvent",
   59                                    => "ClusterQType",
   58                                    => "ClusterWorkLoadLength",
   2                                     => "CodedCharSetId",
   31                                    => "CommandLevel",
   3                                     => "CurrentQDepth",
   7                                     => "DefinitionType",
   61                                    => "DefBind",
   4                                     => "DefInputOpenOption",
   5                                     => "DefPersistence",
   6                                     => "DefPriority",
   34                                    => "DistLists",
   8                                     => "HardenGetBackout",
   36                                    => "HighQDepth",
   48                                    => "InhibitEvent",
   9                                     => "InhibitGet",
   10                                    => "InhibitPut",
   49                                    => "LocalEvent",
   11                                    => "MaxHandles",
   13                                    => "MaxMsgLength",
   14                                    => "MaxPriority",
   15                                    => "MaxQDepth",
   33                                    => "MaxUncommittedMsgs",
   16                                    => "MsgDeliverySequence",
   38                                    => "MsgDeqCount",
   37                                    => "MsgEnqCount",
   17                                    => "OpenInputCount",
   18                                    => "OpenOutputCount",
   53                                    => "PerformanceEvent",
   32                                    => "Platform",
   43                                    => "QDepthHighEvent",
   40                                    => "QDepthHighLimit",
   44                                    => "QDepthLowEvent",
   41                                    => "QDepthLowLimit",
   42                                    => "QDepthMaxEvent",
   54                                    => "QServiceInterval",
   46                                    => "QServiceIntervalEvent",
   20                                    => "QType",
   50                                    => "RemoteEvent",
   21                                    => "RetentionInterval",
   45                                    => "Scope",
   23                                    => "Shareability",
   52                                    => "StartStopEvent",
   30                                    => "SyncPoint",
   35                                    => "TimeSinceReset",
   24                                    => "TriggerControl",
   29                                    => "TriggerDepth",
   25                                    => "TriggerInterval",
   26                                    => "TriggerMsgPriority",
   28                                    => "TriggerType",
   12                                    => "Usage",
  );

1;
