#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Constants/ReasonQualifierText.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Constants;

%ReasonQualifierText =
  (
   12                                => "Bridge has been stopped but there is an error reported.",
   11                                => "Bridge has been stopped with either a zero return code or a warning return code.",
   10                                => "Channel has been closed and it is in a stopped state.",
   8                                 => "Channel has been closed, but there is an error reported and the channel is not in stopped or retry state.",
   7                                 => "Channel has been closed with either a zero return code or a warning return code.",
   9                                 => "Channel has been closed and it is in retry state.",
   3                                 => "Close not authorized.",
   4                                 => "Command not authorized.",
   1                                 => "Connection not authorized.",
   2                                 => "Open not authorized. ",
   6                                 => "Queue manager quiescing.",
   5                                 => "Queue manager stopping.",
   14                                => "The SSL or TLS client CipherSpec does not match that on the SSL or TLS server channel definition.",
   15                                => "The SSL or TLS server channel definition specified either SSLCAUTH(REQUIRED) or a SSLPEER value that was not blank, but the SSL or TLS client did not provide a certificate.",
   13                                => "The key exchange / authentication failure arose during the SSL or TLS handshake.",
   16                                => "The Distinguished Name in the certificate sent by one end of the SSL or TLS channel does not match the peer name on the end of the channel definition at the other end of the SSL or TLS channel.",
   19                                => "An OCSP responder returned a response of Unknown.",
   17                                => "Subscribe not authorized.",
   20                                => "Missing system authority.",
  );

#
# Note that MQRQ_SSL_CIPHER_SPEC_ERROR could also mean:
#
#   An invalid CipherSpec has been specified.
#
#   A CipherSpec has only been specified on one end of the SSL or TLS
#   channel.
#
# The entry that was selected for inclusion in the above hash was
# selected because it can be interpreted in a way that includes these
# other two.
#

1;
