#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Constants/ReasonQualifierMacro.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Constants;

%ReasonQualifierMacro =
  (
   12                                => "MQRQ_BRIDGE_STOPPED_ERROR",
   11                                => "MQRQ_BRIDGE_STOPPED_OK",
   10                                => "MQRQ_CHANNEL_STOPPED_DISABLED",
   8                                 => "MQRQ_CHANNEL_STOPPED_ERROR",
   7                                 => "MQRQ_CHANNEL_STOPPED_OK",
   9                                 => "MQRQ_CHANNEL_STOPPED_RETRY",
   3                                 => "MQRQ_CLOSE_NOT_AUTHORIZED",
   4                                 => "MQRQ_CMD_NOT_AUTHORIZED",
   1                                 => "MQRQ_CONN_NOT_AUTHORIZED",
   2                                 => "MQRQ_OPEN_NOT_AUTHORIZED",
   6                                 => "MQRQ_Q_MGR_QUIESCING",
   5                                 => "MQRQ_Q_MGR_STOPPING",
   14                                => "MQRQ_SSL_CIPHER_SPEC_ERROR",
   15                                => "MQRQ_SSL_CLIENT_AUTH_ERROR",
   13                                => "MQRQ_SSL_HANDSHAKE_ERROR",
   16                                => "MQRQ_SSL_PEER_NAME_ERROR",
   19                                => "MQRQ_SSL_UNKNOWN_REVOCATION",
   18                                => "MQRQ_SUB_DEST_NOT_AUTHORIZED",
   17                                => "MQRQ_SUB_NOT_AUTHORIZED",
   20                                => "MQRQ_SYS_CONN_NOT_AUTHORIZED",
  );

1;
