#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Constants/ValidPutMsgRecFields.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Constants;

#
# These are used to validate MQPMR fields
#
@ValidPutMsgRecFields =
  qw(
     MsgId
     CorrelId
     GroupId
     Feedback
     AccountingToken
    );

#
# The wierd ?: construct:
#
#   defined &foo ? &foo : undef
#
# is to support V2, since those constants are V5 specific, and this is
# the cleanest way to avoid them.  This hash is part of the
# distribution list support, and won't be used in V2.
#
%ValidPutMsgRecFields =
  (

   MsgId		=>
   {
    Flag		=> 1,
    Size		=> 24,
   },

   CorrelId		=>
   {
    Flag		=> 2,
    Size		=> 24,
   },

   GroupId		=>
   {
    Flag		=> 4,
    Size		=> 24,
   },

   Feedback		=>
   {
    Flag		=> 8,
    Size		=> "MQLONG",
   },

   AccountingToken	=>
   {
    Flag		=> 16,
    Size		=> 32,
   },

  );

1;
