*** Settings ***
Documentation       HP Athonet Node Exporter plugin

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}         ${CURDIR}${/}mockoon.json

${BASE_URL}             http://${HOSTNAME}:${APIPORT}
${CMD}                  ${CENTREON_PLUGINS} --plugin=network::hp::athonet::nodeexporter::api::plugin --mode=eir --hostname=${HOSTNAME} --port=${APIPORT} --proto http --api-username=1 --api-password=1



*** Test Cases ***
EIR (Equipment Identity Register) ${tc}
    [Tags]    network    hp    api
    ${command}    Catenate
    ...    ${CMD}
    ...    ${extra_options}

    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:         tc  extra_options                                                            expected_result    --
            ...       1   ${EMPTY}                                                                 OK: All clusters are ok - All diameter connections are ok | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       2   --unknown-node-status='%\\{status\\} eq "running"'                       UNKNOWN: cluster repository 'Eir.DataLayer.Repository' node 'eir@fd10:211:211:1::4:1' status: running - node 'eir@fd10:211:211:2::4:1' status: running - cluster repository 'xdb recovery configuration' node 'eir@fd10:211:211:1::4:1' status: running - node 'eir@fd10:211:211:2::4:1' status: running | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       3   --warning-node-status='%\\{status\\} eq "running"'                       WARNING: cluster repository 'Eir.DataLayer.Repository' node 'eir@fd10:211:211:1::4:1' status: running - node 'eir@fd10:211:211:2::4:1' status: running - cluster repository 'xdb recovery configuration' node 'eir@fd10:211:211:1::4:1' status: running - node 'eir@fd10:211:211:2::4:1' status: running | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       4   --critical-node-status='%\\{status\\} eq "running"'                      CRITICAL: cluster repository 'Eir.DataLayer.Repository' node 'eir@fd10:211:211:1::4:1' status: running - node 'eir@fd10:211:211:2::4:1' status: running - cluster repository 'xdb recovery configuration' node 'eir@fd10:211:211:1::4:1' status: running - node 'eir@fd10:211:211:2::4:1' status: running | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       5   --unknown-diameter-connection-status='%\\{status\\} eq "up"'             UNKNOWN: diameter stack 'diam_default' origin host 'site1-dra01-local.epc.mnc502.mcc208.3gppnetwork.org' connection status: up - diameter stack 'diam_default' origin host 'site2-dra01-local.epc.mnc502.mcc208.3gppnetwork.org' connection status: up | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       6   --warning-diameter-connection-status='%\\{status\\} eq "up"'             WARNING: diameter stack 'diam_default' origin host 'site1-dra01-local.epc.mnc502.mcc208.3gppnetwork.org' connection status: up - diameter stack 'diam_default' origin host 'site2-dra01-local.epc.mnc502.mcc208.3gppnetwork.org' connection status: up | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       7   --critical-diameter-connection-status='%\\{status\\} eq "up"'            CRITICAL: diameter stack 'diam_default' origin host 'site1-dra01-local.epc.mnc502.mcc208.3gppnetwork.org' connection status: up - diameter stack 'diam_default' origin host 'site2-dra01-local.epc.mnc502.mcc208.3gppnetwork.org' connection status: up | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       8   --warning-clusters-detected=1                                            WARNING: Number of clusters detected: 2 | 'clusters.detected.count'=2;0:1;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       9   --critical-clusters-detected=1                                           CRITICAL: Number of clusters detected: 2 | 'clusters.detected.count'=2;;0:1;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      10   --warning-cluster-nodes-detected=1                                       WARNING: cluster repository 'Eir.DataLayer.Repository' number of nodes detected: 2 - cluster repository 'xdb recovery configuration' number of nodes detected: 2 | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;0:1;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;0:1;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      11   --critical-cluster-nodes-detected=1                                      CRITICAL: cluster repository 'Eir.DataLayer.Repository' number of nodes detected: 2 - cluster repository 'xdb recovery configuration' number of nodes detected: 2 | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;0:1;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;0:1;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      12   --warning-cluster-nodes-running=1                                        WARNING: cluster repository 'Eir.DataLayer.Repository' number of nodes running: 2 - cluster repository 'xdb recovery configuration' number of nodes running: 2 | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;0:1;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;0:1;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      13   --critical-cluster-nodes-running=1                                       CRITICAL: cluster repository 'Eir.DataLayer.Repository' number of nodes running: 2 - cluster repository 'xdb recovery configuration' number of nodes running: 2 | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;0:1;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;0:1;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      14   --warning-cluster-nodes-notrunning=1:                                    WARNING: cluster repository 'Eir.DataLayer.Repository' number of nodes not running: 0 - cluster repository 'xdb recovery configuration' number of nodes not running: 0 | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;1:;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;1:;;0;2
            ...      15   --critical-cluster-nodes-notrunning=1:                                   CRITICAL: cluster repository 'Eir.DataLayer.Repository' number of nodes not running: 0 - cluster repository 'xdb recovery configuration' number of nodes not running: 0 | 'clusters.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.detected.count'=2;;;0; 'Eir.DataLayer.Repository#cluster.nodes.running.count'=2;;;0;2 'Eir.DataLayer.Repository#cluster.nodes.notrunning.count'=0;;1:;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;1:;0;2

