*** Settings ***
Documentation       HP Athonet Node Exporter plugin

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${INJECT_PERL}      -Mnrf_date -I${CURDIR}
${MOCKOON_JSON}         ${CURDIR}${/}mockoon.json

${BASE_URL}             http://${HOSTNAME}:${APIPORT}
${CMD}                  ${CENTREON_PLUGINS} --plugin=network::hp::athonet::nodeexporter::api::plugin --mode=nrf --hostname=${HOSTNAME} --port=${APIPORT} --proto http --api-username=1 --api-password=1



*** Test Cases ***
NRF (Network Repository Function) ${tc}
    [Tags]    network    hp    api
    ${OLD_PERL5OPT}=    Get Environment Variable    PERL5OPT    default=
    Set Environment Variable    PERL5OPT    ${INJECT_PERL} ${OLD_PERL5OPT}

    ${command}    Catenate
    ...    ${CMD}
    ...    ${extra_options}

    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:         tc  extra_options                                                            expected_result    --
            ...       1   ${EMPTY}                                                                 OK: All registration network functions are ok - All clusters are ok | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       2   --unknown-node-status='%\\{status\\} eq "running"'                       UNKNOWN: cluster repository 'repository' node 'nrf@ab34:123:456:1::1:1' status: running - node 'nrf@ab34:123:456:2::1:1' status: running - cluster repository 'xdb recovery configuration' node 'nrf@ab34:123:456:1::1:1' status: running - node 'nrf@ab34:123:456:2::1:1' status: running | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       3   --warning-node-status='%\\{status\\} eq "running"'                       WARNING: cluster repository 'repository' node 'nrf@ab34:123:456:1::1:1' status: running - node 'nrf@ab34:123:456:2::1:1' status: running - cluster repository 'xdb recovery configuration' node 'nrf@ab34:123:456:1::1:1' status: running - node 'nrf@ab34:123:456:2::1:1' status: running | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       4   --critical-node-status='%\\{status\\} eq "running"'                      CRITICAL: cluster repository 'repository' node 'nrf@ab34:123:456:1::1:1' status: running - node 'nrf@ab34:123:456:2::1:1' status: running - cluster repository 'xdb recovery configuration' node 'nrf@ab34:123:456:1::1:1' status: running - node 'nrf@ab34:123:456:2::1:1' status: running | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       5   --unknown-nf-registration-status='%\\{status\\} eq "registered"'         UNKNOWN: registration network function 'CHF' status: registered - registration network function 'EIR' status: registered - registration network function 'PCF' status: registered - registration network function 'SMF' status: registered - registration network function 'UDM' status: registered - registration network function 'UDR' status: registered | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       6   --warning-nf-registration-status='%\\{status\\} eq "registered"'         WARNING: registration network function 'CHF' status: registered - registration network function 'EIR' status: registered - registration network function 'PCF' status: registered - registration network function 'SMF' status: registered - registration network function 'UDM' status: registered - registration network function 'UDR' status: registered | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       7   --critical-nf-registration-status='%\\{status\\} eq "registered"'        CRITICAL: registration network function 'CHF' status: registered - registration network function 'EIR' status: registered - registration network function 'PCF' status: registered - registration network function 'SMF' status: registered - registration network function 'UDM' status: registered - registration network function 'UDR' status: registered | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       8   --warning-clusters-detected=1                                            WARNING: Number of clusters detected: 2 | 'clusters.detected.count'=2;0:1;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       9   --critical-clusters-detected=1                                           CRITICAL: Number of clusters detected: 2 | 'clusters.detected.count'=2;;0:1;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      10   --warning-cluster-nodes-detected=1                                       WARNING: cluster repository 'repository' number of nodes detected: 2 - cluster repository 'xdb recovery configuration' number of nodes detected: 2 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;0:1;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;0:1;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      11   --critical-cluster-nodes-detected=1                                      CRITICAL: cluster repository 'repository' number of nodes detected: 2 - cluster repository 'xdb recovery configuration' number of nodes detected: 2 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;0:1;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;0:1;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      12   --warning-cluster-nodes-running=1                                        WARNING: cluster repository 'repository' number of nodes running: 2 - cluster repository 'xdb recovery configuration' number of nodes running: 2 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;0:1;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;0:1;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      13   --critical-cluster-nodes-running=1                                       CRITICAL: cluster repository 'repository' number of nodes running: 2 - cluster repository 'xdb recovery configuration' number of nodes running: 2 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;0:1;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;0:1;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      14   --warning-cluster-nodes-notrunning=1:                                    WARNING: cluster repository 'repository' number of nodes not running: 0 - cluster repository 'xdb recovery configuration' number of nodes not running: 0 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;1:;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;1:;;0;2
            ...      15   --critical-cluster-nodes-notrunning=1:                                   CRITICAL: cluster repository 'repository' number of nodes not running: 0 - cluster repository 'xdb recovery configuration' number of nodes not running: 0 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;1:;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;1:;0;2
            ...      16   --warning-nf-registrations-detected=0                                    WARNING: Number of network function registrations detected: 12 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;0:0;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      17   --critical-nf-registrations-detected=0                                   CRITICAL: Number of network function registrations detected: 12 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;0:0;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      18   --warning-nf-registrations-registered=0                                  WARNING: Number of network function registrations registered: 12 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;0:0;;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      19   --critical-nf-registrations-registered=0                                 CRITICAL: Number of network function registrations registered: 12 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;0:0;0;12 'nf.registrations.suspended.count'=0;;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      20   --warning-nf-registrations-suspended=1:                                  WARNING: Number of network function registrations suspended: 0 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;1:;;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      21   --critical-nf-registrations-suspended=1:                                 CRITICAL: Number of network function registrations suspended: 0 | 'clusters.detected.count'=2;;;0; 'nf.registrations.detected.count'=12;;;0; 'nf.registrations.registered.count'=12;;;0;12 'nf.registrations.suspended.count'=0;;1:;0;12 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789623s;;;0; 'nf.registration.last.seconds'=16789624s;;;0; 'repository#cluster.nodes.detected.count'=2;;;0; 'repository#cluster.nodes.running.count'=2;;;0;2 'repository#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2


