*** Settings ***
Documentation       HP Athonet Node Exporter plugin

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}         ${CURDIR}${/}mockoon.json

${BASE_URL}             http://${HOSTNAME}:${APIPORT}
${CMD}                  ${CENTREON_PLUGINS} --plugin=network::hp::athonet::nodeexporter::api::plugin --mode=udm --hostname=${HOSTNAME} --port=${APIPORT} --proto http --api-username=1 --api-password=1



*** Test Cases ***
UDM (Unified Data Management) ${tc}
    [Tags]    network    hp    api


    ${command}    Catenate
    ...    ${CMD}
    ...    --filter-cluster-repository=Udm.DataRepository.Repository
    ...    ${extra_options}

    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:         tc  extra_options                                                            expected_result    --
            ...       1   ${EMPTY}                                                                 OK: SBI registration network function status: registered - cluster repository 'Udm.DataRepository.Repository' nodes are ok - All diameter connections are ok | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       2   --unknown-node-status='%\\{status\\} eq "running"'                       UNKNOWN: cluster repository 'Udm.DataRepository.Repository' node 'udm@ab34:123:456:1::2:1' status: running - node 'udm@ab34:123:456:2::2:1' status: running | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       3   --warning-node-status='%\\{status\\} eq "running"'                       WARNING: cluster repository 'Udm.DataRepository.Repository' node 'udm@ab34:123:456:1::2:1' status: running - node 'udm@ab34:123:456:2::2:1' status: running | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       4   --critical-node-status='%\\{status\\} eq "running"'                      CRITICAL: cluster repository 'Udm.DataRepository.Repository' node 'udm@ab34:123:456:1::2:1' status: running - node 'udm@ab34:123:456:2::2:1' status: running | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       5   --unknown-diameter-connection-status='%\\{status\\} eq "up"'             UNKNOWN: diameter stack 'diam_default' origin host 'site1-dra01-local.bjo.fgh123.klm567.domain.local' connection status: up - diameter stack 'diam_default' origin host 'site2-dra01-local.bjo.fgh123.klm567.domain.local' connection status: up | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       6   --warning-diameter-connection-status='%\\{status\\} eq "up"'             WARNING: diameter stack 'diam_default' origin host 'site1-dra01-local.bjo.fgh123.klm567.domain.local' connection status: up - diameter stack 'diam_default' origin host 'site2-dra01-local.bjo.fgh123.klm567.domain.local' connection status: up | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       7   --critical-diameter-connection-status='%\\{status\\} eq "up"'            CRITICAL: diameter stack 'diam_default' origin host 'site1-dra01-local.bjo.fgh123.klm567.domain.local' connection status: up - diameter stack 'diam_default' origin host 'site2-dra01-local.bjo.fgh123.klm567.domain.local' connection status: up | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       8   --unknown-sbi-nf-registration-status='%\\{status\\} eq "registered"'     UNKNOWN: SBI registration network function status: registered | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...       9   --warning-sbi-nf-registration-status='%\\{status\\} eq "registered"'     WARNING: SBI registration network function status: registered | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      10   --critical-sbi-nf-registration-status='%\\{status\\} eq "registered"'    CRITICAL: SBI registration network function status: registered | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      11   --warning-clusters-detected=0                                            WARNING: Number of clusters detected: 1 | 'clusters.detected.count'=1;0:0;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      12   --critical-clusters-detected=0                                           CRITICAL: Number of clusters detected: 1 | 'clusters.detected.count'=1;;0:0;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      13   --warning-cluster-nodes-detected=1                                       WARNING: cluster repository 'Udm.DataRepository.Repository' number of nodes detected: 2 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;0:1;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      14   --critical-cluster-nodes-detected=1                                      CRITICAL: cluster repository 'Udm.DataRepository.Repository' number of nodes detected: 2 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;0:1;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      15   --warning-cluster-nodes-running=1                                        WARNING: cluster repository 'Udm.DataRepository.Repository' number of nodes running: 2 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;0:1;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      16   --critical-cluster-nodes-running=1                                       CRITICAL: cluster repository 'Udm.DataRepository.Repository' number of nodes running: 2 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;0:1;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      17   --warning-cluster-nodes-notrunning=1:                                    WARNING: cluster repository 'Udm.DataRepository.Repository' number of nodes not running: 0 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;1:;;0;2
            ...      18   --critical-cluster-nodes-notrunning=1:                                   CRITICAL: cluster repository 'Udm.DataRepository.Repository' number of nodes not running: 0 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;1:;0;2
            ...      19   --warning-sbi-nf-registration-detected=0                                 WARNING: SBI registration network function detected: 1 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;0:0;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      20   --critical-sbi-nf-registration-detected=0                                CRITICAL: SBI registration network function detected: 1 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;0:0;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      21   --warning-sbi-nf-registration-registered=0                               WARNING: SBI registration network function registered: 1 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;0:0;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      22   --critical-sbi-nf-registration-registered=0                              CRITICAL: SBI registration network function registered: 1 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;0:0;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      23   --warning-sbi-nf-registration-suspended=1:                               WARNING: SBI registration network function suspended: 0 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;1:;;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
            ...      24   --critical-sbi-nf-registration-suspended=1:                              CRITICAL: SBI registration network function suspended: 0 | 'clusters.detected.count'=1;;;0; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;1:;0;1 'Udm.DataRepository.Repository#cluster.nodes.detected.count'=2;;;0; 'Udm.DataRepository.Repository#cluster.nodes.running.count'=2;;;0;2 'Udm.DataRepository.Repository#cluster.nodes.notrunning.count'=0;;;0;2
