*** Settings ***
Documentation       HP Athonet Node Exporter plugin

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}         ${CURDIR}${/}mockoon.json

${BASE_URL}             http://${HOSTNAME}:${APIPORT}
${CMD}                  ${CENTREON_PLUGINS} --plugin=network::hp::athonet::nodeexporter::api::plugin --mode=udr --hostname=${HOSTNAME} --port=${APIPORT} --proto http --api-username=1 --api-password=1



*** Test Cases ***
UDR (Unified Data Repository) ${tc}
    [Tags]    network    hp    api


    ${command}    Catenate
    ...    ${CMD}
    ...    ${extra_options}

    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:         tc  extra_options                                                            expected_result    --
            ...       1   ${EMPTY}                                                                 OK: SBI registration network function status: registered - All clusters are ok | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       2   --unknown-node-status='%\\{status\\} eq "running"'                       UNKNOWN: cluster repository 'Udr.DataLayer.Repository.Provisioning' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running - cluster repository 'Udr.DataLayer.Repository.Session' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running - cluster repository 'xdb recovery configuration' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       3   --warning-node-status='%\\{status\\} eq "running"'                       WARNING: cluster repository 'Udr.DataLayer.Repository.Provisioning' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running - cluster repository 'Udr.DataLayer.Repository.Session' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running - cluster repository 'xdb recovery configuration' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       4   --critical-node-status='%\\{status\\} eq "running"'                      CRITICAL: cluster repository 'Udr.DataLayer.Repository.Provisioning' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running - cluster repository 'Udr.DataLayer.Repository.Session' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running - cluster repository 'xdb recovery configuration' node 'udr@ab34:123:456:1::3:1' status: running - node 'udr@ab34:123:456:2::3:1' status: running | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       5   --unknown-sbi-nf-registration-status='%\\{status\\} eq "registered"'     UNKNOWN: SBI registration network function status: registered | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       6   --warning-sbi-nf-registration-status='%\\{status\\} eq "registered"'     WARNING: SBI registration network function status: registered | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       7   --critical-sbi-nf-registration-status='%\\{status\\} eq "registered"'    CRITICAL: SBI registration network function status: registered | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       8   --warning-clusters-detected=0                                            WARNING: Number of clusters detected: 3 | 'clusters.detected.count'=3;0:0;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...       9   --critical-clusters-detected=0                                           CRITICAL: Number of clusters detected: 3 | 'clusters.detected.count'=3;;0:0;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      10   --warning-cluster-nodes-detected=1                                       WARNING: cluster repository 'Udr.DataLayer.Repository.Provisioning' number of nodes detected: 2 - cluster repository 'Udr.DataLayer.Repository.Session' number of nodes detected: 2 - cluster repository 'xdb recovery configuration' number of nodes detected: 2 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;0:1;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;0:1;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;0:1;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      11   --critical-cluster-nodes-detected=1                                      CRITICAL: cluster repository 'Udr.DataLayer.Repository.Provisioning' number of nodes detected: 2 - cluster repository 'Udr.DataLayer.Repository.Session' number of nodes detected: 2 - cluster repository 'xdb recovery configuration' number of nodes detected: 2 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;0:1;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;0:1;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;0:1;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      12   --warning-cluster-nodes-running=1                                        WARNING: cluster repository 'Udr.DataLayer.Repository.Provisioning' number of nodes running: 2 - cluster repository 'Udr.DataLayer.Repository.Session' number of nodes running: 2 - cluster repository 'xdb recovery configuration' number of nodes running: 2 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;0:1;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;0:1;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;0:1;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      13   --critical-cluster-nodes-running=1                                       CRITICAL: cluster repository 'Udr.DataLayer.Repository.Provisioning' number of nodes running: 2 - cluster repository 'Udr.DataLayer.Repository.Session' number of nodes running: 2 - cluster repository 'xdb recovery configuration' number of nodes running: 2 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;0:1;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;0:1;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;0:1;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      14   --warning-cluster-nodes-notrunning=1:                                    WARNING: cluster repository 'Udr.DataLayer.Repository.Provisioning' number of nodes not running: 0 - cluster repository 'Udr.DataLayer.Repository.Session' number of nodes not running: 0 - cluster repository 'xdb recovery configuration' number of nodes not running: 0 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;1:;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;1:;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;1:;;0;2
            ...      15   --critical-cluster-nodes-notrunning=1:                                   CRITICAL: cluster repository 'Udr.DataLayer.Repository.Provisioning' number of nodes not running: 0 - cluster repository 'Udr.DataLayer.Repository.Session' number of nodes not running: 0 - cluster repository 'xdb recovery configuration' number of nodes not running: 0 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;1:;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;1:;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;1:;0;2
            ...      16   --warning-sbi-nf-registration-detected=0                                 WARNING: SBI registration network function detected: 1 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;0:0;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      17   --critical-sbi-nf-registration-detected=0                                CRITICAL: SBI registration network function detected: 1 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;0:0;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      18   --warning-sbi-nf-registration-registered=0                               WARNING: SBI registration network function registered: 1 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;0:0;;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      19   --critical-sbi-nf-registration-registered=0                              CRITICAL: SBI registration network function registered: 1 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;0:0;0;1 'sbi.nf.registration.suspended.count'=0;;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      20   --warning-sbi-nf-registration-suspended=1:                               WARNING: SBI registration network function suspended: 0 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;1:;;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
            ...      21   --critical-sbi-nf-registration-suspended=1:                              CRITICAL: SBI registration network function suspended: 0 | 'clusters.detected.count'=3;;;0; 'udr.supi.change.last24h.percentage'=0.00%;;;; 'sbi.nf.registration.detected.count'=1;;;0; 'sbi.nf.registration.registered.count'=1;;;0;1 'sbi.nf.registration.suspended.count'=0;;1:;0;1 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Provisioning#cluster.nodes.notrunning.count'=0;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.detected.count'=2;;;0; 'Udr.DataLayer.Repository.Session#cluster.nodes.running.count'=2;;;0;2 'Udr.DataLayer.Repository.Session#cluster.nodes.notrunning.count'=0;;;0;2 'xdb recovery configuration#cluster.nodes.detected.count'=2;;;0; 'xdb recovery configuration#cluster.nodes.running.count'=2;;;0;2 'xdb recovery configuration#cluster.nodes.notrunning.count'=0;;;0;2
