*** Settings ***
Documentation       Check Hardware (Fans, Power supplies, chassis, io cards, blades, fabric extenders).

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Ctn Generic Suite Setup
Test Timeout        120s


*** Variables ***
${CMD}      ${CENTREON_PLUGINS} --plugin=hardware::server::cisco::ucs::snmp::plugin


*** Test Cases ***
equipment ${tc}
    [Tags]    hardware    snmp
    ${command}    Catenate
    ...    ${CMD}
    ...    --mode=equipment
    ...    --hostname=${HOSTNAME}
    ...    --snmp-version=${SNMPVERSION}
    ...    --snmp-port=${SNMPPORT}
    ...    --snmp-community=hardware/server/cisco/ucs/snmp/slim-ucs-equipment
    ...    ${extra_options}
 
    Ctn Verify Command Output    ${command}    ${expected_result}

    Examples:        tc    extra_options                                                                                                expected_result    --
            ...      1     ${EMPTY}                                                                                                     WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing' - memory 'Anonymized-002/mem-22' presence is: 'missing' - memory 'Anonymized-002/mem-12' presence is: 'missing' - memory 'Anonymized-002/mem-7' presence is: 'missing'
            ...      2     --threshold-overload='presence,OK,missing' --threshold-overload='operability,OK,removed'                     OK: All 192 components are ok [192/192 memories]. | 'hardware.memory.count'=192;;;;
            ...      3     --threshold-overload='presence,UNKNOWN,missing' --component='memory'                                         UNKNOWN: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing'
            ...      4     --threshold-overload='operability,WARNING,missing' --component='memory'                                      WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing'
            ...      5     --component='cpu'                                                                                            OK: All 0 components are ok [].
            ...      6     --filter=fan,/sys/chassis-7/fan-module-1-7/fan-1                                                             WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing' - memory 'Anonymized-002/mem-22' presence is: 'missing' - memory 'Anonymized-002/mem-12'
            ...      7     --absent-problem=fan,/sys/chassis-7/fan-module-1-7/fan-1                                                     WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing' - memory 'Anonymized-002/mem-22' presence is: 'missing' - memory 'Anonymized-002/mem-12'
            ...      8     --no-component=UNKNOWN --filter='.*'                                                                         UNKNOWN: No components are checked.
            ...      9     --threshold-overload='presence,CRITICAL,equipped'                                                            CRITICAL: memory 'Anonymized-001/mem-10' presence is: 'equipped' - memory 'Anonymized-001/mem-11' presence is: 'equipped' - memory 'Anonymized-001/mem-13' presence is: 'equipped' - memory 'Anonymized-001/mem-14' presence is: 'equipped' - memory 'Anonymized-001/mem-16' presence is: 'equipped' - memory 'Anonymized-001/mem-17' presence is: 'equipped' - memory 'Anonymized-001/mem-19' presence is: 'equipped' - memory 'Anonymized-001/mem-1' presence is: 'equipped' - memory 'Anonymized-001/mem-2' presence is: 'equipped' - memory 'Anonymized-001/mem-4' presence is: 'equipped' - memory 'Anonymized-001/mem-5' presence is: 'equipped' - memory 'Anonymized-001/mem-7' presence is: 'equipped' - memory 'Anonymized-001/mem-8' presence is: 'equipped' - memory 'Anonymized-001/mem-20' presence is: 'equipped' - memory 'Anonymized-001/mem-22' presence is: 'equipped' - memory 'Anonymized-001/mem-23' presence is: 'equipped'
            ...      10    --filter='.*'                                                                                                OK: All 0 components are ok [].