ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye

ENV DEBIAN_FRONTEND noninteractive

# fix locale
RUN bash -e <<EOF

apt-get update
apt-get install -y locales libcurl4-openssl-dev curl wget
rm -rf /var/lib/apt/lists/*
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
apt-get clean

EOF

ENV LANG en_US.utf8

RUN bash -e <<EOF
# Install Robotframework
apt-get install -y python3 python3-dev python3-pip
pip install robotframework robotframework-examples
# Install snmpsim
pip install snmpsim-lextudio

# Install nodejs
curl -fsSL https://deb.nodesource.com/setup_21.x | bash - &&\
apt-get install -y nodejs
# Install mockoon (needs nodejs)
npm install -g -D @mockoon/cli@7.0.0

# Add Centreon plugins repositories
echo "deb https://packages.centreon.com/apt-plugins-stable/ bullseye main" | tee /etc/apt/sources.list.d/centreon-plugins.list
echo "deb https://packages.centreon.com/apt-plugins-testing/ bullseye main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
echo "deb https://packages.centreon.com/apt-plugins-unstable/ bullseye main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1
apt-get update

# Install perl dependencies
apt-get install -y \
    libpod-parser-perl \
    libnet-curl-perl \
    liburi-encode-perl \
    libwww-perl \
    liblwp-protocol-https-perl \
    libhttp-cookies-perl \
    libio-socket-ssl-perl \
    liburi-perl \
    libhttp-proxypac-perl \
    libcryptx-perl \
    libjson-xs-perl \
    libjson-path-perl \
    libcrypt-argon2-perl \
    libkeepass-reader-perl \
    libdatetime-perl

apt-get update
apt-get clean

EOF
