ARG REGISTRY_URL=docker.io

FROM ${REGISTRY_URL}/debian:trixie

ENV DEBIAN_FRONTEND=noninteractive

ARG NODE_VERSION=24
ARG PNPM_VERSION=10.24.0

COPY .github/docker/testing/package.json .github/docker/testing/pnpm-lock.yaml /usr/local/src/

# fix locale
RUN bash -e <<EOF

useradd snmp
mkdir -p /var/lib/snmp/cert_indexes/
chown snmp:snmp -R /var/lib/snmp/cert_indexes/
mkdir -p /tmp/cache/

apt-get update
apt-get install -y locales libcurl4-openssl-dev curl wget zstd jq lsb-release ca-certificates gnupg2 procps
rm -rf /var/lib/apt/lists/*
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
apt-get clean

EOF

ENV LANG=en_US.utf8

RUN bash -e <<EOF

# Avoid apt to clean packages cache directory
rm -f /etc/apt/apt.conf.d/docker-clean

apt-get update
# Install requirements for python virtual envs
apt-get install -y python3-venv
python3 -m venv .venv
. .venv/bin/activate
# Install Robotframework
apt-get install -y python3 python3-dev python3-pip
pip3 install robotframework robotframework-examples
# Install snmpsim
pip3 install snmpsim

curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
apt-get install -y nodejs
curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=${PNPM_VERSION} bash -
source ~/.bashrc
cd /usr/local/src
pnpm install --frozen-lockfile
echo 'export PATH="~/node_modules/.bin/:$PATH"' >> ~/.bashrc

# Add Centreon plugins repositories
echo "deb https://packages.centreon.com/apt-standard trixie-25.10-stable main" | tee /etc/apt/sources.list.d/centreon.list
echo "deb https://packages.centreon.com/apt-plugins-stable/ trixie main" | tee /etc/apt/sources.list.d/centreon-plugins.list
echo "deb https://packages.centreon.com/apt-plugins-testing/ trixie main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
echo "deb https://packages.centreon.com/apt-plugins-unstable/ trixie main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1

# Update
apt-get update

apt-get install -y centreon-clib centreon-connector-perl centreon-plugins

rm -f /etc/apt/sources.list.d/centreon.list

mkdir -p /var/lib/centreon/centplugins/
chmod 777 /var/lib/centreon/centplugins/

apt-get clean

EOF

ENV PATH="/usr/local/src/node_modules/.bin/:$PATH"
