ARG REGISTRY_URL=docker.io

FROM ${REGISTRY_URL}/ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

ARG NODE_VERSION=24
ARG PNPM_VERSION=10.24.0

# fix locale
RUN bash -e <<EOF

useradd snmp
mkdir -p /var/lib/snmp/cert_indexes/
chown snmp:snmp -R /var/lib/snmp/cert_indexes/
mkdir -p /tmp/cache/

apt-get update
apt-get install -y locales libcurl4-openssl-dev curl wget zstd jq lsb-release ca-certificates software-properties-common gnupg2 procps
rm -rf /var/lib/apt/lists/*
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
apt-get clean

EOF

ENV LANG=en_US.utf8

RUN bash -e <<EOF

# Avoid apt to clean packages cache directory
rm -f /etc/apt/apt.conf.d/docker-clean

apt-get update
# Install Robotframework
apt-get install -y python3 python3-dev python3-pip
rm -rf /usr/lib/python3.11/EXTERNALLY-MANAGED
pip3 install robotframework robotframework-examples
# Install snmpsim
pip3 install snmpsim

curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - &&\
apt-get install -y nodejs
curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=${PNPM_VERSION} ENV="\$HOME/.bashrc" SHELL="\$(which bash)" bash -
pnpm install --frozen-lockfile
export PATH="~/node_modules/.bin/:$PATH"

# Add Centreon plugins repositories
echo "deb https://packages.centreon.com/ubuntu-standard-24.04-stable/ jammy main" | tee -a /etc/apt/sources.list.d/centreon-stable.list
echo "deb https://packages.centreon.com/ubuntu-plugins-stable/ jammy main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
echo "deb https://packages.centreon.com/ubuntu-plugins-testing/ jammy main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
echo "deb https://packages.centreon.com/ubuntu-plugins-unstable/ jammy main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
echo "deb https://packages.centreon.com/ubuntu-connectors-stable/ jammy main" | tee /etc/apt/sources.list.d/centreon-connectors.list
wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1
apt-get update

apt-get install -y centreon-clib centreon-connector-perl

rm -f /etc/apt/sources.list.d/centreon.list

mkdir -p /var/lib/centreon/centplugins/
chmod 777 /var/lib/centreon/centplugins/

apt-get clean

EOF