*** Settings ***
Documentation       Quanta

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}     ${CURDIR}${/}quanta.mockoon.json
${HOSTNAME}         127.0.0.1
${APIPORT}          3000
${CMD}              ${CENTREON_PLUGINS}
...                 --plugin=apps::monitoring::quanta::restapi::plugin
...                 --hostname=${HOSTNAME}
...                 --api-token=PaSsWoRd
...                 --site-id=10
...                 --proto=http
...                 --port=${APIPORT}


*** Test Cases ***
Rum ${tc}
    [Tags]    quanta    api
    ${command}    Catenate
    ...    ${CMD}
    ...    --mode=rum
    ...    ${extra_options}

    Ctn Run Command And Check Result As Regexp    ${command}    ${expected_regexp}

    Examples:        tc       extraoptions                                                expected_regexp    --
            ...      1        ${EMPTY}                                                    OK: all pages: sessions: 34, page views: 62, bounce rate: 43%, ttfb: 1617.714ms, onload time: 5494.82ms, interaction to next paint: 46.70ms, speed index: 2536.67ms \\\\| 'pages#sessions.count'=34;;;0; 'pages#pageviews.count'=62;;;0; 'pages#bounce.rate.percentage'=43%;;;0;100 'pages#ttfb.milliseconds'=1617.71ms;;;0; 'pages#onload.time.milliseconds'=5494.82ms;;;0; 'pages#nextpaint.interaction.time.milliseconds'=46.70ms;;;0; 'pages#speedindex.time.milliseconds'=2536.67ms;;;0;
            ...      2        --perspective=all                                           OK: all pages: sessions: 34, page views: 62, bounce rate: 43%, ttfb: 1617.714ms, onload time: 5494.82ms, interaction to next paint: 46.70ms, speed index: 2536.67ms \\\\| 'pages#sessions.count'=34;;;0; 'pages#pageviews.count'=62;;;0; 'pages#bounce.rate.percentage'=43%;;;0;100 'pages#ttfb.milliseconds'=1617.71ms;;;0; 'pages#onload.time.milliseconds'=5494.82ms;;;0; 'pages#nextpaint.interaction.time.milliseconds'=46.70ms;;;0; 'pages#speedindex.time.milliseconds'=2536.67ms;;;0;
            ...      3        --perspective=all --critical-page-views=:10                 ^CRITICAL: all pages.+$
            ...      4        --perspective=all --warning-page-views=:10                  ^WARNING: all pages.+$
            ...      5        --perspective=url                                           OK: All RUM counters are OK \\\\| '/#pageviews.count'=6;;;0; '/#ttfb.milliseconds'=2308.00ms;;;0; '/#onload.time.milliseconds'=5970.00ms;;;0; '/#nextpaint.interaction.time.milliseconds'=58.67ms;;;0; '/#speedindex.time.milliseconds'=2710.00ms;;;0; '/ariege/departement/#pageviews.count'=2;;;0; '/ariege/departement/#ttfb.milliseconds'=1380.00ms;;;0; '/ariege/departement/#onload.time.milliseconds'=2198.00ms;;;0; '/ariege/departement/#nextpaint.interaction.time.milliseconds'=50.67ms;;;0; '/ariege/departement/#speedindex.time.milliseconds'=1521.00ms;;;0; '/fr/#pageviews.count'=8;;;0; '/fr/#ttfb.milliseconds'=1741.67ms;;;0; '/fr/#onload.time.milliseconds'=5020.38ms;;;0; '/fr/#nextpaint.interaction.time.milliseconds'=74.00ms;;;0; '/fr/#speedindex.time.milliseconds'=3838.71ms;;;0; '/fr/ariege/#pageviews.count'=1;;;0; '/fr/ariege/#ttfb.milliseconds'=1491.00ms;;;0; '/fr/ariege/#onload.time.milliseconds'=2713.00ms;;;0; '/fr/ariege/#speedindex.time.milliseconds'=1697.00ms;;;0; '/fr/contrazy/#pageviews.count'=2;;;0; '/fr/contrazy/#ttfb.milliseconds'=3469.50ms;;;0; '/fr/contrazy/#onload.time.milliseconds'=9203.50ms;;;0; '/fr/contrazy/#speedindex.time.milliseconds'=4092.50ms;;;0; '/fr/merigon/#pageviews.count'=2;;;0; '/fr/merigon/#ttfb.milliseconds'=1174.50ms;;;0; '/fr/merigon/#onload.time.milliseconds'=5819.50ms;;;0; '/fr/merigon/#nextpaint.interaction.time.milliseconds'=29.33ms;;;0; '/fr/merigon/#speedindex.time.milliseconds'=6318.00ms;;;0; '/fr/stgirons/#pageviews.count'=3;;;0; '/fr/stgirons/#ttfb.milliseconds'=543.50ms;;;0; '/fr/stgirons/#onload.time.milliseconds'=2847.67ms;;;0; '/fr/stgirons/#nextpaint.interaction.time.milliseconds'=112.00ms;;;0; '/fr/stgirons/#speedindex.time.milliseconds'=1062.50ms;;;0; '/guzet/#pageviews.count'=3;;;0; '/guzet/#ttfb.milliseconds'=1264.00ms;;;0; '/guzet/#onload.time.milliseconds'=1916.00ms;;;0; '/guzet/#nextpaint.interaction.time.milliseconds'=64.00ms;;;0; '/guzet/#speedindex.time.milliseconds'=1445.00ms;;;0; '/massat/#pageviews.count'=1;;;0; '/massat/#ttfb.milliseconds'=2484.00ms;;;0; '/massat/#onload.time.milliseconds'=13258.00ms;;;0; '/montardit/#pageviews.count'=3;;;0; '/montardit/#ttfb.milliseconds'=1171.33ms;;;0; '/montardit/#onload.time.milliseconds'=4867.33ms;;;0; '/montardit/#nextpaint.interaction.time.milliseconds'=52.00ms;;;0; '/montardit/#speedindex.time.milliseconds'=1357.67ms;;;0;
            ...      6        --perspective=url --critical-interaction-next-paint=:10     ^CRITICAL: url.+$
            ...      7        --perspective=url --warning-interaction-next-paint=:10      ^WARNING: url.+$
            ...      8        --perspective=browser                                       OK: All RUM counters are OK \\\\| 'Chrome#sessions.count'=16;;;0; 'Chrome#pageviews.count'=22;;;0; 'Chrome#bounce.rate.percentage'=20%;;;0;100 'Chrome#ttfb.milliseconds'=1554.31ms;;;0; 'Chrome#onload.time.milliseconds'=5495.91ms;;;0; 'Chrome#nextpaint.interaction.time.milliseconds'=80.38ms;;;0; 'Chrome#speedindex.time.milliseconds'=2706.62ms;;;0; 'Chrome Mobile#sessions.count'=1;;;0; 'Chrome Mobile#pageviews.count'=1;;;0; 'Chrome Mobile#bounce.rate.percentage'=1%;;;0;100 'Chrome Mobile#ttfb.milliseconds'=5021.00ms;;;0; 'Chrome Mobile#onload.time.milliseconds'=7429.00ms;;;0; 'Chrome Mobile#speedindex.time.milliseconds'=5260.00ms;;;0; 'Edge#sessions.count'=8;;;0; 'Edge#pageviews.count'=18;;;0; 'Edge#bounce.rate.percentage'=12%;;;0;100 'Edge#ttfb.milliseconds'=1330.06ms;;;0; 'Edge#onload.time.milliseconds'=4063.17ms;;;0; 'Edge#nextpaint.interaction.time.milliseconds'=41.87ms;;;0; 'Edge#speedindex.time.milliseconds'=1592.81ms;;;0; 'Firefox#sessions.count'=3;;;0; 'Firefox#pageviews.count'=15;;;0; 'Firefox#bounce.rate.percentage'=3%;;;0;100 'Firefox#ttfb.milliseconds'=1233.40ms;;;0; 'Firefox#onload.time.milliseconds'=6396.27ms;;;0; 'Firefox#nextpaint.interaction.time.milliseconds'=20.73ms;;;0; 'Firefox#speedindex.time.milliseconds'=2624.56ms;;;0; 'HeadlessChrome#sessions.count'=1;;;0; 'HeadlessChrome#pageviews.count'=1;;;0; 'HeadlessChrome#bounce.rate.percentage'=1%;;;0;100 'HeadlessChrome#ttfb.milliseconds'=6226.00ms;;;0; 'HeadlessChrome#onload.time.milliseconds'=8563.00ms;;;0; 'HeadlessChrome#speedindex.time.milliseconds'=6764.00ms;;;0; 'Mobile Safari#sessions.count'=1;;;0; 'Mobile Safari#pageviews.count'=1;;;0; 'Mobile Safari#bounce.rate.percentage'=1%;;;0;100 'Mobile Safari#ttfb.milliseconds'=1183.00ms;;;0; 'Mobile Safari#onload.time.milliseconds'=2572.00ms;;;0; 'Mobile Safari#speedindex.time.milliseconds'=1446.00ms;;;0; 'Opera Mobile#sessions.count'=1;;;0; 'Opera Mobile#pageviews.count'=1;;;0; 'Opera Mobile#bounce.rate.percentage'=1%;;;0;100 'Opera Mobile#ttfb.milliseconds'=3092.00ms;;;0; 'Opera Mobile#onload.time.milliseconds'=11991.00ms;;;0; 'Opera Mobile#speedindex.time.milliseconds'=6095.00ms;;;0;
            ...      9        --perspective=browser --critical-ttfb=:10                   ^CRITICAL: browser.+$
            ...      10       --perspective=browser --warning-ttfb=:10                    ^WARNING: browser.+$
            ...      11       --perspective=country                                       OK: country country: sessions: 34, page views: 62, bounce rate: 43%, ttfb: 1617.714ms, onload time: 5494.82ms, interaction to next paint: 46.70ms, speed index: 2536.67ms \\\\| 'country#sessions.count'=34;;;0; 'country#pageviews.count'=62;;;0; 'country#bounce.rate.percentage'=43%;;;0;100 'country#ttfb.milliseconds'=1617.71ms;;;0; 'country#onload.time.milliseconds'=5494.82ms;;;0; 'country#nextpaint.interaction.time.milliseconds'=46.70ms;;;0; 'country#speedindex.time.milliseconds'=2536.67ms;;;0;
            ...      12       --perspective=country --critical-bounce-rate=:10            ^CRITICAL: country.+$
            ...      13       --perspective=country --warning-bounce-rate=:10             ^WARNING: country.+$
            ...      14       --perspective=city                                          OK: All RUM counters are OK \\\\| 'EE#pageviews.count'=7;;;0; 'EE#ttfb.milliseconds'=1128.71ms;;;0; 'EE#onload.time.milliseconds'=1716.00ms;;;0; 'EE#nextpaint.interaction.time.milliseconds'=32.00ms;;;0; 'EE#speedindex.time.milliseconds'=1300.86ms;;;0; 'FR#sessions.count'=1;;;0; 'FR#pageviews.count'=1;;;0; 'FR#bounce.rate.percentage'=1%;;;0;100 'FR#ttfb.milliseconds'=1183.00ms;;;0; 'FR#onload.time.milliseconds'=2572.00ms;;;0; 'FR#speedindex.time.milliseconds'=1446.00ms;;;0; 'IN#sessions.count'=1;;;0; 'IN#pageviews.count'=3;;;0; 'IN#bounce.rate.percentage'=2%;;;0;100 'IN#ttfb.milliseconds'=1660.00ms;;;0; 'IN#onload.time.milliseconds'=3668.67ms;;;0; 'IN#nextpaint.interaction.time.milliseconds'=36.00ms;;;0; 'IN#speedindex.time.milliseconds'=2294.67ms;;;0; 'MA#sessions.count'=1;;;0; 'MA#pageviews.count'=1;;;0; 'MA#bounce.rate.percentage'=1%;;;0;100 'MA#ttfb.milliseconds'=3092.00ms;;;0; 'MA#onload.time.milliseconds'=11991.00ms;;;0; 'MA#speedindex.time.milliseconds'=6095.00ms;;;0; 'NO#sessions.count'=1;;;0; 'NO#pageviews.count'=3;;;0; 'NO#bounce.rate.percentage'=2%;;;0;100 'NO#ttfb.milliseconds'=1171.33ms;;;0; 'NO#onload.time.milliseconds'=4867.33ms;;;0; 'NO#nextpaint.interaction.time.milliseconds'=52.00ms;;;0; 'NO#speedindex.time.milliseconds'=1357.67ms;;;0; 'SN#sessions.count'=1;;;0; 'SN#pageviews.count'=1;;;0; 'SN#bounce.rate.percentage'=2%;;;0;100 'SN#ttfb.milliseconds'=2693.00ms;;;0; 'SN#onload.time.milliseconds'=23566.00ms;;;0; 'SN#nextpaint.interaction.time.milliseconds'=64.00ms;;;0; 'SN#speedindex.time.milliseconds'=17320.00ms;;;0; 'US#sessions.count'=4;;;0; 'US#pageviews.count'=6;;;0; 'US#bounce.rate.percentage'=5%;;;0;100 'US#ttfb.milliseconds'=2587.75ms;;;0; 'US#onload.time.milliseconds'=4897.67ms;;;0; 'US#speedindex.time.milliseconds'=3131.00ms;;;0;
            ...      15       --perspective=city --critical-speed-index=:10               ^CRITICAL: city.+$
            ...      16       --perspective=city --warning-speed-index=:10                ^WARNING: city.+$
            ...      17       --perspective=os                                            OK: All RUM counters are OK \\\\| 'Android#sessions.count'=1;;;0; 'Android#pageviews.count'=1;;;0; 'Android#bounce.rate.percentage'=1%;;;0;100 'Android#ttfb.milliseconds'=3092.00ms;;;0; 'Android#onload.time.milliseconds'=11991.00ms;;;0; 'Android#speedindex.time.milliseconds'=6095.00ms;;;0; 'Linux#sessions.count'=1;;;0; 'Linux#pageviews.count'=1;;;0; 'Linux#bounce.rate.percentage'=1%;;;0;100 'Linux#ttfb.milliseconds'=6226.00ms;;;0; 'Linux#onload.time.milliseconds'=8563.00ms;;;0; 'Linux#speedindex.time.milliseconds'=6764.00ms;;;0; 'Mac OS X#sessions.count'=1;;;0; 'Mac OS X#pageviews.count'=3;;;0; 'Mac OS X#bounce.rate.percentage'=2%;;;0;100 'Mac OS X#ttfb.milliseconds'=1264.00ms;;;0; 'Mac OS X#onload.time.milliseconds'=1916.00ms;;;0; 'Mac OS X#speedindex.time.milliseconds'=1445.00ms;;;0; 'Windows#sessions.count'=21;;;0; 'Windows#pageviews.count'=49;;;0; 'Windows#bounce.rate.percentage'=27%;;;0;100 'Windows#ttfb.milliseconds'=1371.89ms;;;0; 'Windows#onload.time.milliseconds'=5404.73ms;;;0; 'Windows#nextpaint.interaction.time.milliseconds'=45.41ms;;;0; 'Windows#speedindex.time.milliseconds'=2345.58ms;;;0; 'iOS#sessions.count'=1;;;0; 'iOS#pageviews.count'=1;;;0; 'iOS#bounce.rate.percentage'=1%;;;0;100 'iOS#ttfb.milliseconds'=1183.00ms;;;0; 'iOS#onload.time.milliseconds'=2572.00ms;;;0; 'iOS#speedindex.time.milliseconds'=1446.00ms;;;0;
            ...      18       --perspective=os --critical-onload=:10                      ^CRITICAL: os.+$
            ...      19       --perspective=os --warning-onload=:10                       ^WARNING: os.+$
            ...      20       --perspective=os --critical-sessions=:10                    ^CRITICAL: os.+$
            ...      21       --perspective=os --warning-sessions=:10                     ^WARNING: os.+$
