*** Settings ***
Documentation       Meraki VPN Tunnels

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}     ${CURDIR}${/}meraki.mockoon.json

${CMD}              ${CENTREON_PLUGINS} --plugin=network::cisco::meraki::cloudcontroller::restapi::plugin
...                 --api-token=3858c7977a394be5c2414178df9ebd5bb6d7dbba


*** Test Cases ***
Create cache from API
    [Tags]    meraki    api    vpn    network cache
    ${output}    Run
    ...    ${CMD} 
    ...    --mode=cache --proto=http --port=${APIPORT} --hostname=${HOSTNAME}

    ${output}    Strip String    ${output}
    Should Be Equal As Strings
    ...    ${output}
    ...    OK: Cache files created successfully
    ...    Wrong output result:\n\n ${output}\nInstead of:\n OK: Cache files created successfully\n\n
    # Mockoon is not needed any longer since the data are cached
    Stop Mockoon

Check if ${test_desc} works ${tc}
    [Tags]    meraki    api    vpn    network
    ${command}    Catenate
    ...    ${CMD}
    ...    --mode=vpn-tunnels --http-backend=curl
    ...    ${extra_options}
    
    Ctn Verify Command Output    ${command}    ${expected_result}

    Examples:    tc    test_desc        extra_options                                                                                                expected_result   --
        ...      1     all links        .*                                                                                                           OK: vpn tunnel 'C3PO-R2P2-BB88' status: dormant [mode: spoke] | 'vpn.tunnels.online.count'=0;;;0;1 'vpn.tunnels.offline.count'=0;;;0;1 'vpn.tunnels.dormant.count'=1;;1:;0;1
        ...      2     empty filter     ${EMPTY}                                                                                                     CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki]
        ...      3     absurd filter    toto                                                                                                         CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T4_LOM1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T4_POS2' [type: meraki]
        ...      4     ${EMPTY}         --filter-network-name=''                                                                                     CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T4_LOM1' [type: meraki]
        ...      5     ${EMPTY}         --filter-organization-id=''                                                                                  CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T4_LOM1' [type: meraki]
        ...      6     ${EMPTY}         --filter-organization-name=''                                                                                CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T4_LOM1' [type: meraki]
        ...      7     ${EMPTY}         --filter-device-serial='Q2AZ-B78W-TDAW'                                                                      CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable | 'vpn.tunnels.unreachable.count'=1;;;0;41
        ...      8     ${EMPTY}         --filter-vpn-type=''                                                                                         CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T4_LOM1' [type: meraki]
        ...      9     ${EMPTY}         --filter-vpn-name='LTR_AT_SALZBURG_BACKUP'                                                                   CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2DZ-9WFE-6FUH' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2DZ-W48Z-TDVJ' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2SW-8Y8M-ZLG5' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2WN-KWMQ-2K64' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable | 'vpn.tunnels.unreachable.count'=6;;;0;6
        ...      10    ${EMPTY}         --unknown-device-status='\\\%{deviceStatus} =~ /offline/i'                                                   CRITICAL:
        ...      11    ${EMPTY}         --warning-device-status='\\\%{deviceMode} =~ /offline/i'                                                     CRITICAL:
        ...      12    ${EMPTY}         --critical-device-status='\\\%{deviceSerial} =~ /offline/i'                                                  CRITICAL: device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki]       
        ...      13    ${EMPTY}         --unknown-vpn-status='\\\%{deviceStatus} eq unreachable'                                                     CRITICAL:                
        ...      14    ${EMPTY}         --warning-vpn-status='\\\%{vpnStatus} eq unreachable'                                                        CRITICAL:
        ...      15    ${EMPTY}         --critical-vpn-status='\\\%{deviceSerial} ne unreachable'                                                    OK: All devices are ok | 'vpn.tunnels.unreachable.count'=279;;;0;3462         
        ...      16    ${EMPTY}         --warning-total-unreachable=100 --critical-total-unreachable=12                                              CRITICAL: Number of VPNS unreachable: 277 - device 'Q2AZ-B78W-TDAW' vpn tunnel 'LTR_AT_SALZBURG_BACKUP' [type: meraki] status: unreachable - device 'Q2AZ-K972-8592' vpn tunnel 'HUBONE_CDG_DOME_BUR_FORMATION' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2BD_PPODIUM_CHANEL' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2C_FNC1' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E010' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2EK_E023' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2F2_LFM6_PODIUM' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S3_S309' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S408' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_CDG_T2S4_S410' [type: meraki] status: unreachable - vpn tunnel 'HUBONE_ORY_T2_OW05' [type: meraki]