[package]
name = "conn"
version = "1.1.0"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "generic-snmp"
path = "src/main.rs"

[dependencies]
regex = "1.11.1"
rasn = "0.24.0"
rasn-snmp = "0.24.0"
rasn-smi = "0.24.0"
log = "0.4.25"
clap = { version = "4.5.29", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
