#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Message/Event.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Message::Event;

%ResponseParameters =
  (
   3024                                  => "ApplName",
   3026                                  => "AuxErrorDataStr1",
   3027                                  => "AuxErrorDataStr2",
   3028                                  => "AuxErrorDataStr3",
   3029                                  => "BridgeName",
   3023                                  => "ObjectQMgrName",
   3025                                  => "UserIdentifier",
   3501                                  => "ChannelName",
   3506                                  => "ConnectionName",
   3533                                  => "Format",
   3546                                  => "SSLHandshakeStage",
   3545                                  => "SSLPeerName",
   3505                                  => "XmitQName",
   2002                                  => "BaseQName",
   2012                                  => "ProcessName",
   2015                                  => "QMgrName",
   2016                                  => "QName",
   2024                                  => "XmitQName",
   1070                                  => "AuxErrorDataInt1",
   1071                                  => "AuxErrorDataInt2",
   1073                                  => "BridgeType",
   1021                                  => "Command",
   1072                                  => "ConversionReasonCode",
   1013                                  => "ErrorIdentifier",
   1022                                  => "Options",
   1020                                  => "ReasonQualifier",
   1511                                  => "ChannelType",
   1533                                  => "SSLReturnCode",
   1                                     => "ApplType",
   36                                    => "HighQDepth",
   38                                    => "MsgDeqCount",
   37                                    => "MsgEnqCount",
   20                                    => "QType",
   35                                    => "TimeSinceReset",
  );

1;
