[package]
name = "centreon-plugin-rust-snmp"
version = "1.0.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.23.1"

[dependencies]
env_logger = "0.11.11"
lalrpop-util = { version = "0.23.1", features = ["lexer"] }
lexopt = "0.3.2"
log = "0.4.33"
rasn = "0.28.13"
rasn-smi = "0.28.13"
rasn-snmp = "0.28.13"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
snafu = "0.9.2"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
