[package]
name = "centreon-plugin-rust-snmp"
version = "1.0.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.23.1"

[dependencies]
lalrpop-util = { version = "0.23.1", features = ["lexer"] }
lexopt = "0.3.2"
rasn = "0.28.13"
rasn-smi = "0.28.13"
rasn-snmp = "0.28.13"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
snafu = "0.9.2"
hmac = "0.13.0"
md-5 = "0.11.0"
sha1 = "0.11.0"
sha2 = "0.11.0"
aes = "0.9.2"
des = "0.9.0"
cbc = "0.2.1"
cfb-mode = "0.9.1"
cipher = "0.5.2"
tracing = "0.1"
tracing-chrome = "0.7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
