ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye

ENV DEBIAN_FRONTEND noninteractive

# fix locale
RUN bash -e <<EOF

apt-get update
apt-get install -y locales
rm -rf /var/lib/apt/lists/*
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
apt-get clean

EOF

ENV LANG en_US.utf8

RUN bash -e <<EOF

apt-get update

apt-get install -y \
  dh-make \
  aptitude \
  ca-certificates \
  libssh-dev \
  lintian \
  pbuilder \
  quilt \
  git-buildpackage \
  debmake \
  devscripts \
  fakeroot \
  curl \
  gcc \
  git \
  python3 \
  libjson-perl \
  libapp-fatpacker-perl \
  libfile-copy-recursive-perl \
  jq \
  zstd

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
apt-get update
apt-get install -y nfpm

apt-get clean

EOF
