FROM docker-proxy.centreon.com/debian:bullseye

# fix locale
RUN <<EOF

apt-get update
apt-get install -y locales
rm -rf /var/lib/apt/lists/*
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
apt-get clean

EOF

ENV LANG en_US.utf8

RUN <<EOF

apt-get update
apt-get install -y \
  dh-make \
  aptitude \
  lintian \
  pbuilder \
  quilt \
  git-buildpackage \
  debmake \
  devscripts \
  fakeroot \
  curl \
  git \
  python3 \
  libjson-perl \
  libapp-fatpacker-perl \
  libfile-copy-recursive-perl \
  jq
apt-get clean

EOF
