name: run-in-docker
description: Run step in docker container
inputs:
  script_name:
    description: "script_name"
    required: true
  image_name:
    description: "image_name"
    required: true
  image_version:
    description: "image_version"
    required: true
  centreon_pat:
    description: "Secret"
    required: false
  registry_url:
    description: Docker registry url
    required: true
  registry_username:
    description: Docker registry username
    required: true
  registry_password:
    description: Docker registry password
    required: true
  params:
    description: "params for script"
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to Registry (via runner)
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ${{ inputs.registry_url }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - run: docker run -i -e TOKEN=${{ inputs.centreon_pat }} --entrypoint /src/.github/scripts/${{ inputs.script_name }}.sh -v "$PWD:/src" ${{ inputs.registry_url }}/${{ inputs.image_name }}:${{ inputs.image_version }} ${{ inputs.params }}
      shell: bash
