*** Settings ***
Documentation       Check Cisco Wireless Lan Controller in SNMP.

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}resources/import.resource

Test Timeout        120s


*** Variables ***
${CMD}      ${CENTREON_PLUGINS} --plugin=network::cisco::wlc::snmp::plugin


*** Test Cases ***
ap-status ${tc}
    [Tags]    network    wlc    snmp
    ${command}    Catenate
    ...    ${CMD}
    ...    --mode=ap-status
    ...    --hostname=${HOSTNAME}
    ...    --snmp-port=${SNMPPORT}
    ...    --snmp-community=network/cisco/wlc/snmp/slim_cisco_wlc
    ...    ${extra_options}

    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:        tc    extra_options                                                                                                               expected_result    --
            ...      1     --verbose                                                                                                                   OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0; Model: Anonymized 042 checking access point 'Anonymized 007' status: associated checking access point 'Anonymized 015' status: associated checking access point 'Anonymized 035' status: associated checking access point 'Anonymized 072' status: associated checking access point 'Anonymized 089' status: associated checking access point 'Anonymized 108' status: associated checking access point 'Anonymized 122' status: associated checking access point 'Anonymized 181' status: associated checking access point 'Anonymized 201' status: associated checking access point 'Anonymized 249' status: associated
            ...      2     --filter-counters                                                                                                           OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      3     --filter-name                                                                                                               OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      4     --filter-group                                                                                                              OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      5     --add-radio-interfaces                                                                                                      OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0; 'radio_interface_channels_utilization_Anonymized 007'=2%;;;0;100 'radio_interface_channels_utilization_Anonymized 015'=4%;;;0;100 'radio_interface_channels_utilization_Anonymized 035'=5%;;;0;100 'radio_interface_channels_utilization_Anonymized 072'=2%;;;0;100 'radio_interface_channels_utilization_Anonymized 089'=2%;;;0;100 'radio_interface_channels_utilization_Anonymized 108_0'=7%;;;0;100 'radio_interface_channels_utilization_Anonymized 108_1'=0%;;;0;100 'radio_interface_channels_utilization_Anonymized 122'=3%;;;0;100 'radio_interface_channels_utilization_Anonymized 181'=3%;;;0;100 'radio_interface_channels_utilization_Anonymized 201'=1%;;;0;100 'radio_interface_channels_utilization_Anonymized 249_0'=29%;;;0;100 'radio_interface_channels_utilization_Anonymized 249_1'=0%;;;0;100                                                
            ...      6     --warning-status='\\\%{admstatus}'                                                                                          WARNING: access point 'Anonymized 007' status: associated - access point 'Anonymized 015' status: associated - access point 'Anonymized 035' status: associated - access point 'Anonymized 072' status: associated - access point 'Anonymized 089' status: associated - access point 'Anonymized 108' status: associated - access point 'Anonymized 122' status: associated - access point 'Anonymized 181' status: associated - access point 'Anonymized 201' status: associated - access point 'Anonymized 249' status: associated | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      7     --warning-status='\\\%{opstatus}'                                                                                           WARNING: access point 'Anonymized 007' status: associated - access point 'Anonymized 015' status: associated - access point 'Anonymized 035' status: associated - access point 'Anonymized 072' status: associated - access point 'Anonymized 089' status: associated - access point 'Anonymized 108' status: associated - access point 'Anonymized 122' status: associated - access point 'Anonymized 181' status: associated - access point 'Anonymized 201' status: associated - access point 'Anonymized 249' status: associated | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      8     --warning-status='\\\%{display}'                                                                                            WARNING: access point 'Anonymized 007' status: associated - access point 'Anonymized 015' status: associated - access point 'Anonymized 035' status: associated - access point 'Anonymized 072' status: associated - access point 'Anonymized 089' status: associated - access point 'Anonymized 108' status: associated - access point 'Anonymized 122' status: associated - access point 'Anonymized 181' status: associated - access point 'Anonymized 201' status: associated - access point 'Anonymized 249' status: associated | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      9     --critical-status='\\\%{admstatus} eq "enable" and \\\%{opstatus} !~ /associated|downloading/'                              OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      10    --critical-status='\\\%{admstatus} eq "enable" and \\\%{opstatus} !~ /associated|downloading/'                              OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      11    --critical-status='\\\%{admstatus} eq "enable" and \\\%{opstatus} !~ /associated|downloading/'                              OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      12    --warning-radio-status='\\\%{admstatus}'                                                                                    OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;        
            ...      13    --critical-radio-status='\\\%{admstatus} eq "enable" and \\\%{opstatus} eq "down"'                                          OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;                        
            ...      14    --warning-total --critical-total                                                                                            OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      15    --warning-total-associated --critical-total-associated                                                                      OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      16    --warning-total-disassociating --critical-total-disassociating                                                              OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      17    --warning-total-downloading --critical-total-downloading                                                                    OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      18    --warning-total-enabled --critical-total-enabled                                                                            OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      19    --warning-total-disabled --critical-total-disabled                                                                          OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;
            ...      20    --warning-radio-interface-channels-utilization --critical-radio-interface-channels-utilization                              OK: Access points total: 10, associated: 10, disassociating: 0, enabled: 10, disabled: 0 - All access points are ok | 'total'=10;;;0; 'total_associated'=10;;;0; 'total_disassociating'=0;;;0; 'total_downloading'=0;;;0; 'total_enabled'=10;;;0; 'total_disabled'=0;;;0;