#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/RequestValues.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%RequestValues =
  (
   #
   # QueueManager
   #
   QueueManager =>
   {
    All				=> 1009,
    ClusterAttrs		=> 1125,
    DistributedQueueingAttrs	=> 1124,
    EventAttrs			=> 1123,
    PubSubAttrs			=> 1291,
    SystemAttrs			=> 1122,

    AccountingConnOverride	=> 136,
    AccountingInterval		=> 135,
    ActivityRecording		=> 138,
    ActivityConnOverride	=> 239,
    ActivityTrace		=> 240,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    AdoptNewMCACheck		=> 102,
    AdoptNewMCAType		=> 103,
    AlterationTime		=> 2028,
    AuthorityEvent		=> 47,
    BridgeEvent			=> 74,
    CFConlos			=> 245,
    ChannelAutoDef		=> 55,
    ChannelAutoDefEvent		=> 56,
    ChannelAutoDefExit		=> 2026,
    ChannelEvent		=> 73,
    ChannelInitiatorControl	=> 119,
    ChannelMonitoring		=> 122,
    ChannelStatistics		=> 129,
    ChinitAdapters		=> 101,
    ChinitDispatchers		=> 105,
    ChinitServiceParm		=> 2076,
    ChinitTraceAutoStart	=> 117,
    ChinitTraceTableSize	=> 118,
    ChlAuthRecords		=> 248,
    ClusterSenderMonitoringDefault => 124,
    ClusterSenderStatistics	=> 130,
    ClusterWorkLoadData		=> 2034,
    ClusterWorkLoadExit		=> 2033,
    ClusterWorkLoadLength	=> 58,
    CLWLMRUChannels		=> 97,
    CLWLUseQ			=> 98,
    CodedCharSetId		=> 2,
    CommandEvent		=> 99,
    CommandInputQName		=> 2003,
    CommandLevel		=> 31,
    CommandServerControl	=> 120,
    ConfigurationEvent		=> 51,
    CPILevel			=> 27,
    CreationDate		=> 2004,
    CreationTime		=> 2005,
    Custom			=> 2119,
    DeadLetterQName		=> 2006,
    DefXmitQName		=> 2025,
    DistLists			=> 34,
    DNSGroup			=> 2071,
    DNSWLM			=> 106,
    ExpiryInterval		=> 39,
    EncryptionPolicySuiteB	=> 247,
    GroupUR			=> 221,
    IGQUserId			=> 2041,
    IGQPutAuthority		=> 65,
    InhibitEvent		=> 48,
    IntraGroupQueueing		=> 64,
    IPAddressVersion		=> 93,
    ListenerTimer		=> 107,
    LocalEvent			=> 49,
    LoggerEvent			=> 94,
    LUGroupName			=> 2072,
    LUName			=> 2073,
    LU62ARMSuffix		=> 2074,
    LU62Channels		=> 108,
    MaxActiveChannels		=> 100,
    MaxChannels			=> 109,
    MaxHandles			=> 11,
    MaxMsgLength		=> 13,
    MaxPriority			=> 14,
    MaxPropertiesLength		=> 192,
    MaxUncommittedMsgs		=> 33,
    MQIAccounting		=> 133,
    MQIStatistics		=> 127,
    MsgMarkBrowseInterval	=> 68,
    OpMode			=> 1326,
    OutboundPortMax		=> 140,
    OutboundPortMin		=> 110,
    Parent			=> 2102,
    PerformanceEvent		=> 53,
    Platform			=> 32,
    PubSubClus			=> 249,
    PubSubMaxMsgRetryCount	=> 206,
    PubSubMode			=> 187,
    PubSubNPInputMsg		=> 203,
    PubSubNPResponse		=> 205,
    PubSubSyncPoint		=> 207,
    QMgrDesc			=> 2014,
    QMgrIdentifier		=> 2032,
    QMgrName			=> 2015,
    QSharingGroupName		=> 2040,
    QueueAccounting		=> 134,
    QueueMonitoring		=> 123,
    QueueStatistics		=> 128,
    ReceiveTimeout		=> 111,
    ReceiveTimeoutMin		=> 113,
    ReceiveTimeoutType		=> 112,
    RemoteEvent			=> 50,
    RepositoryName		=> 2035,
    RepositoryNamelist		=> 2036,
    SecurityCase		=> 141,
    SharedQQMgrName		=> 77,
    SSLCRLNamelist		=> 2050,
    SSLCryptoHardware		=> 2051,
    SSLEvent			=> 75,
    SSLFipsRequired		=> 92,
    SSLKeyRepository		=> 2049,
    SSLKeyResetCount		=> 76,
    SSLTasks			=> 69,
    StartStopEvent		=> 52,
    StatisticsInterval		=> 131,
    SyncPoint			=> 30,
    TCPChannels			=> 114,
    TCPKeepAlive		=> 115,
    TCPStackType		=> 116,
    TCPName			=> 2075,
    TraceRouteRecording		=> 137,
    TreeLifeTime		=> 183,
    TriggerInterval		=> 25,
    Version			=> 2120,
    XrCapability			=> 243,
   },

   AdoptNewMCACheck =>
   {
    All				=> 1,
    NetworkAddress		=> 4,
    None			=> 0,
    QMgrName			=> 2,
   },

   AdoptNewMCAType =>
   {
    All				=> 1,
    No				=> 0,
   },

   ChannelEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    Exception			=> 2,
   },

   CommandEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    NoDisplay			=> 3,
   },

   #
   # Pub/Sub mode
   #
   PubSubMode =>
   {
    Compat			=> 1,
    Disabled			=> 0,
    Enabled			=> 2,
   },

   #
   # Pub/Sub undelivered input messages
   #
   PubSubNPInputMsg =>
   {
    Discard			=> 2,
    Keep			=> 3,
   },

   #
   # Pub/Sub undelivered response messages
   #
   PubSubNPResponse =>
   {
    Discard			=> 2,
    Keep			=> 3,
    Normal			=> 0,
    Safe			=> 1,
   },

   #
   # Pub/Sub syncpoint
   #
   PubSubSyncPoint =>
   {
    IfPersistent		=> 1,
    Yes				=> 0,
   },

   Recording =>			# ActivityRecording / TraceRouteRecording
   {
    Disabled			=> 0,
    Msg				=> 2,
    Queue			=> 1,
   },

   QMgrAccounting =>		# QMgr-level Queue/Channel Accounting
   {
    None			=> -1,
    Off				=> 0,
    On				=> 1,
   },

   QMgrMonitoring =>		# QMgr-level Queue/Channel Monitoring, ChannelStatistics
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None			=> -1,
    Off				=> 0,
   },

   QMgrQueueStatistics =>
   {
    None			=> -1,
    Off				=> 0,
    On				=> 1,
   },

   QMgrServiceControl =>
   {				# ChInitControl, CommandServerControl
    Manual			=> 2,
    QMgr			=> 0,
   },

   QMStatusAttrs =>
   {
    All				=> 1009,

    ChannelInitiatorStatus	=> 1232,
    CommandServerStatus		=> 1233,
    ConnectionCount		=> 1230,
    CurrentLog			=> 3071,
    InstallationDesc		=> 2115,
    InstallationName		=> 2116,
    InstallationPath		=> 2117,
    LogPath			=> 3074,
    MediaRecoveryLog		=> 3073,
    QMgrName			=> 2015,
    QMgrStatus			=> 1149,
    RestartRecoveryLog		=> 3072,
    StartDate			=> 3175,
    StartTime			=> 3176,
   },

   ReceiveTimeoutType =>
   {
    Add				=> 1,
    Equal			=> 2,
    Multiply			=> 0,
   },

   SecurityCase =>
   {
    Mixed			=> 1,
    Upper			=> 0,
   },

   SharedQQMgrName =>
   {
    Ignore			=> 1,
    Use				=> 0,
   },

   TCPStackType =>
   {
    Multiple			=> 1,
    Single			=> 0,
   },

   #
   # Process
   #
   Process =>
   {
    All				=> 1009,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    ApplId			=> 2001,
    ApplType			=> 1,
    EnvData			=> 2007,
    ProcessDesc			=> 2011,
    ProcessName			=> 2012,
    ProcessNames		=> 3012,
    UserData			=> 2021,
   },

   ApplType =>
   {
    AIX				=> 6,
    CHINIT			=> 30,
    CICS			=> 1,
    CICSVSE			=> 10,
    DOS				=> 5,
    Default			=> 6,
    IMS				=> 3,
    MVS				=> 2,
    NSK				=> 13,
    OS2				=> 4,
    OS400			=> 8,
    QMGR			=> 7,
    UNIX			=> 6,
    USER			=> 25,
    VMS				=> 12,
    Win16			=> 9,
    Win32			=> 11,
    ZOS				=> 2,
   },

   #
   # Queue
   #
   Queue =>
   {
    All				=> 1009,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    BackoutRequeueName		=> 2019,
    BackoutThreshold		=> 22,
    BaseObjectName		=> 2002,
    BaseQName			=> 2002,
    BaseType			=> 193,
    CFStructure			=> 2039,
    CLWLQueuePriority		=> 96,
    CLWLQueueRank		=> 95,
    CLWLUseQ			=> 98,
    ClusterDate			=> 2037,
    ClusterName			=> 2029,
    ClusterNamelist		=> 2030,
    ClusterQMgrName		=> 2031,
    ClusterQType		=> 59,
    ClusterTime			=> 2038,
    CreationDate		=> 2004,
    CreationTime		=> 2005,
    CurrentQDepth		=> 3,
    Custom			=> 2119,
    DefBind			=> 61,
    DefinitionType		=> 7,
    DefInputOpenOption		=> 4,
    DefPersistence		=> 5,
    DefPriority			=> 6,
    DefPutResponse		=> 184,
    DefReadAhead		=> 188,
    DistLists			=> 34,
    HardenGetBackout		=> 8,
    HighQDepth			=> 36,
    IndexType			=> 57,
    InhibitGet			=> 9,
    InhibitPut			=> 10,
    InitiationQName		=> 2008,
    MaxMsgLength		=> 13,
    MaxQDepth			=> 15,
    MsgDeliverySequence		=> 16,
    MsgDeqCount			=> 38,
    MsgEnqCount			=> 37,
    NonPersistentMsgClass	=> 78,
    OpenInputCount		=> 17,
    OpenOutputCount		=> 18,
    PageSetId			=> 62,
    ProcessName			=> 2012,
    PropertyControl		=> 190,
    QDepthHighEvent		=> 43,
    QDepthHighLimit		=> 40,
    QDepthLowEvent		=> 44,
    QDepthLowLimit		=> 41,
    QDepthMaxEvent		=> 42,
    QDesc			=> 2013,
    QMgrIdentifier		=> 2032,
    QName			=> 2016,
    QNames			=> 3011,
    QueueAccounting		=> 134,
    QueueMonitoring		=> 123,
    QueueStatistics		=> 128,
    QSGDisposition		=> 63,
    QServiceInterval		=> 54,
    QServiceIntervalEvent	=> 46,
    QType			=> 20,
    RemoteQMgrName		=> 2017,
    RemoteQName			=> 2018,
    RetentionInterval		=> 21,
    Scope			=> 45,
    Shareability		=> 23,
    StorageClass		=> 2022,
    TimeSinceReset		=> 35,
    TPipeNames			=> 2085,
    TriggerControl		=> 24,
    TriggerData			=> 2023,
    TriggerDepth		=> 29,
    TriggerMsgPriority		=> 26,
    TriggerType			=> 28,
    Usage			=> 12,
    XmitQName			=> 2024,
   },

   QType =>
   {
    Alias			=> 3,
    All				=> 1001,
    Cluster			=> 7,
    Local			=> 1,
    Model			=> 2,
    Remote			=> 6,
   },

   BaseType =>
   {
    Queue			=> 1,
    Topic			=> 8,
   },

   QMoveType =>
   {
    Move			=> 1146,
    Add				=> 1147,
   },

   ClearType =>
   {
    Retained			=> 1,
   },

   DefInputOpenOption =>
   {
    Exclusive			=> 4,
    Shared			=> 2,
   },

   #
   # Default Put Response Type (MQ v7)
   #
   DefPutResponse =>
   {
    AsParent			=> 0,
    Async			=> 2,
    Sync			=> 1,
   },

   #
   # Default Read Ahead (MQ v7)
   #
   DefReadAhead =>
   {
    Disabled			=> 2,
    No				=> 0,
    Yes				=> 1,
   },

   #
   # Durable Pub/Sub Subscriptions for MQ v7 (Part of Subscription object)
   #
   Durable =>
   {
    All				=> -1,
    Yes				=> 1,
    No				=> 2,
   },

   #
   # Pub/Sub Topics on MQ v7
   #
   InhibitPublications =>
   {
    Allowed			=> 2,
    AsParent			=> 0,
    Inhibited			=> 1,
   },

   #
   # Pub/Sub Topics on MQ v7
   #
   InhibitSubscriptions =>
   {
    Allowed			=> 2,
    AsParent			=> 0,
    Inhibited			=> 1,
   },

   Multicast =>
   {
    AsParent			=> 0,
    Enabled			=> 1,
    Disabled			=> 2,
    Only			=> 3,
   },

   MonitoringDft =>		# ClusSdrMonDft, Queue-level QueueMonitoring, Channel-level ChannelMonitoring
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    Off				=> 0,
    QMgr			=> -3,
   },

   #
   # Pub/Sub Message Delivery
   #
   MsgDelivery =>
   {
    All				=> 1,
    AllAvailable		=> 3,
    AllDurable			=> 2,
    AsParent			=> 0,
   },

   MsgDeliverySequence =>
   {
    FIFO			=> 1,
    Priority			=> 0,
   },

   #
   # Property Control (MQ v7)
   #
   PropertyControl =>
   {
    All				=> 2,
    Compatibility		=> 0,
    ForceRFH2			=> 3,
    None			=> 1,
    V6Compat			=> 4,
   },

   #
   # Proxy Subscriptions (Topic for MQ v7)
   #
   ProxySubscriptions =>
   {
    FirstUse			=> 2,
    Force			=> 1,
   },

   #
   # Pub/Sub properties for Subscription on MQ v7
   #
   PubSubProperties =>
   {
    Compat			=> 1,
    None			=> 0,
    RFH2			=> 2,
   },

   #
   # Pub/Sub scope for Topic on MQ v7
   #
   PubSubScope =>
   {
    All				=> 0,
    AsParent			=> 1,
    QMgr			=> 4,
   },

   Usage =>
   {
    Normal			=> 0,
    XMITQ			=> 1,
   },

   TopicType =>
   {
    Cluster			=> 1,
    Local			=> 0,
   },

   TriggerType =>
   {
    Depth			=> 3,
    Every			=> 2,
    First			=> 1,
    None			=> 0,
   },

   DefinitionType =>
   {
    Permanent			=> 2,
    Predefined			=> 1,
    Shared			=> 4,
    Temporary			=> 3,
   },

   IGQPutAuthority =>
   {
    AltIGQ			=> 4,
    Context			=> 2,
    Default			=> 1,
    OnlyIGQ			=> 3,
   },

   #
   # IndexType is for queues on z/OS
   #
   IndexType =>
   {
    CorrelId			=> 2,
    GroupId			=> 5,
    MsgId			=> 1,
    MsgToken			=> 4,
    None			=> 0,
   },

   IPAddressVersion =>
   {
    IPv4			=> 0,
    IPv6			=> 1,
   },

   #
   # QueueAccounting is also used for QueueMonitoring
   #
   QueueAccounting =>
   {
    Off				=> 0,
    On				=> 1,
    QMgr			=> -3,
   },

   QueueMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    Off				=> 0,
    QMgr			=> -3,
   },

   NonPersistentMsgClass =>
   {
    High			=> 10,
    Normal			=> 0,
   },

   Scope =>
   {
    Cell			=> 2,
    QMgr			=> 1,
   },

   QServiceIntervalEvent =>
   {
    High			=> 1,
    None			=> 0,
    OK				=> 2,
   },

   #
   # For Topic on MQ v7
   #
   WildcardOperation =>
   {
    Block			=> 1,
    Passthru			=> 2,
   },

   ClearTopicStringScope =>
   {
    Local			=> 1,
    Global			=> 2,
   },

   #
   # Channels
   #
   Channel =>
   {
    All				=> 1009,
    MonitoringAttrs		=> 1258,

    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    BatchDataLimit		=> 1624,
    BatchHeartBeat		=> 1567,
    BatchInterval		=> 1564,
    BatchSize			=> 1502,
    ChannelDesc			=> 3502,
    ChannelDisposition		=> 1580,
    ChannelMonitoring		=> 122,
    ChannelName			=> 3501,
    ChannelNames		=> 3512,
    ChannelStatistics		=> 129,
    ChannelType			=> 1511,
    ClientChannelWeight		=> 1620,
    ClusterName			=> 2029,
    ClusterNamelist		=> 2030,
    CLWLChannelPriority		=> 1578,
    CLWLChannelRank		=> 1577,
    CLWLChannelWeight		=> 1579,
    ConnectionAffinity		=> 1621,
    ConnectionName		=> 3506,
    DataConversion		=> 1515,
    DefReconnect		=> 1640,
    DiscInterval		=> 1503,
    HeaderCompression		=> 1575,
    HeartbeatInterval		=> 1563,
    KeepAliveInterval		=> 1566,
    LocalAddress		=> 3520,
    LongRetryCount		=> 1507,
    LongRetryInterval		=> 1506,
    MaxInstances		=> 1618,
    MaxInstancesPerClient	=> 1619,
    MaxMsgLength		=> 1510,
    MCAName			=> 3507,
    MCAType			=> 1517,
    MCAUserIdentifier		=> 3527,
    MessageCompression		=> 1576,
    ModeName			=> 3503,
    MsgExit			=> 3509,
    MsgRetryCount		=> 1544,
    MsgRetryExit		=> 3534,
    MsgRetryInterval		=> 1545,
    MsgRetryUserData		=> 3535,
    MsgUserData			=> 3514,
    NonPersistentMsgSpeed	=> 1562,
    Password			=> 3518,
    PropertyControl		=> 190,
    PutAuthority		=> 1508,
    QMgrName			=> 2015,
    ReceiveExit			=> 3511,
    ReceiveUserData		=> 3516,
    ResetRequested		=> 1623,
    SecurityExit		=> 3508,
    SecurityUserData		=> 3513,
    SendExit			=> 3510,
    SendUserData		=> 3515,
    SeqNumberWrap		=> 1509,
    SharingConversations	=> 1615,
    ShortRetryCount		=> 1505,
    ShortRetryInterval		=> 1504,
    SSLCipherSpec		=> 3544,
    SSLClientAuth		=> 1568,
    SSLPeerName			=> 3545,
    TpName			=> 3504,
    TransportType		=> 1501,
    UserIdentifier		=> 3517,
    XmitQName			=> 3505,
    UseDLQ			=> 234,
   },

   ChlAuthAction =>
   {
    Add				=> 5,
    Replace			=> 6,
    Remove			=> 7,
    RemoveAll			=> 8,
   },

   ChlAuthAttrs =>
   {
    All				=> 1009,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    ChlAuthDesc			=> 2118,
    RemoteQMgrName		=> 2017,
    ChlAuth			=> 3501,
    ClientUserId		=> 3567,
    Address			=> 3506,
    Addrlist			=> 3566,
    MCAUserIdentifier		=> 3527,
    MCAUserIdList		=> 3568,
    SSLPeerName			=> 3545,
    ChAuthType			=> 1352,
    Match			=> 1637,
    UserSource			=> 1638,
    Warning			=> 1639,
   },

   ChlAuthType =>
   {
    BlockUser			=> 1,
    BlockAddress		=> 2,
    SSLPeerMap			=> 3,
    AddressMap			=> 4,
    UserMap			=> 5,
    QMgrMap			=> 6,
    All				=> 0,
   },

   ChlAuthMatch =>
   {
    Runcheck			=> 1,
    Exact			=> 2,
    Generic			=> 0,
    All				=> 3,
   },

#   ChlAuthRecords =>
#   {
#    Disabled			=> 0,
#    Enabled			=> 1,
#   },

#   ChlAuthWarning =>
#   {
#    No				=> 0,
#    Yes				=> 1,
#   },

   EncryptionPolicySuiteB =>
   {
    None			=> 1,
    "128Bit"			=> 2,
    "192Bit"			=> 4,
   },

#   PubSubClus =>
#   {
#    Disabled			=> 0,
#    Enabled			=> 1,
#   },

   UserSource =>
   {
    Channel			=> 2,
    Map				=> 0,
    NoAccess			=> 1,
   },

   ChannelDisposition =>
   {
    All				=> -1,
    Private			=> 4,
    Shared			=> 2,
    Fixshared			=> 5,
   },

   DefReconnect =>
   {
    QMgr			=> 2,
    Disabled			=> 3,
    No				=> 0,
    Yes				=> 1,
   },

   UseDLQ =>
   {
    No				=> 1,
    Yes				=> 2,
   },

   TopicUseDLQ =>
   {
    AsParent			=> 0,
    No				=> 1,
    Yes				=> 2,
   },

   #
   # Channel Status
   #
   ChannelInstanceAttrs =>
   {
    All				=> 1009,
    MonitoringAttrs		=> 1258,

    BatchSize			=> 1502,
    BatchSizeIndicator		=> 1607,
    Batches			=> 1537,
    BuffersReceived		=> 1539,
    BuffersSent			=> 1538,
    BytesReceived		=> 1536,
    BytesSent			=> 1535,
    ChannelInstanceType		=> 1523,
    ChannelMonitoring		=> 122,
    ChannelName			=> 3501,
    ChannelStartDate		=> 3529,
    ChannelStartTime		=> 3528,
    ChannelStatus		=> 1527,
    ChannelType			=> 1511,
    CompressionRate		=> 1611,
    CompressionTime		=> 1612,
    ConnectionName		=> 3506,
    CurrentLUWID		=> 3532,
    CurrentMsgs			=> 1531,
    CurrentSequenceNumber	=> 1532,
    CurrentSharingConversations	=> 1617,
    ExitTime			=> 1606,
    HeaderCompression		=> 1575,
    HeartbeatInterval		=> 1563,
    InDoubtStatus		=> 1528,
    KeepAliveInterval		=> 1566,
    LastLUWID			=> 3531,
    LastMsgDate			=> 3525,
    LastMsgTime			=> 3524,
    LastSequenceNumber		=> 1529,
    LocalAddress		=> 3520,
    LongRetriesLeft		=> 1540,
    MaxSharingConversations	=> 1616,
    MCAJobName			=> 3530,
    MCAStatus			=> 1542,
    MCAUserIdentifier		=> 3527,
    MessageCompression		=> 1576,
    Msgs			=> 1534,
    MsgsAvailable		=>  1608,
    NetTime			=> 1605,
    NonPersistentMsgSpeed	=> 1562,
    QMgrName			=> 2015,
    RemoteApplTag		=> 3548,
    RemoteQMgrName		=> 2017,
    RemoteProduct		=> 3561,
    RemoteVersion		=> 3560,
    ShortRetriesLeft		=> 1541,
    SSLCertRemoteIssuerName	=> 3550,
    SSLCertUserId		=>  3549,
    SSLKeyResetDate		=> 3558,
    SSLKeyResets		=> 1610,
    SSLKeyResetTime		=> 3559,
    SSLShortPeerName		=> 3547,
    StopRequested		=> 1543,
    SubState			=> 1609,
    XmitQName			=> 3505,
    XQTime			=> 1604,
   },

   ChannelMode =>
   {
    Quiesce			=> 1,
    Force			=> 0,
    Terminate			=> 2,
   },

   ChannelStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   ChannelStatus =>
   {
    Inactive			=> 0,
    Stopped			=> 6,
   },

   ChannelMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   ChannelType =>
   {
    All				=> 5,
    Clntconn			=> 6,
    ClusterReceiver		=> 8,
    ClusterSender		=> 9,
    Receiver			=> 3,
    Requester			=> 4,
    Sender			=> 1,
    Server			=> 2,
    Svrconn			=> 7,
    Telemetry			=> 10,
   },

   #
   # Destination Class for Subscriptions in MQ v7
   #
   DestinationClass =>
   {
    Managed			=> 1,
    Provided			=> 2,
   },

   HeaderCompression =>
   {
    None			=> 0,
    System			=> 8,
   },

   MessageCompression =>
   {
    Any				=> 268435455,
    None			=> 0,
    RLE				=> 1,
    ZlibFast			=> 2,
    ZlibHigh			=> 4,
   },

   # VALUEMAP-CODEREF
   KeepAliveInterval =>
        sub { return MQSeries::Command::Base::strinteger(@_, -1,
                                                    "AUTO", 99999); },

   # VALUEMAP-CODEREF
   MsgMarkBrowseInterval =>
        sub { return MQSeries::Command::Base::strinteger(@_, -1,
                                                    "NOLIMIT", 999999999); },
# 100MB max
   # VALUEMAP-CODEREF
   MaxPropertiesLength =>
        sub { return MQSeries::Command::Base::strinteger(@_, -1,
                                                    "NOLIMIT", 104857600); },

   # VALUEMAP-CODEREF
   ComminfoCCSID =>
        sub { return MQSeries::Command::Base::strinteger(@_, -4,
                                                    "ASPUB", 65535); },

   TransportType =>
   {
    DECnet			=> 5,
    LU62			=> 1,
    NetBIOS			=> 3,
    SPX				=> 4,
    TCP				=> 2,
    UDP				=> 6,
   },

   PutAuthority =>
   {
    Context			=> 2,
    Default			=> 1,
   },

   MCAType =>
   {
    Process			=> 1,
    Thread			=> 2,
   },

   NonPersistentMsgSpeed =>
   {
    Normal			=> 1,
    Fast			=> 2,
   },

   QMgrCLWLUseQ =>		# QMgr-level
   {
    Any				=> 1,
    Local			=> 0,
   },

   QueueCLWLUseQ =>		# Queue-level
   {
    Any				=> 1,
    Local			=> 0,
    QMgr			=> -3,
   },

   ChannelTable =>
   {
    Clntconn			=> 2,
    QMgr			=> 1,
   },

   ChannelInstanceType =>
   {
    Current			=> 1011,
    Saved			=> 1012,
   },

   InDoubt =>
   {
    Backout			=> 2,
    Commit			=> 1,
   },

   SSLClientAuth =>
   {
    Optional			=> 1,
    Required			=> 0,
   },

   #
   # Escape
   #
   EscapeType =>
   {
    MQSC			=> 1,
   },

   #
   # New entries for MQSeries 5.1
   #
   Cluster =>
   {
    All				=> 1009,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    BatchInterval		=> 1564,
    BatchSize			=> 1502,
    ChannelStatus		=> 1527,
    ClusterDate			=> 2037,
    ClusterName			=> 2029,
    ClusterTime			=> 2038,
    ConnectionName		=> 3506,
    DataConversion		=> 1515,
    Description			=> 3502,          # ? not documented in response
    DiscInterval		=> 1503,
    HeartbeatInterval		=> 1563,
    LongRetryCount		=> 1507,
    LongRetryInterval		=> 1506,
    MCAName			=> 3507,
    MCAType			=> 1517,
    MCAUserIdentifier		=> 3527,
    MaxMsgLength		=> 1510,
    ModeName			=> 3503,
    MsgExit			=> 3509,
    MsgRetryCount		=> 1544,
    MsgRetryExit		=> 3534,
    MsgRetryInterval		=> 1545,
    MsgRetryUserData		=> 3535,
    MsgUserData			=> 3514,
    NetworkPriority		=> 1565,
    NonPersistentMsgSpeed	=> 1562,
    Password			=> 3518,
    PutAuthority		=> 1508,
    QMgrDefinitionType		=> 1084,
    QMgrIdentifier		=> 2032,
    QMgrType			=> 1085,
    ReceiveExit			=> 3511,
    ReceiveUserData		=> 3516,
    SecurityExit		=> 3508,
    SecurityUserData		=> 3513,
    SendExit			=> 3510,
    SendUserData		=> 3515,
    SeqNumberWrap		=> 1509,
    ShortRetryCount		=> 1505,
    ShortRetryInterval		=> 1504,
    Suspend			=> 1087,
    TpName			=> 3504,
    TransportType		=> 1501,
    UserIdentifier		=> 3517,
    XmitQName			=> 3505,
   },

   RefreshRepository =>
   {
    Yes				=> 1,
    No				=> 0,
   },

   NamelistAttrs =>
   {
    All				=> 1009,

    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    NamelistDesc		=> 2009,
    NamelistName		=> 2010,
    Names			=> 2020,
    NameCount			=> 19,
    NamelistType		=> 72,
   },

   ClusterAction =>
   {
    ForceRemove			=> 1,
   },

   QMgrAction =>
   {
    AdvanceLog			=> 2,
    CollectStatistics		=> 3,
    PubSub			=> 4
   },

   QMgrFacility =>
   {
    DB2				=> 2,
    IMSBridge			=> 1,
   },

   DefBind =>
   {
    OnGroup			=> 2,
    OnOpen			=> 0,
    NotFixed			=> 1,
   },

   ObjectType =>
   {
    AuthInfo			=> 7,
    Listener			=> 11,
    Namelist			=> 2,
    Process			=> 3,
    Queue			=> 1,
    QueueManager		=> 5,
    Service			=> 12,
    Topic			=> 8,

    Channel			=> 6,

    All				=> 1001,
    AliasQueue			=> 1002,
    ModelQueue			=> 1003,
    LocalQueue			=> 1004,
    RemoteQueue			=> 1005,

    SenderChannel		=> 1007,
    ServerChannel		=> 1008,
    RequesterChannel		=> 1009,
    ReceiverChannel		=> 1010,
    CurrentChannel		=> 1011,
    SavedChannel		=> 1012,
    SvrconnChannel		=> 1013,
    ClntconnChannel		=> 1014,
    CFStruc			=> 10,
    ChlAuth			=> 1016,
    StorageClass		=> 4,
   },

   #
   # AuthInfo
   #
   AuthInfoAttrs =>
   {
    All				=> 1009,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    AuthInfoConnName		=> 2053,
    AuthInfoDesc		=> 2046,
    AuthInfoName		=> 2045,
    AuthInfoType		=> 66,
    LDAPPassword		=> 2048,
    LDAPUserName		=> 2047,
    OCSPResponderURL		=> 2109,
   },

   AuthInfoType =>
   {
    CRLLDAP			=> 1,
    OCSP			=> 2,            # new with v7.0.1.1
    All				=> 0,
   },

   #
   # Queue Status
   #
   OpenType =>
   {
    All				=> 1,
    Input			=> 2,
    Output			=> 3,
   },

   QStatusAttrs =>
   {
    All				=> 1009,
    MonitoringAttrs		=> 1258,

    ApplTag			=> 3058,
    ApplType			=> 1,
    ASId			=> 3081,
    AsynchronousState		=> 1308,
    ChannelName			=> 3501,
    Conname			=> 3506,
    CurrentQDepth		=> 3,
    ExternalUOWId		=> 7005,
    HandleState			=> 1028,
    LastGetDate			=> 3130,
    LastGetTime			=> 3131,
    LastPutDate			=> 3128,
    LastPutTime			=> 3129,
    MediaRecoveryLog		=> 3073,
    OldestMsgAge		=> 1227,
    OnQTime			=> 1226,
    OpenBrowse			=> 1102,
    OpenInputCount		=> 17,
    OpenInputType		=> 1098,
    OpenInquire			=> 1101,
    OpenOptions			=> 1022,
    OpenOutput			=> 1099,
    OpenOutputCount		=> 18,
    OpenSet			=> 1100,
    ProcessId			=> 1024,
    PSBName			=> 3082,
    PSTId			=> 3083,
    QMgrUOWId			=> 7009,
    QName			=> 2016,
    QueueMonitoring		=> 123,
    TaskNumber			=> 3084,
    ThreadId			=> 1025,
    TransactionId		=> 3085,
    UncommittedMsgs		=> 1027,
    UserIdentifier		=> 3025,
    UOWIdentifier		=> 7005,
    UOWType			=> 1132,
   },

   StatusType =>
   {
    Queue			=> 1105,
    Handle			=> 1104,
   },

#   Authrec =>
#   {
#    Yes				=> 1,
#    No				=> 0,
#   },

   #
   # Namelist
   #
   NamelistType =>
   {
    All				=> 1001,
    AuthInfo			=> 4,
    Cluster			=> 2,
    None			=> 0,
    Queue			=> 1,
   },

   #
   # CF Structure (MQ on z/OS)
   #
   CFConlos =>
   {
    AsQMgr			=> 2,
    Terminate			=> 0,
    Tolerate			=> 1,
   },

   Offload =>
   {
    DB2				=> 2,
    SMDS			=> 1,
    None			=> 0,
   },

   DSExpand =>
   {
    Yes				=> 1,
    No				=> 2,
    Default			=> 0,
   },

   DSBlock =>
   {
    "8K"			=> 1,
    "16K"			=> 2,
    "32K"			=> 3,
    "64K"			=> 4,
    "128K"			=> 5,
    "256K"			=> 6,
    "512K"			=> 7,
    "1024K"			=> 8,
    "1M"			=> 8,
   },

   CFStrucAttrs =>
   {
    All				=> 1009,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    CFConlos			=> 246,
    CFLevel			=> 70,
    CFStrucDesc			=> 2052,
    CFStrucName			=> 2039,
    DSBlock			=> 1328,
    DSBufs			=> 228,
    DSExpand 			=> 1329,
    DSGroup			=> 3182,
    Offload			=> 224,
    Recauto			=> 244,
    Recovery			=> 71,
   },

#   Recauto =>
#   {
#    Yes				=> 1,
#    No				=> 0,
#   },

   CFStatusType =>
   {
    CFStatusSummary		=> 1136,
    CFStatusConnect		=> 1137,
    CFStatusBackup		=> 1138,
    CFStatusSMDS		=> 1333,
   },

   #
   # CF Structure (MQ on z/OS)
   #
   # NOTE: CFStruct is for backwards compatibility with pre-1.24 MQSC
   #	   New code should use CFStruc (no final 't')
   #
   CFStructAttrs =>
   {
    All				=> 1009,

    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    CFLevel			=> 70,
    CFStructDesc		=> 2052,
    CFStructName		=> 2039,
    Recovery			=> 71,
   },

   #
   # Storage Class (MQ on z/OS)
   #
   StorageClassAttrs =>
   {
    All				=> 1009,

    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    PageSetId			=> 62,
    StorageClassDesc		=> 2042,
    StorageClassName		=> 2022,
    XCFGroupName		=> 2043,
    XCFMemberName		=> 2044,
   },

   #
   # QSG Disposition
   #
   QSGDisposition =>
   {
    All				=> -1,
    Copy			=> 1,
    Group			=> 3,
    Private			=> 4,
    Live			=> 6,
    QMgr			=> 0,
    Shared			=> 2,
   },

   #
   # UsageType (for InquireUsage, MQ on z/OS)
   #
   UsageType =>
   {
    All				=> 1009,
    BufferPool			=> 1170,
    DataSet			=> 1169,
    Pageset			=> 1168,
    SMDS			=> 1335,
   },

   #
   # Security (MQ on z/OS)
   #
   SecurityAttrs =>
   {
    All				=> 1009,
    SecurityInterval		=> 1153,
    SecuritySwitch		=> 1154,
    SecurityTimeout		=> 1152,
    #SecuritySwitchProfile	=> 3090,
    #SecuritySwitchSetting	=> 1155,
   },

   #
   # V7 for SetLog
   #
   LogCompression =>
   {
    None			=> 0,
    RLE				=> 1,
    Any				=> 268435455,
   },

   #
   # Commented lines came out of v7. But they seem to be
   # similar to existing ones except MQ being replaced with MX.
   # Needs clarification.
   #
   SecurityItem =>
   {
    All				=> 0,
    Administration		=> 1,
    Namelist			=> 2,
    Process			=> 3,
    Queue			=> 4,
    #XAdministration		=> 7,
    #XNamelist			=> 8,
    #XProcess			=> 9,
    #XQueue			=> 10,
    #XTopic			=> 11,
   },

   #
   # SecurityType is for distributed and z/OS
   #
   SecurityType =>
   {
    AuthorizationService	=> 1,                   	# Default on distributed
    Classes			=> 3,                   # Default on z/OS
    SSL				=> 2,
   },

   #
   # EntityType is for InquireAuthorityRecords (MQ v6 on distributed)
   #
   EntityType =>
   {
    Group			=> 2,
    Principal			=> 1,
   },

   #
   # Authority (MQ v6 on distributed platforms)
   #
   Authority =>
   {
    All				=> -1,
    AllAdmin			=> -2,
    AllMqi			=> -3,
    AltUser			=> 1,
    Browse			=> 2,
    Change			=> 3,
    Clear			=> 4,
    Connect			=> 5,
    Control			=> 17,
    ControlExtended		=> 18,
    Create			=> 6,
    Delete			=> 7,
    Display			=> 8,
    Input			=> 9,
    Inquire			=> 10,
    None			=> 0,
    Output			=> 11,
    PassAllContext		=> 12,
    PassIdentityContext		=> 13,
    Publish			=> 19,
    Resume			=> 21,
    Set				=> 14,
    SetAllContext		=> 15,
    SetIdentityContext		=> 16,
    Subscribe			=> 20,
    System			=> 22,
   },

   #
   # Authority Profile Atrts (MQ v6 on distributed platforms)
   #
   AuthProfileAttrs =>
   {
    All				=> 1009,
    AuthorizationList		=> 1115,
    EntityName			=> 3068,
    EntityType			=> 1118,
    ObjectType			=> 1016,
   },

   AuthOptions =>
   {
    NameAllMatching		=> 32,
    NameExplicit		=> 16,
    EntityExplicit		=> 1,
    EntitySet			=> 2,
    NameAsWildcard		=> 64,
   },

   #
   # Authority Service (MQ v6 on distributed platforms)
   #
   AuthServiceAttrs =>
   {
    All				=> 1009,
    InterfaceVersion		=> 1263,
    UserIdSupport		=> 1262,
   },

   #
   # Channel Connection Affinity (MQ v7)
   #
   ConnectionAffinity =>
   {
    None			=> 0,
    Preferred			=> 1,
   },

   #
   # Listener
   #
   ListenerAttrs =>
   {
    All				=> 1009,
    Adapter			=> 1519,
    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    Backlog			=> 1602,
    Commands			=> 1520,
    IPAddress			=> 3552,
    ListenerDesc		=> 3555,
    ListenerName		=> 3554,
    LocalName			=> 3521,
    NetBiosNames		=> 1513,
    Port			=> 1522,
    Sessions			=> 1518,
    Socket			=> 1521,
    StartMode			=> 1601,
    TPName			=> 3504,
    TransportType		=> 1501,
   },

   ListenerStartMode =>
   {
    Manual			=> 2,
    QMgr			=> 0,
    QMgrStart			=> 1,
   },

   ListenerTransportType =>
   {
    TCP				=> 2,
    LU62			=> 1,
    NetBIOS			=> 3,
    SPX				=> 4,
    All				=> -1,
   },

   InboundDisposition =>
   {
    QMgr			=> 0,
    Group			=> 3,
   },

   #
   # Service (installable service for distributed MQ v6)
   #
   ServiceAttrs =>
   {
    All				=> 1009,

    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    ServiceDesc			=> 2078,
    ServiceName			=> 2077,
    StartArguments		=> 2080,
    StartCommand		=> 2079,
    StartMode			=> 139,
    StopArguments		=> 2082,
    StopCommand			=> 2081,
    StderrDestination		=> 2084,
    StdoutDestination		=> 2083,
    ServiceType			=> 121,
   },

   ServiceStartMode =>
   {
    Manual			=> 2,
    QMgr			=> 0,
    QMgrStart			=> 1,
   },

   ServiceType =>
   {
    Command			=> 0,
    Server			=> 1,
   },

   #
   # Service Status (installable service for distributed MQ v6)
   #
   ServiceStatusAttrs =>
   {
    All				=> 1009,

    ProcessId			=> 1024,
    ServiceDesc			=> 2078,
    ServiceName			=> 2077,
    ServiceType			=> 121,
    StartArguments		=> 2080,
    StartCommand		=> 2079,
    StartDate			=> 3144,
    StartMode			=> 139,
    StartTime			=> 3145,
    Status			=> 1260,
    StopArguments		=> 2082,
    StopCommand			=> 2081,
    StderrDestination		=> 2084,
    StdoutDestination		=> 2083,
   },

   ServiceStatus =>
   {
    Running			=> 2,
    Starting			=> 1,
    Stopped			=> 0,
    Stopping			=> 3,
   },


   #
   # Listener Status
   #
   ListenerStatusAttrs =>
   {
    All				=> 1009,

    Adapter			=> 1519,
    Backlog			=> 1602,
    Commands			=> 1520,
    IPAddress			=> 3552,
    ListenerDesc		=> 3555,
    ListenerName		=> 3554,
    LocalName			=> 3521,
    NetBiosNames		=> 1513,
    Port			=> 1522,
    ProcessId			=> 1024,
    Sessions			=> 1518,
    Socket			=> 1521,
    StartDate			=> 3556,
    StartMode			=> 1601,
    StartTime			=> 3557,
    Status			=> 1599,
    TPName			=> 3504,
    TransportType		=> 1501,
   },

   #
   # Inquire Connection for V6
   #
   ConnectionAttrs =>
   {
    All				=> 1009,

    ASID			=> 3081,
    ApplTag			=> 3058,
    ApplType			=> 1,
    ChannelName			=> 3501,
    ConnectionId		=> 7006,
    ConnectionName		=> 3506,
    ConnectionOptions		=> 1108,
    HandleState			=> 1028,
    ObjectName			=> 3046,
    ObjectType			=> 1016,
    OpenOptions			=> 1022,
    OriginName			=> 3088,
    OriginUOWId			=> 7008,
    PSBName			=> 3082,
    PSTId			=> 3083,
    ProcessId			=> 1024,
    QMgrUOWId			=> 7009,
    QSGDisposition		=> 63,
    ReadAhead			=> 189,
    StartUOWLogExtent		=> 3064,
    TaskNumber			=> 3084,
    ThreadId			=> 1025,
    TransactionId		=> 3085,
    UOWIdentifier		=> 7005,
    UOWLogStartDate		=> 3062,
    UOWLogStartTime		=> 3063,
    UOWStartDate		=> 3060,
    UOWStartTime		=> 3061,
    UOWState			=> 1128,
    UOWType			=> 1132,
    URDisposition		=> 222,
    UserId			=> 3025,
    },

   ConnInfoType =>
   {
    Conn			=> 1111,
    Handle			=> 1112,
    All				=> 1113,
   },

   #
   # Unit of Recovery Disposition (V7)
   #
   URDisposition =>
   {
    All				=> -1,
    Group			=> 3,
    QMgr			=> 0,
   },

   #
   # Durable Pub/Sub Subscriptions for MQ v7 (Part of Topic object)
   #
   DurableSubscriptions =>
   {
    AsParent			=> 0,
    Allowed			=> 1,
    Inhibited			=> 2,
   },


   #
   # PublishPriority for
   #
   PublishPriority =>
   {
    AsPublished			=> -3,
    AsQDef			=> -1,
    0				=> 0,
    1				=> 1,
    2				=> 2,
    3				=> 3,
    4				=> 4,
    5				=> 5,
    6				=> 6,
    7				=> 7,
    8				=> 8,
    9				=> 9,
   },

   #
   # Subscription for MQ V7
   #
   SubscriptionAttrs =>
   {
    All				=> 1009,
    SummaryAttrs		=> 1309,

    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    CreationDate		=> 2004,
    CreationTime		=> 2005,
    Destination			=> 3154,
    DestinationClass		=> 1273,
    DestinationCorrelId		=> 7015,
    DestinationQueueManager	=> 3153,
    Durable			=> 1274,
    Expiry			=> 1244,
    PublishPriority		=> 1283,
    PublishSubscribeProperties	=> 1271,
    PublishedAccountingToken	=> 7010,
    PublishedApplicationIdentifier => 3135,
    RequestOnly			=> 1280,
    Selector			=> 3160,
    SubId			=> 7016,
    SubName			=> 3152,
    SubscriptionLevel		=> 1307,
    SubscriptionScope		=> 1275,
    SubscriptionType		=> 1289,
    SubscriptionUser		=> 3156,
    TopicName			=> 2092,
    TopicObject			=> 3031,
    TopicString			=> 2094,                # Not listed in docs
    UserData			=> 3159,
    VariableUser		=> 1277,
    WildcardSchema		=> 1288,
   },

   #
   # Subscription Status for MQ V7
   #
# LastPublishDate/Time sees to be related to InquireTopicStatus..Verify
   SubscriptionStatusAttrs =>
   {
    All				=> 1009,

    ActiveConnection		=> 7006,
    Durable			=> 1274,
    LastMessageDate		=> 3168,
    LastMessageTime		=> 3167,
#    LastPublishDate		=> 3161,
#    LastPublishTime		=> 3162,
    NumberOfMessages		=> 1290,
    ResumeDate			=> 2098,
    ResumeTime			=> 2099,
    SubscriptionUser		=> 3156,
    SubType			=> 1289,

   },

   SubscriptionType =>
   {
    Admin			=> 2,
    All				=> -1,
    API				=> 1,
    Proxy			=> 3,
    User			=> -2,
   },

   PubSubStatusAttrs =>
   {
    All				=> 1009,
    Status			=> 1311,
    Type			=> 1314,
   },

   PubSubStatusType =>
   {
    All				=> 0,
    Local			=> 1,
    Parent			=> 2,
    Child			=> 3,
   },

   #
   # Pub/Sub Topic for MQ V7
   #
   TopicAttrs =>
   {
    All				=> 1009,

    AlterationDate		=> 2027,
    AlterationTime		=> 2028,
    ClusterName			=> 2029,
    ClusterDate			=> 2037,
    ClusterTime			=> 2038,
    ClusterQMgrName		=> 2031,
    ComminfoName		=> 2110,
    Custom			=> 2119,
    DefPersistence		=> 185,
    DefPriority			=> 6,
    DefPutResponse		=> 184,
    DurableModelQName		=> 2096,
    DurableSubscriptions	=> 175,
    InhibitPublications		=> 181,
    InhibitSubscriptions	=> 182,
    NonDurableModelQName	=> 2097,
    NonPersistentMsgDelivery	=> 196,
    PersistentMsgDelivery	=> 195,
    ProxySubscriptions		=> 199,
    PublicationScope		=> 219,
    SubscriptionScope		=> 218,
    TopicDesc			=> 2093,
    TopicName			=> 2092,
    TopicString			=> 2094,
    TopicType			=> 208,               # Not in docs
    UseDLQ			=> 234,
    WildcardOperation		=> 216,                       # Not in docs
   },

   TopicDefPersistence =>
   {
    AsParent			=> -1,
    NonPersistent		=> 0,
    Persistent			=> 1,
   },

   TopicDefPriority =>
   {
    AsParent			=> -2,
    0				=> 0,
    1				=> 1,
    2				=> 2,
    3				=> 3,
    4				=> 4,
    5				=> 5,
    6				=> 6,
    7				=> 7,
    8				=> 8,
    9				=> 9,
   },

   #
   # Pub/Sub Topic Status for MQ V7
   #
   TopicStatusAttrs =>
   {
    All				=> 1009,

    ActiveConnection		=> 7006,
    AdminTopicName		=> 2105,
    DefPriority			=> 6,
    DefPersistence		=> 185,
    DefPutResponse		=> 184,
    DurableModelQName		=> 2096,
    Durable			=> 1274,
    DurableSubscriptions	=> 175,
    InhibitPublications		=> 181,
    InhibitSubscriptions	=> 182,
    LastMessageDate		=> 3168,
    LastMessageTime		=> 3167,
    LastPublishDate		=> 3161,
    LastPublishTime		=> 3162,
    NonDurableModelQName	=> 2097,
    NonPersistentMsgDelivery	=> 196,
    NumberOfMessages		=> 1290,
    NumberOfPublishes		=> 215,
    PersistentMsgDelivery	=> 195,
    PublicationScope		=> 219,
    PublishCount		=> 215,
    ResumeDate			=> 2098,
    ResumeTime			=> 2099,
    RetainedPublication		=> 1300,
    SubscriptionCount		=> 204,
    SubId			=> 7016,
    SubscriptionUserId		=> 3156,
    SubscriptionScope		=> 218,
    SubscriptionType		=> 1289,
    TopicString			=> 2094,
   },

   #
   # Pub/Sub Topic Status Type for MQ V7
   #
   TopicStatusType =>
   {
    Publication			=> 1297,
    Status			=> 1295,
    Subscription		=> 1296,
   },

   #
   # Variable Userid for Subscriptions in MQ v7
   #
   VariableUser =>
   {
    Any				=> 2,
    Fixed			=> 1,
   },

   #
   # Wildcard Schema for Subscriptions in MQ v7
   #
   WildcardSchema =>
   {
    Character			=> 1,
    Topic			=> 2,
   },

   #
   # For z/os v7
   #
   GroupUR =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
   },

   #
   # For RefreshQueueManager on z/OS
   #
   RefreshType =>
   {
    Configuration		=> 1,
    Expiry			=> 2,
    ProxySub			=> 4,
   },

   #
   # Pub/Sub scope for Subscription on MQ v7
   #
   SubscriptionScope =>
   {
    All				=> 2,
    QMgr			=> 1,
   },

   #
   # Comminfo for 7.1
   #
   ComminfoAttrs =>
   {
   All				=> 1009,

   CodedCharSetId		=> 2,
   CommEvent			=> 232,
   Bridge			=> 233,
   MonitorInterval		=> 81,
   Encoding			=> 1243,
   MulticastHeartbeat		=> 1628,
   MsgHistory			=> 1625,
   MulticastPropControl		=> 1626,
   NewSubHistory		=> 1627,
   PortNumber			=> 1522,
   AlterationDate		=> 2027,
   AlterationTime		=> 2028,
   ComminfoDesc			=> 2111,
   ComminfoType			=> 223,
   GrpAddress			=> 3562,
   },

   #
   # Comminfo Encoding
   #
   Encoding =>
   {
    AsPublished			=> -1,
    Normal			=> 273,
    Reversed			=> 546,
    S390			=> 785,
    TNS				=> 1041,
   },

   #
   # Comminfo ComminfoType
   # Currently only supported type is Multicast.
   #
   ComminfoType =>
   {
    Multicast			=> 1,
   },

   #
   # Comminfo CommEvent
   #
   CommEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    Exception			=> 2,
   },

   #
   # Comminfo NewSubHistory
   #
   NewSubHistory =>
   {
    None			=> 0,
    All				=> -1,
   },

   #
   # Comminfo MulticastPropControl
   #
   MulticastPropControl =>
   {
    All				=> -1,
    Reply			=> 2,
    User			=> 1,
    None			=> 0,
    Compat			=> -2,
   },

   #
   # Log for z/OS
   #
   ParameterType =>
   {
    Initial			=> 10,
    Set				=> 11,
   },

   FilterParams =>
   {
    Param			 => {
				     ExternalUOWId		=> 7005,
				     OriginUOWId		=> 7008,
				     QMgrUOWId			=> 7009,
				     ApplType			=> 1,
				     ConnectOptions		=> 1108,
				     ProcessId			=> 1024,
				     ThreadId			=> 1025,
				     UOWState			=> 1128,
				     UOWType			=> 1132,
				     QSGDisp			=> 63,
				     HandleState		=> 1028,
				     ObjectType			=> 1016,
				     OpenOptions		=> 1022,
				     },
    Operator			=> {
				    Greater			=> 4,
				    Less			=> 1,
				    Equal			=> 2,
				    NotEqual			=> 5,
				    NotLess			=> 6,
				    NotGreater			=> 3,
				    Contains			=> 10,
				    Excludes			=> 13,
				   },

   },

   FilterType =>
   {
    ExternalUOWId    => 15,
    OriginUOWId	     => 15,
    QMgrUOWId	     => 15,
    ApplType	     => 13,
    ConnectOptions   => 13,
    ProcessId	     => 13,
    ThreadId	     => 13,
    UOWState	     => 13,
    UOWType	     => 13,
    QSGDisp	     => 13,
    HandleState	     => 13,
    ObjectType	     => 13,
    OpenOptions	     => 13,
   },


   ByteFilterParams =>
   {
    Param			=> {
				    ExternalUOWId	       => 7005,
				    OriginUOWId		       => 7008,
				    QMgrUOWId		       => 7009,
				   },

    Operator			=> {
				    Greater			=> 4,
				    Less			=> 1,
				    Equal			=> 2,
				    NotEqual			=> 5,
				    NotLess			=> 6,
				    NotGreater			=> 3,
				   },
   },

   #
   # Morgan Stanley extensions
   #
   MorganEntityType =>
   {
    Principal			=> 1000,
    Group			=> 1001,
    AFS				=> 1002,
   },

  );

1;
