#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/Requests.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%Requests =
  (
   BackupCFStruc	       => [ 105,                    	       $RequestParameters{BackupCFStruc} ],

   ChangeAuthInfo		=> [ 79,                      		$RequestParameters{AuthInfo} ],
   ChangeCFStruc		=> [ 101,                    		$RequestParameters{CFStruc} ],
   # NOTE: ChangeCFStruct is for backwards compatibility with pre-1.24 MQSC
   ChangeCFStruct		=> [ 101,                    		$RequestParameters{CFStruct} ],
   ChangeChannel		=> [ 21,                    		$RequestParameters{Channel} ],
   ChangeChannelListener	=> [ 93,                     		$RequestParameters{Listener} ],
   ChangeComminfo		=> [ 192,                     		$RequestParameters{Comminfo} ],
   ChangeNamelist		=> [ 32,                     		$RequestParameters{Namelist} ],
   ChangeProcess		=> [ 3,                     		$RequestParameters{Process} ],
   ChangeQueue			=> [ 8,               			$RequestParameters{Queue} ],
   ChangeQueueManager		=> [ 1,                   		$RequestParameters{QueueManager} ],
   ChangeSecurity		=> [ 100,                    		$RequestParameters{Security} ],
   ChangeService		=> [ 149,                   		$RequestParameters{Service} ],
   ChangeStorageClass		=> [ 102,                     		$RequestParameters{StorageClass} ],
   ChangeSubscription		=> [ 178,                        	$RequestParameters{Subscription} ],
   ChangeTopic			=> [ 170,                 		$RequestParameters{Topic} ],

   ClearQueue			=> [ 9,              			$RequestParameters{Queue} ],
   ClearTopicString		=> [ 184,                       		$RequestParameters{ClearTopicString} ],

   CopyAuthInfo			=> [ 80,                    		$RequestParameters{AuthInfo} ],
   CopyCFStruc			=> [ 110,                  		$RequestParameters{CFStruc} ],
   CopyChannel			=> [ 22,                  		$RequestParameters{Channel} ],
   CopyChannelListener		=> [ 94,                   		$RequestParameters{Listener} ],
   CopyComminfo			=> [ 193,                   		$RequestParameters{Comminfo} ],
   CopyNamelist			=> [ 33,                   		$RequestParameters{Namelist} ],
   CopyProcess			=> [ 4,                   		$RequestParameters{Process} ],
   CopyQueue			=> [ 10,            			$RequestParameters{Queue} ],
   CopyService			=> [ 150,                 		$RequestParameters{Service} ],
   CopyStorageClass		=> [ 111,                   		$RequestParameters{StorageClass} ],
   CopySubscription		=> [ 181,                      		$RequestParameters{Subscription} ],
   CopyTopic			=> [ 171,               			$RequestParameters{Topic} ],

   CreateAuthInfo		=> [ 81,                      		$RequestParameters{AuthInfo} ],
   CreateCFStruc		=> [ 108,                    		$RequestParameters{CFStruc} ],
   # NOTE: CreateCFStruct is for backwards compatibility with pre-1.24 MQSC
   CreateCFStruct		=> [ 108,                    		$RequestParameters{CFStruct} ],
   CreateChannel		=> [ 23,                    		$RequestParameters{Channel} ],
   CreateNamelist		=> [ 34,                     		$RequestParameters{Namelist} ],
   CreateChannelListener	=> [ 95,                     		$RequestParameters{Listener} ],
   CreateComminfo		=> [ 190,                     		$RequestParameters{Comminfo} ],
   CreateProcess		=> [ 5,                     		$RequestParameters{Process} ],
   CreateQueue			=> [ 11,              			$RequestParameters{Queue} ],
   CreateService		=> [ 151,                   		$RequestParameters{Service} ],
   CreateStorageClass		=> [ 109,                     		$RequestParameters{StorageClass} ],
   CreateSubscription		=> [ 177,                        	$RequestParameters{Subscription} ],
   CreateTopic			=> [ 172,                 		$RequestParameters{Topic} ],

   DeleteAuthInfo		=> [ 82,                      		$RequestParameters{AuthInfo} ],
   DeleteAuthorityRecord	=> [ 89,                     		$RequestParameters{DeleteAuthorityRecord} ],
   DeleteCFStruc		=> [ 112,                    		$RequestParameters{CFStruc} ],
   # NOTE: DeleteCFStruct is for backwards compatibility with pre-1.24 MQSC
   DeleteCFStruct		=> [ 112,                    		$RequestParameters{CFStruct} ],
   DeleteChannel		=> [ 24,                    		$RequestParameters{Channel} ],
   DeleteComminfo		=> [ 194,                     		$RequestParameters{Comminfo} ],
   DeleteNamelist		=> [ 35,                     		$RequestParameters{Namelist} ],
   DeleteChannelListener	=> [ 96,                     		$RequestParameters{Listener} ],
   DeleteProcess		=> [ 6,                     		$RequestParameters{Process} ],
   DeleteQueue			=> [ 12,              			$RequestParameters{Queue} ],
   DeleteService		=> [ 152,                   		$RequestParameters{Service} ],
   DeleteStorageClass		=> [ 113,                     		$RequestParameters{StorageClass} ],
   DeleteSubscription		=> [ 179,                        	$RequestParameters{Subscription} ],
   DeleteTopic			=> [ 173,                 		$RequestParameters{Topic} ],

   Escape			=> [ 38,            			$RequestParameters{Escape} ],

   InquireAuthInfo		=> [ 83,                       		$RequestParameters{AuthInfo} ],
   InquireAuthInfoNames		=> [ 84,                             	$RequestParameters{AuthInfo} ],
   InquireAuthorityRecords	=> [ 87,                       		$RequestParameters{AuthorityRecords} ],
   InquireAuthorityService	=> [ 169,                         	$RequestParameters{AuthorityService} ],
   InquireCFStruc		=> [ 115,                     		$RequestParameters{CFStruc} ],
   InquireCFStrucNames		=> [ 147,                           	$RequestParameters{CFStruc} ],
   InquireCFStrucStatus		=> [ 116,                            	$RequestParameters{CFStruc} ],
   # NOTE: InquireCFStruct is for backwards compatibility with pre-1.24 MQSC
   InquireCFStruct		=> [ 115,                     		$RequestParameters{CFStruct} ],
   InquireCFStructNames		=> [ 147,                           	$RequestParameters{CFStruct} ],
   InquireChannel		=> [ 25,                     		$RequestParameters{Channel} ],
   InquireChlAuthRecs		=> [ 204,                         	$RequestParameters{ChlAuthRec} ],
   InquireChannelInitiator	=> [ 118,                         	$RequestParameters{ChannelInitiator} ],
   InquireChannelNames		=> [ 20,                           	$RequestParameters{Channel} ],
   InquireChannelStatus		=> [ 42,                            	$RequestParameters{ChannelStatus} ],
   InquireClusterQueueManager	=> [ 70,                           	$RequestParameters{Cluster} ],
   InquireConnection		=> [ 85,                        		$RequestParameters{Connection} ],
   InquireChannelListener	=> [ 97,                      		$RequestParameters{Listener} ],
   InquireChannelListenerStatus	=> [ 98,                             	$RequestParameters{ListenerStatus} ],
   InquireComminfo		=> [ 191,                      		$RequestParameters{Comminfo} ],
   InquireEntityAuthority	=> [ 88,                         	$RequestParameters{AuthorityRecords} ],
   InquireGroup			=> [ 119,                		$RequestParameters{InquireGroup} ],
   InquireLog			=> [ 120,                		$RequestParameters{Log} ],
   InquireNamelist		=> [ 36,                      		$RequestParameters{Namelist} ],
   InquireNamelistNames		=> [ 37,                            	$RequestParameters{Namelist} ],
   InquireProcess		=> [ 7,                      		$RequestParameters{Process} ],
   InquireProcessNames		=> [ 19,                           	$RequestParameters{Process} ],
   InquirePubSubStatus		=> [ 185,                          	$RequestParameters{PubSubStatus} ],
   InquireQueue			=> [ 13,               			$RequestParameters{Queue} ],
   InquireQueueManager		=> [ 2,                    		$RequestParameters{QueueManager} ],
   InquireQueueManagerStatus	=> [ 161,                               $RequestParameters{QueueManagerStatus} ],
   InquireQueueNames		=> [ 18,                     		$RequestParameters{Queue} ],
   InquireQueueStatus		=> [ 41,                      		$RequestParameters{QueueStatus} ],
   InquireSecurity		=> [ 121,                     		$RequestParameters{Security} ],
   InquireService		=> [ 153,                    		$RequestParameters{Service} ],
   InquireServiceStatus		=> [ 154,                           	$RequestParameters{ServiceStatus} ],
   InquireStorageClass		=> [ 122,                      		$RequestParameters{StorageClass} ],
   InquireStorageClassNames	=> [ 148,                            	$RequestParameters{StorageClass} ],
   InquireSubscription		=> [ 176,                         	$RequestParameters{Subscription} ],
   InquireSubscriptionStatus	=> [ 182,                       		$RequestParameters{SubscriptionStatus} ],
   InquireSystem		=> [ 123,                   		$RequestParameters{System} ],
   InquireTopic			=> [ 174,                  		$RequestParameters{Topic} ],
   InquireTopicNames		=> [ 175,                        	$RequestParameters{Topic} ],
   InquireTopicStatus		=> [ 183,                         	$RequestParameters{TopicStatus} ],
   InquireUsage			=> [ 126,                  		$RequestParameters{InquireUsage} ],

   MoveQueue			=> [ 127,           			$RequestParameters{Queue} ],

   PingChannel			=> [ 26,                  		$RequestParameters{Channel} ],
   PingQueueManager		=> [ 40,                			$RequestParameters{QueueManager} ],

   RecoverCFStruc		=> [ 129,                     		$RequestParameters{RecoverCFStruc} ],

   RefreshCluster		=> [ 73,                     		$RequestParameters{Cluster} ],
   RefreshQueueManager		=> [ 16,                   		$RequestParameters{RefreshQueueManager} ],
   RefreshSecurity		=> [ 78,                      		$RequestParameters{RefreshSecurity} ],

   ResetChannel			=> [ 27,                   		$RequestParameters{Channel} ],
   ResetCluster			=> [ 74,                   		$RequestParameters{Cluster} ],
   ResetQueueManager		=> [ 92,                 		$RequestParameters{QueueManager} ],
   ResetQueueStatistics		=> [ 17,                   		$RequestParameters{Queue} ],

   ResolveChannel		=> [ 39,                     		$RequestParameters{Channel} ],

   ResumeQueueManager		=> [ 132,                 		$RequestParameters{QueueManager} ],
   ResumeQueueManagerCluster	=> [ 71,                          	$RequestParameters{Cluster} ],

   ReverifySecurity		=> [ 133,                      		$RequestParameters{ReverifySecurity} ],

   SetAuthorityRecord		=> [ 90,                  		$RequestParameters{SetAuthorityRecord} ],
   SetChlAuthRec		=> [ 203,                    		$RequestParameters{ChlAuthRec} ],
   SetLog			=> [ 136,            			$RequestParameters{Log} ],
   SetSystem			=> [ 137,               			$RequestParameters{System} ],

   StartChannel			=> [ 28,                   		$RequestParameters{Channel} ],
   StartChannelInitiator	=> [ 30,                        		$RequestParameters{Channel} ],
   StartChannelListener		=> [ 31,                            	$RequestParameters{Listener} ],
   StartService			=> [ 155,                  		$RequestParameters{Service} ],

   StopChannel			=> [ 29,                  		$RequestParameters{Channel} ],
   StopChannelInitiator		=> [ 141,                      		$RequestParameters{Channel} ],
   StopChannelListener		=> [ 142,                          	$RequestParameters{Listener} ],
   StopConnection		=> [ 86,                     		$RequestParameters{Connection} ],
   StopService			=> [ 156,                 		$RequestParameters{Service} ],

   SuspendQueueManager		=> [ 146,                  		$RequestParameters{QueueManager} ],
   SuspendQueueManagerCluster	=> [ 72,                           	$RequestParameters{Cluster} ],

   #
   # Extended command set
   #
   InquireAuthority		=> [ 1000,                      		$RequestParameters{MorganAuthority} ],
   ChangeAuthority		=> [ 1001,                     		$RequestParameters{MorganAuthority} ],

  );

1;
