#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/ResponseValues.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%ResponseValues =
  (

   Platform =>
   {
    MVS				=> 1,
    NSK				=> 13,
    OS2				=> 2,
    OS400			=> 4,
    UNIX			=> 3,
    Win16			=> 5,
    Win32			=> 11,
   },

   QType =>
   {
    Alias			=> 3,
    Cluster			=> 7,
    Local			=> 1,
    Model			=> 2,
    Remote			=> 6,
   },

   BaseType =>
   {
    Queue			=> 1,
    Topic			=> 8,
   },

   DefInputOpenOption =>
   {
    Exclusive			=> 4,
    Shared			=> 2,
   },

   #
   # Pub/Sub Message Delivery
   #
   MsgDelivery =>
   {
    All				=> 1,
    AllAvailable		=> 3,
    AllDurable			=> 2,
    AsParent			=> 0,
   },

   MsgDeliverySequence =>
   {
    FIFO			=> 1,
    Priority			=> 0,
   },

   DefinitionType =>
   {
    Permanent			=> 2,
    Predefined			=> 1,
    Temporary			=> 3,
   },

   Usage =>
   {
    Normal			=> 0,
    XMITQ			=> 1,
   },

   TriggerType =>
   {
    Depth			=> 3,
    Every			=> 2,
    First			=> 1,
    None			=> 0,
   },

   Scope =>
   {
    Cell			=> 2,
    QMgr			=> 1,
   },

   QServiceIntervalEvent =>
   {
    High			=> 1,
    None			=> 0,
    OK				=> 2,
   },

   ChannelType =>
   {
    Clntconn			=> 6,
    ClusterReceiver		=> 8,
    ClusterSender		=> 9,
    Receiver			=> 3,
    Requester			=> 4,
    Sender			=> 1,
    Server			=> 2,
    Svrconn			=> 7,
    Telemetry			=> 10,
   },

   ChannelInstanceType =>
   {
    Current			=> 1011,
    Saved			=> 1012,
   },

   MCAStatus =>
   {
    Running			=> 3,
    Stopped			=> 0,
   },

   TransportType =>
   {
    DECnet			=> 5,
    LU62			=> 1,
    NetBIOS			=> 3,
    SPX				=> 4,
    TCP				=> 2,
    UDP				=> 6,
   },

   PutAuthority =>
   {
    Context			=> 2,
    Default			=> 1,
   },

   MCAType =>
   {
    Process			=> 1,
    Thread			=> 2,
   },

   NonPersistentMsgClass =>
   {
    High			=> 10,
    Normal			=> 0,
   },

   NonPersistentMsgSpeed =>
   {
    Fast			=> 2,
    Normal			=> 1,
   },

   DefReconnect =>
   {
    QMgr 			=> 2,
    Disabled			=> 3,
    No				=> 0,
    Yes				=> 1,
   },

   UseDLQ =>
   {
    No				=> 1,
    Yes				=> 2,
   },

   TopicUseDLQ =>
   {
    AsParent			=> 0,
    No				=> 1,
    Yes				=> 2,
   },

   ChannelStatus =>
   {
    Binding			=> 1,
    Inactive			=> 0,
    Initializing		=> 13,
    Paused			=> 8,
    Requesting			=> 7,
    Retrying			=> 5,
    Running			=> 3,
    Starting			=> 2,
    Stopped			=> 6,
    Stopping			=> 4,
   },

   ChlAuthAction =>
   {
    Add				=> 5,
    Replace			=> 6,
    Remove			=> 7,
    RemoveAll			=> 8,
   },

   ChlAuthType =>
   {
    BlockUser			=> 1,
    BlockAddress		=> 2,
    SSLPeerMap			=> 3,
    AddressMap			=> 4,
    UserMap			=> 5,
    QMgrMap			=> 6,
   },

#   ChlAuthRecords =>
#   {
#    Disabled			=> 0,
#    Enabled			=> 1,
#   },

   UserSource =>
   {
    Channel			=> 2,
    Map				=> 0,
    NoAccess			=> 1,
   },

#   ChlAuthWarning =>
#   {
#    No				=> 0,
#    Yes				=> 1,
#   },

   ApplType =>
   {
    CHINIT			=> 30,
    CICS			=> 1,
    DOS				=> 5,
    IMS				=> 3,
    MVS				=> 2,
    NSK				=> 13,
    OS2				=> 4,
    OS400			=> 8,
    QMGR			=> 7,
    SystemExtension		=> 35,
    UNIX			=> 6,
    USER			=> 25,
    VMS				=> 12,
    Win16			=> 9,
    Win32			=> 11,
   },

   EscapeType =>
   {
    MQSC			=> 1,
   },

   QMgrDefinitionType =>
   {
    AutoClusterSender		=> 2,
    AutoExplicitClusterSender	=> 4,
    ClusterReceiver		=> 3,
    ExplicitClusterSender	=> 1,
   },

   QMgrType =>
   {
    Normal			=> 0,
    Repository			=> 1,
   },

   ClusterQType =>
   {
    Alias			=> 2,
    Local			=> 1,
    QMgrAlias			=> 4,
    Remote			=> 3,
   },

   DefBind =>
   {
    NotFixed			=> 1,
    OnOpen			=> 0,
    OnGroup			=> 2,
   },

   ObjectType =>
   {
    AuthInfo			=> 7,
    Listener			=> 11,
    Namelist			=> 2,
    Process			=> 3,
    Queue			=> 1,
    QueueManager		=> 5,
    Service			=> 12,
    Topic			=> 8,

    Channel			=> 6,

    All				=> 1001,
    AliasQueue			=> 1002,
    ModelQueue			=> 1003,
    LocalQueue			=> 1004,
    RemoteQueue			=> 1005,

    SenderChannel		=> 1007,
    ServerChannel		=> 1008,
    RequesterChannel		=> 1009,
    ReceiverChannel		=> 1010,
    CurrentChannel		=> 1011,
    SavedChannel		=> 1012,
    SvrconnChannel		=> 1013,
    ClntconnChannel		=> 1014,
    CFStruc			=> 10,
    ChlAuth			=> 1016,
    StorageClass		=> 4,
   },

   #
   # New with WebSphere MQ 5.3
   #
   AuthInfoType =>
   {
    CRLLDAP			=> 1,
    OCSP			=> 2,            # new with v7.0.1.1
    All				=> 0,
   },

   OpenType =>
   {
    All				=> 1,
    Input			=> 2,
    Output			=> 3,
   },

   QStatusInputType =>
   {
    Exclusive			=> 2,
    No				=> 0,
    Shared			=> 1,
   },

   QStatusType =>
   {
    Queue			=> 1105,
    Handle			=> 1104,
   },

   SSLClientAuth =>
   {
    Optional			=> 1,
    Required			=> 0,
   },

   #
   # New with MQv6
   #
   AdoptNewMCACheck =>
   {
    All				=> 1,
    NetworkAddress		=> 4,
    None			=> 0,
    QMgrName			=> 2,
   },

   AdoptNewMCAType =>
   {
    All				=> 1,
    No				=> 0,
   },

   #
   # Authority (MQ v6 on distributed platforms)
   #
   Authority =>
   {
    All				=> -1,
    AllAdmin			=> -2,
    AllMqi			=> -3,
    Control			=> 17,
    ControlExtended		=> 18,
    AltUser			=> 1,
    Browse			=> 2,
    Change			=> 3,
    Clear			=> 4,
    Connect			=> 5,
    Create			=> 6,
    Delete			=> 7,
    Display			=> 8,
    Input			=> 9,
    Inquire			=> 10,
    None			=> 0,
    Output			=> 11,
    PassAllContext		=> 12,
    PassIdentityContext		=> 13,
    Publish			=> 19,
    Resume			=> 21,
    Set				=> 14,
    SetAllContext		=> 15,
    SetIdentityContext		=> 16,
    Subscribe			=> 20,
    System			=> 22,
   },

    AsynchronousState          =>
   {
    Active			=> 6,
    Inactive			=> 7,
    Started			=> 1,
    StartWait			=> 2,
    Stopped			=> 3,
    Suspended			=> 4,
    SuspendedTemporary		=> 5,
    None   			=> 0,
   },
   #
   # Unit of Recovery Disposition (V7)
   #
   URDisposition =>
   {
    All				=> -1,
    Group			=> 3,
    QMgr			=> 0,
   },

   ChannelDisposition =>
   {
    All				=> -1,
    Private			=> 4,
    Shared			=> 2,
    Fixshared			=> 5,
   },

   ChannelInitiatorControl =>
   {
    Manual			=> 2,
    QMgr			=> 0,
   },

   ChannelEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    Exception			=> 2,
   },

   QMgrChannelMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None			=> -1,
    Off				=> 0,
   },

   QMgrChannelStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None			=> -1,
    Off				=> 0,
   },

   ChannelStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   ChannelMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   ChannelSubState =>
   {
    ChannelAutoDefinitionExit	=> 1200,
    Compressing			=> 1800,
    EndOfBatch			=> 100,
    HeartBeating		=> 600,
    ExecutingMQICall		=> 1700,
    MessageExit			=> 1000,
    NameServerRequest		=> 1400,
    NetworkConnect		=> 1250,
    NetworkReceive		=> 300,
    NetworkSend			=> 200,
    Other			=> 0,
    PerformingMQGET		=> 1600,
    PerformingMQPUT		=> 1500,
    ReceiveExit			=> 800,
    Resynching			=> 500,
    RetryExit			=> 1100,
    SecurityExit		=> 700,
    SendExit			=> 900,
    Serializing			=> 400,
    SSLHandshaking		=> 1300,
   },

   CommandEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    NoDisplay			=> 3,
   },

   #
   # Channel Connection Affinity (MQ v7)
   #
   ConnectionAffinity =>
   {
    None			=> 0,
    Preferred			=> 1,
   },

   ClusterSenderMonitoringDefault =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   ClusterSenderStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   #
   # Default Put Response Type (MQ v7)
   #
   DefPutResponse =>
   {
    AsParent			=> 0,
    Async			=> 2,
    Sync			=> 1,
   },

   #
   # Default Read Ahead (MQ v7)
   #
   DefReadAhead =>
   {
    Disabled			=> 2,
    No				=> 0,
    Yes				=> 1,
   },

   #
   # Destination Class for Subscriptions in MQ v7
   #
   DestinationClass =>
   {
    Managed			=> 1,
    Provided			=> 2,
   },

   #
   # Durable Pub/Sub Subscriptions for MQ v7 (for topic object)
   #
   TopicDurableSubscriptions =>
   {
    AsParent			=> 0,
    Durable			=> 1,
    NonDurable			=> 2,
   },

   #
   # Durable Pub/Sub Subscriptions for MQ v7 (for topicstatus object)
   #
   TopicStatusDurableSubscriptions =>
   {
    Allowed			=> 1,
    Inhibited			=> 2,
   },

   #
   # Durable Pub/Sub Subscriptions for MQ v7 (for subscription object)
   #
   Durable =>
   {
    No				=> 2,
    Yes				=> 1,
   },

   #
   # EntityType is for InquireAuthorityRecords (MQ v6 on distributed)
   #
   EntityType =>
   {
    Group			=> 2,
    Principal			=> 1,
    Unknown			=> 3,
   },

   HeaderCompression =>
   {
    None			=> 0,
    System			=> 8,
   },

   IGQPutAuthority =>
   {
    AltIGQ			=> 4,
    Context			=> 2,
    Default			=> 1,
    OnlyIGQ			=> 3,
   },

   IndexType =>
   {
    CorrelId			=> 2,
    GroupId			=> 5,
    MsgId			=> 1,
    MsgToken			=> 4,
    None			=> 0,
   },

   #
   # Pub/Sub Topics on MQ v7
   #
   InhibitPublications =>
   {
    Allowed			=> 2,
    AsParent			=> 0,
    Inhibited			=> 1,
   },

   #
   # Pub/Sub Topics on MQ v7
   #
   InhibitSubscriptions =>
   {
    Allowed			=> 2,
    AsParent			=> 0,
    Inhibited			=> 1,
   },

   IPAddressVersion =>
   {
    IPv4			=> 0,
    IPv6			=> 1,
   },

   # VALUEMAP-CODEREF
   KeepAliveInterval =>
        sub { return MQSeries::Command::Base::strinteger(@_, -1,
                                                    "AUTO"); },

   # VALUEMAP-CODEREF
   MsgMarkBrowseInterval =>
        sub { return MQSeries::Command::Base::strinteger(@_, -1,
                                                    "NOLIMIT"); },

   # VALUEMAP-CODEREF
   MaxPropertiesLength =>
        sub { return MQSeries::Command::Base::strinteger(@_, -1,
                                                    "NOLIMIT"); },

   # VALUEMAP-CODEREF
   ComminfoCCSID =>
        sub { return MQSeries::Command::Base::strinteger(@_, -4,
                                                    "ASPUB"); },

   ListenerStartMode =>
   {
    Manual			=> 2,
    QMgr			=> 0,
    QMgrStart			=> 1,
   },

   ListenerStatus =>
   {
    Running			=> 2,
    Starting			=> 1,
    Stopping			=> 3,
   },

   ListenerTransportType =>
   {
    TCP				=> 2,
    LU62			=> 1,
    NetBIOS			=> 3,
    SPX				=> 4,
   },

   MessageCompression =>
   {
    Any				=> 268435455,
    None			=> 0,
    RLE				=> 1,
    ZlibFast			=> 2,
    ZlibHigh			=> 4,
   },

   #
   # Property Control (MQ v7)
   #
   PropertyControl =>
   {
    All				=> 2,
    Compatibility		=> 0,
    ForceRFH2			=> 3,
    V6Compat			=> 4,
    None			=> 1,
   },

   #
   # Proxy Subscriptions (Topic for MQ v7)
   #
   ProxySubscriptions =>
   {
    FirstUse			=> 2,
    Force			=> 1,
   },

#   PubSubClus =>
#   {
#    Disabled			=> 0,
#    Enabled			=> 1,
#   },

   #
   # PublishPriority for
   #
   PublishPriority =>
   {
    AsPublished			=> -3,
    AsQDef			=> -1,
    0				=> 0,
    1				=> 1,
    2				=> 2,
    3				=> 3,
    4				=> 4,
    5				=> 5,
    6				=> 6,
    7				=> 7,
    8				=> 8,
    9				=> 9,
   },

   #
   # Pub/Sub properties for Subscription on MQ v7
   #
   PubSubProperties =>
   {
    Compat			=> 1,
    MsgProp			=> 3,
    None			=> 0,
    RFH2			=> 2,
   },

   #
   # Pub/Sub scope for Topic on MQ v7
   #
   PubSubScope =>
   {
    All				=> 0,
    AsParent			=> 1,
    QMgr			=> 4,
   },

   #
   # Pub/Sub mode
   #
   PubSubMode =>
   {
    Compat			=> 1,
    Disabled			=> 0,
    Enabled			=> 2,
   },

   #
   # Pub/Sub undelivered input messages
   #
   PubSubNPInputMsg =>
   {
    Discard			=> 2,
    Keep			=> 3,
   },

   #
   # Pub/Sub undelivered response messages
   #
   PubSubNPResponse =>
   {
    Discard			=> 2,
    Keep			=> 3,
    Normal			=> 0,
    Safe			=> 1,
   },

   #
   # Pub/Sub syncpoint
   #
   PubSubSyncPoint =>
   {
    IfPersistent		=> 1,
    Yes				=> 0,
   },

   #
   # Subscription request Only
   #
   RequestOnly =>
   {
    All				=> 2,
    OnRequest			=> 1,
   },

   QMgrChlMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None			=> -1,
    Off				=> 0,
   },

   QMgrClusterMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   QMgrMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None			=> -1,
    Off				=> 0,
   },

   QueueMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   QMgrQueueStatistics =>
   {
    Off				=> 0,
    On				=> 1,
    None			=> -1,
   },

   QueueStatistics =>
   {
    Off				=> 0,
    On				=> 1,
    QMgr			=> -3,
   },

   MonitoringDft =>
   {
    Off				=> 0,
    QMgr			=> -3,
    Low				=> 17,
    Medium			=> 33,
    High			=> 65,
   },

   NamelistType =>
   {
    AuthInfo			=> 4,
    Cluster			=> 2,
    None			=> 0,
    Queue			=> 1,
   },

   SharedQQMgrName =>
   {
    Ignore			=> 1,
    Use				=> 0,
   },

   QMgrCLWLUseQ =>		# QMgr-level
   {
    Any				=> 1,
    Local			=> 0,
   },

   CommandServerControl =>
   {
    Manual			=> 2,
    QMgr			=> 0,
   },

   QMgrServiceStatus =>
   {
    Starting			=> 1,
    Running			=> 2,
    Stopped			=> 0,
    Stopping			=> 3,
   },

   QMgrStatus =>
   {
    Starting			=> 1,
    Running			=> 2,
    Quiescing			=> 3,
   },

   QueueCLWLUseQ =>		# Queue-level
   {
    Any				=> 1,
    Local			=> 0,
    QMgr			=> -3,
   },

   QueueAccounting =>
   {
    On			       => 1,
    Off			       => 0,
    QMgr		       => -3,
   },

   QMgrAccounting =>		# QMgr-level QueueAccounting
   {
    None		       => -1,
    On			       => 1,
    Off			       => 0,
   },

   QSharingGroupDisposition =>
   {
    Copy			=> 1,
    Group			=> 3,
    QMgr			=> 0,
    Shared			=> 2,
   },

   QSGDisposition =>
   {
    Copy			=> 1,
    Group			=> 3,
    QMgr			=> 0,
    Shared			=> 2,
   },

   ReceiveTimeoutType =>
   {
    Add				=> 1,
    Equal			=> 2,
    Multiply			=> 0,
   },

   ActivityRecording =>
   {
    Disabled			=> 0,
    Msg				=> 2,
    Queue			=> 1,
   },

   SecurityCase =>
   {
    Mixed			=> 1,
    Upper			=> 0,
   },

   SecuritySwitch =>
   {
    AlternateUser		=> 7,
    Command			=> 8,
    CommandResource		=> 11,
    Connection			=> 9,
    Context			=> 6,
    Namelist			=> 2,
    QMgr			=> 15,
    QSG				=> 16,
    Queue			=> 3,
    Process			=> 1,
    Subsystem			=> 10,
    Topic			=> 4,
   },

   SecuritySwitchSetting =>
   {
    OffError			=> 25,
    OffFound			=> 21,
    OffNotFound			=> 23,
    OnFound			=> 22,
    OnNotFound			=> 24,
    OnOverridden		=> 26,
   },

   ServiceStartMode =>
   {
    Manual			=> 2,
    QMgr			=> 0,
    QMgrStart			=> 1,
   },

   ServiceStatus =>
   {
    Running			=> 2,
    Starting			=> 1,
    Stopping			=> 3,
   },

   ServiceType =>
   {
    Command			=> 0,
    Server			=> 1,
   },

   #
   # Pub/Sub scope for Subscription on MQ v7
   #
   SubscriptionScope =>
   {
    All				=> 2,
    QMgr			=> 1,
   },

   SubscriptionType =>
   {
    Admin			=> 2,
    API				=> 1,
    Proxy			=> 3,
   },

   TCPStackType =>
   {
    Multiple			=> 1,
    Single			=> 0,
   },

   TopicDefPersistence =>
   {
    AsParent			=> -1,
    NonPersistent		=> 0,
    Persistent			=> 1,
   },

   TopicType =>
   {
    Cluster			=> 1,
    Local			=> 0,
   },

   TraceRouteRecording =>
   {
    Disabled			=> 0,
    Msg				=> 2,
    Queue			=> 1,
   },

   #
   # The UsageXXX hashes are for the 'InquireUsage' command for MQ on z/OS
   #
   UsageType =>
   {
    BufferPool			=> 1170,
    DataSet			=> 1169,
    Pageset			=> 1168,
    SMDS			=> 1335,
   },

   UsageDataSetType =>
   {
    OldestActiveUOW		=> 10,
    OldestCFRecovery		=> 12,
    OldestPSRecovery		=> 11,
   },

   UsageExpandType =>
   {
    None			=> 3,
    User			=> 1,
    System			=> 2,
   },

   UsagePageSetStatus =>
   {
    Available			=> 0,
    Defined			=> 1,
    NotDefined			=> 3,
    Offline			=> 2,
   },

   #
   # For Topic on MQ v7
   #
   WildcardOperation =>
   {
    Block			=> 1,
    Passthru			=> 2,
   },

   RetainedPublication =>
   {
    Yes				=> 1,
    No				=> 0,
   },

   #
   # For CFStruc on V6
   CFStatusType =>
   {
    CFStatusSummary		=> 1136,
    CFStatusConnect		=> 1137,
    CFStatusBackup		=> 1138,
    CFStatusSMDS		=> 1333,
   },

   CFStrucStatus =>
   {
    Active			=> 1,
    Failed			=> 4,
    NotFound			=> 0,
    InBackup			=> 3,
    InRecover			=> 2,
    Unknown			=> 6,
    None			=> 5,
    Recovered			=> 7,
    Empty			=> 8,
    New				=> 9,
   },

   CFStrucType =>
   {
    Admin			=> 1,
    Appl			=> 0,
   },

   CFStrucAccess =>
   {
    Enabled			=> 0,
    Disabled			=> 2,
    Suspended			=> 1,
   },

   DSBlock =>
   {
    "8K"                          => 1,
    "16K"                         => 2,
    "32K"                         => 3,
    "64K"                         => 4,
    "128K"                        => 5,
    "256K"                        => 6,
    "512K"                        => 7,
    "1024K"                       => 8,
    "1M"                          => 8,
   },

   CFConlos =>
   {
    AsQMgr                      => 2,
    Terminate                   => 0,
    Tolerate                    => 1,
   },

   EncryptionPolicySuiteB =>
   {
    None			=> 1,
    "128Bit"			=> 2,
    "192Bit"			=> 4,
   },

   Offload =>
   {
    DB2                         => 2,
    SMDS                        => 1,
    None                        => 0,
    Both                        => 3,
   },

   DSExpand =>
   {
    Yes                         => 1,
    No                          => 2,
    Default                     => 0,
   },

   #
   # For Inquire Connection in V6
   #
   ConnInfoType =>
   {
    Conn			=> 1111,
    Handle			=> 1112,
    All				=> 1113
    },

   HandleObjectType =>
   {
    Queue		       => 1,
    Process		       => 3,
    Namelist		       => 2,
    QMgr		       => 5,
    Channel		       => 6,
    AuthInfo		       => 7,
 #   Topic		       => 8,            # FIXME:do we need this in HandleObjectType?
    },

   HandleQSGDisposition =>
   {
    Copy		      => 1,
    QMgr		      => 0,
    Shared		      => 2,
   },

   ConnApplType =>
   {
    QMgr		      => 7,
    ChannelInitiator	      => 30,
    User		      => 25,
    Batch		      => 32,
    RRSBatch		      => 33,
    CICS		      => 1,
    IMS			      => 3,
    SystemExtension	      => 35,
   },

   HandleState =>
   {
    Active		       => 1,
    Inactive		       => 0,
    },

   UOWState =>
   {
    None			=> 0,
    Active			=> 1,
    Prepared			=> 2,
    Unresolved			=> 3,
   },

   UOWType =>
   {
    QMgr			=> 0,
    CICS			=> 1,
    RRS				=> 2,
    IMS				=> 3,
    XA				=> 4,
   },

   #
   # On z/os, v7, GroupUR
   #
   GroupUR =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
   },

   #
   # InquireGroup to query about QSG via a qmgr
   #
   QSGStatus =>
   {
    Active			=> 2,
    Created			=> 1,
    Inactive			=> 3,
    Failed			=> 4,
    Pending			=> 5,
    Unknown			=> 0,
   },

   CommandInformation =>
   {
    DB2ObsoleteMsgs		=> 20,
   },

   #
   # InquireLog for z/OS
   #
   OffLoadStatus =>
   {
    AllocatingArchive		=> 34,
    Available			=> 32,
    CopyingBSDS			=> 35,
    CopyingLog			=> 36,
    Busy			=> 30,
   },

   #
   #  v7 stuff on z/os
   #
   LogCompression =>
   {
    None			=> 0,
    RLE				=> 1,
    Any				=> 268435455,
   },

   #
   # InquireSystem for z/OS
   #
   ParameterType =>
   {
    Initial			=> 10,
    Set				=> 11,
   },

   ClusterCacheType =>
   {
    Static			=> 0,
    Dynamic			=> 1,
   },

   #
   # V7 on z/os
   #
   MULCCapture =>
   {
    Standard			=> 0,
    Refined			=> 1,
   },

   SelectorType =>
   {
    None			=> 0,
    Standard			=> 1,
    Extended			=> 2,
   },

   #
   # Variable Userid for Subscriptions in MQ v7
   #
   VariableUser =>
   {
    Any				=> 2,
    Fixed			=> 1,
   },

   #
   # Wildcard Schema for Subscriptions in MQ v7
   #
   WildcardSchema =>
   {
    Character			=> 1,
    Topic			=> 2,
   },

   WLMIntervalUnits =>
   {
    Seconds			=> 1,
    Minutes			=> 0,
   },

   #
   # Type for Inquire PubSubStatus in MQ V7
   #
   PubSubStatusType =>
   {
    Child			=> 3,
    Local			=> 1,
    Parent			=> 2,
   },

   #
   # PubSubStatus for Inquire PubSubStatus in MQ V7
   #
   PubSubStatus =>
   {
    Active			=> 3,
    Compat			=> 4,
    Error			=> 5,
    Inactive			=> 0,
    Starting			=> 1,
    Stopping			=> 2,
    Active			=> 3,
    Refused			=> 6,
   },

   #
   # Comminfo Encoding
   #
   Encoding =>
   {
    AsPublished                 => -1,
    Normal                      => 273,
    Reversed                    => 546,
    S390                        => 785,
    TNS                         => 1041,
   },

   #
   # Comminfo ComminfoType
   # Currently only supported type is Multicast.
   #
   ComminfoType =>
   {
    Multicast                   => 1,
   },

   #
   # Comminfo CommEvent
   #
   CommEvent =>
   {
    Disabled                    => 0,
    Enabled                     => 1,
    Exception                   => 2,
   },

   #
   # Comminfo NewSubHistory
   #
   NewSubHistory =>
   {
    None                        => 0,
    All                         => -1,
   },

   #
   # Comminfo MulticastPropControl
   #
   MulticastPropControl =>
   {
    All                         => -1,
    Reply                       => 2,
    User                        => 1,
    None                        => 0,
    Compat                      => -2,
   },

   #
   # Used with the Morgan Stanley extended Authority commands
   #
   MorganEntityType =>
   {
    Principal			=> 1000,
    Group			=> 1001,
    AFS				=> 1002,
   },

  );

1;
