#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/Responses.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2012 Morgan Stanley & Co. Incorporated
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%Responses =
  (
   Error				=> [ "Error",				$ResponseParameters{Error} ],
   None					=> [ 0,           			$ResponseParameters{Error} ],

   ChangeAuthInfo			=> [ 79,                      		$ResponseParameters{AuthInfo} ],
   ChangeCFStruc			=> [ 101,                    		$ResponseParameters{CFStruc} ],
   # NOTE: ChangeCFStruct is for backwards compatibility with pre-1.24 MQSC
   ChangeCFStruct			=> [ 101,                    		$ResponseParameters{CFStruct} ],
   ChangeChannel			=> [ 21,                    		$ResponseParameters{Channel} ],
   ChangeChannelListener		=> [ 93,                     		$ResponseParameters{Listener} ],
   ChangeComminfo			=> [ 192,                     		$ResponseParameters{Comminfo} ],
   ChangeNamelist			=> [ 32,                     		$ResponseParameters{Namelist} ],
   ChangeProcess			=> [ 3,                     		$ResponseParameters{Process} ],
   ChangeQueue				=> [ 8,               			$ResponseParameters{Queue} ],
   ChangeQueueManager			=> [ 1,                   		$ResponseParameters{QueueManager} ],
   ChangeService			=> [ 149,                   		$ResponseParameters{Service} ],
   ChangeStorageClass			=> [ 102,                     		$ResponseParameters{StorageClass} ],
   ChangeSubscription			=> [ 178,                        	$ResponseParameters{Subscription} ],
   ChangeTopic				=> [ 170,                 		$ResponseParameters{Topic} ],

   ClearQueue				=> [ 9,              			$ResponseParameters{Queue} ],

   CopyAuthInfo				=> [ 80,                    		$ResponseParameters{AuthInfo} ],
   CopyChannel				=> [ 22,                  		$ResponseParameters{Channel} ],
   CopyChannelListener			=> [ 94,                   		$ResponseParameters{Listener} ],
   CopyComminfo				=> [ 193,                   		$ResponseParameters{Comminfo} ],
   CopyNamelist				=> [ 33,                   		$ResponseParameters{Namelist} ],
   CopyProcess				=> [ 4,                   		$ResponseParameters{Process} ],
   CopyQueue				=> [ 10,            			$ResponseParameters{Queue} ],
   CopyService				=> [ 150,                 		$ResponseParameters{Service} ],
   CopyStorageClass			=> [ 111,                   		$ResponseParameters{StorageClass} ],
   CopySubscription			=> [ 181,                      		$ResponseParameters{Subscription} ],
   CopyTopic				=> [ 171,               			$ResponseParameters{Topic} ],

   CreateAuthInfo			=> [ 81,                      		$ResponseParameters{AuthInfo} ],
   CreateCFStruc			=> [ 108,                    		$ResponseParameters{CFStruc} ],
   # NOTE: ChangeCFStruct is for backwards compatibility with pre-1.24 MQSC
   CreateCFStruct			=> [ 108,                    		$ResponseParameters{CFStruct} ],
   CreateChannel			=> [ 23,                    		$ResponseParameters{Channel} ],
   CreateChannelListener		       => [ 95,                     	       $ResponseParameters{Listener} ],
   CreateComminfo			=> [ 190,                     		$ResponseParameters{Comminfo} ],
   CreateNamelist			=> [ 34,                     		$ResponseParameters{Namelist} ],
   CreateProcess			=> [ 5,                     		$ResponseParameters{Process} ],
   CreateQueue				=> [ 11,              			$ResponseParameters{Queue} ],
   CreateService			=> [ 151,                   		$ResponseParameters{Service} ],
   CreateStorageClass			=> [ 109,                     		$ResponseParameters{StorageClass} ],
   CreateSubscription			=> [ 177,                        	$ResponseParameters{Subscription} ],
   CreateTopic				=> [ 172,                 		$ResponseParameters{Topic} ],

   DeleteAuthInfo			=> [ 82,                      		$ResponseParameters{AuthInfo} ],
   DeleteAuthorityRecord		=> [ 89,                     		$ResponseParameters{AuthorityRecord} ],
   DeleteCFStruc			=> [ 112,                    		$ResponseParameters{CFStruc} ],
   # NOTE: ChangeCFStruct is for backwards compatibility with pre-1.24 MQSC
   DeleteCFStruct			=> [ 112,                    		$ResponseParameters{CFStruct} ],
   DeleteChannel			=> [ 24,                    		$ResponseParameters{Channel} ],
   DeleteChannelListener		       => [ 96,                     	       $ResponseParameters{Listener}],
   DeleteComminfo			=> [ 194,                     		$ResponseParameters{Comminfo} ],
   DeleteNamelist			=> [ 35,                     		$ResponseParameters{Namelist} ],
   DeleteProcess			=> [ 6,                     		$ResponseParameters{Process} ],
   DeleteQueue				=> [ 12,              			$ResponseParameters{Queue} ],
   DeleteService			=> [ 152,                   		$ResponseParameters{Service} ],
   DeleteStorageClass			=> [ 113,                     		$ResponseParameters{StorageClass} ],
   DeleteSubscription			=> [ 179,                        	$ResponseParameters{Subscription} ],
   DeleteTopic				=> [ 173,                 		$ResponseParameters{Topic} ],

   Escape				=> [ 38,            			$ResponseParameters{Escape} ],

   InquireAuthInfo			=> [ 83,                       		$ResponseParameters{AuthInfo} ],
   InquireAuthInfoNames			=> [ 84,                             	$ResponseParameters{AuthInfo} ],
   InquireAuthorityRecords		=> [ 87,                       		$ResponseParameters{AuthorityRecord} ],
   InquireAuthorityService		=> [ 169,                         	$ResponseParameters{AuthorityService} ],
   InquireCFStruc			=> [ 115,                     		$ResponseParameters{CFStruc} ],
   InquireCFStrucNames			=> [ 147,                           	$ResponseParameters{CFStruc} ],
   InquireCFStrucStatus			=> [ 116,                            	$ResponseParameters{CFStruc} ],
   # NOTE: InquireCFStruct is for backwards compatibility with pre-1.24 MQSC
   InquireCFStruct			=> [ 115,                     		$ResponseParameters{CFStruct} ],
   InquireCFStructNames			=> [ 147,                           	$ResponseParameters{CFStruct} ],
   InquireChannel			=> [ 25,                     		$ResponseParameters{Channel} ],
   InquireChlAuthRecs			=> [ 204,                         	$ResponseParameters{ChlAuthRec} ],
   InquireChannelInitiator		=> [ 118,                         	$ResponseParameters{ChannelInitiator} ],
   InquireComminfo			=> [ 191,                      		$ResponseParameters{Comminfo} ],
   InquireChannelNames			=> [ 20,                           	$ResponseParameters{Channel} ],
   InquireChannelStatus			=> [ 42,                            	$ResponseParameters{ChannelStatus} ],
   InquireConnection			=> [ 85,                        		$ResponseParameters{Connection} ],
   InquireClusterQueueManager		=> [ 70,                           	$ResponseParameters{Cluster} ],
   InquireChannelListener		=> [ 97,                      		$ResponseParameters{Listener} ],
   InquireChannelListenerStatus		=> [ 98,                             	$ResponseParameters{ListenerStatus} ],
   InquireEntityAuthority		=> [ 88,                         	$ResponseParameters{AuthorityRecord} ],
   InquireGroup				=> [ 119,                		$ResponseParameters{QSharingGroup} ],
   InquireLog				=> [ 120,                		$ResponseParameters{Log} ],
   InquireNamelist			=> [ 36,                      		$ResponseParameters{Namelist} ],
   InquireNamelistNames			=> [ 37,                            	$ResponseParameters{Namelist} ],
   InquireProcess			=> [ 7,                      		$ResponseParameters{Process} ],
   InquireProcessNames			=> [ 19,                           	$ResponseParameters{Process} ],
   InquirePubSubStatus			=> [ 185,                          	$ResponseParameters{PubSubStatus} ],
   InquireQueue				=> [ 13,               			$ResponseParameters{Queue} ],
   InquireQueueManager			=> [ 2,                    		$ResponseParameters{QueueManager} ],
   InquireQueueManagerStatus		=> [ 161,                         	$ResponseParameters{QueueManagerStatus} ],
   InquireQueueNames			=> [ 18,                     		$ResponseParameters{Queue} ],
   InquireQueueStatus			=> [ 41,                      		$ResponseParameters{QueueStatus} ],
   InquireSecurity			=> [ 121,                     		$ResponseParameters{InquireSecurity} ],
   InquireService			=> [ 153,                    		$ResponseParameters{Service} ],
   InquireServiceStatus			=> [ 154,                           	$ResponseParameters{ServiceStatus} ],
   InquireStorageClass			=> [ 122,                      		$ResponseParameters{StorageClass} ],
   InquireStorageClassNames		=> [ 148,                            	$ResponseParameters{StorageClass} ],
   InquireSubscription			=> [ 176,                         	$ResponseParameters{Subscription} ],
   InquireSubscriptionStatus		=> [ 182,                       		$ResponseParameters{SubscriptionStatus} ],
   InquireSystem			=> [ 123,                   		$ResponseParameters{InquireSystem} ],
   InquireTopic				=> [ 174,                  		$ResponseParameters{Topic} ],
   InquireTopicNames			=> [ 175,                        	$ResponseParameters{Topic} ],
   InquireTopicStatus			=> [ 183,                         	$ResponseParameters{TopicStatus} ],
   InquireUsage				=> [ 126,                  		$ResponseParameters{InquireUsage} ],

   PingChannel				=> [ 26,                  		$ResponseParameters{Channel} ],
   PingQueueManager			=> [ 40,                			$ResponseParameters{QueueManager} ],

   RefreshCluster			=> [ 73,                     		$ResponseParameters{Cluster} ],
   RefreshSecurity			=> [ 78,                      		$ResponseParameters{RefreshSecurity} ],

   ResetChannel				=> [ 27,                   		$ResponseParameters{Channel} ],
   ResetQueueStatistics			=> [ 17,                   		$ResponseParameters{Queue} ],

   ResolveChannel			=> [ 39,                     		$ResponseParameters{Channel} ],

   ReverifySecurity			=> [ 133,                      		$ResponseParameters{ReverifySecurity} ],

   SetAuthorityRecord			=> [ 90,                  		$ResponseParameters{AuthorityRecord} ],
   SetChlAuthRec			=> [ 203,                    		$ResponseParameters{ChlAuthRec} ],


   StartChannel				=> [ 28,                   		$ResponseParameters{Channel} ],
   StartChannelInitiator		=> [ 30,                        		$ResponseParameters{Channel} ],
   StartChannelListener			=> [ 31,                            	$ResponseParameters{Listener} ],
   StartService				=> [ 155,                  		$ResponseParameters{Service} ],

   StopChannel				=> [ 29,                  		$ResponseParameters{Channel} ],
   StopChannelInitiator			=> [ 141,                      		$ResponseParameters{Channel} ],
   StopChannelListener			=> [ 142,                          	$ResponseParameters{Listener} ],
   StopConnection			=> [ 86,                     		$ResponseParameters{Connection} ],
   StopService				=> [ 156,                 		$ResponseParameters{Service} ],

   #
   # Morgan Stanley extensions
   #
   InquireAuthority			=> [ 1000,                      		$ResponseParameters{MorganAuthority} ],
   ChangeAuthority			=> [ 1001,                     		$ResponseParameters{MorganAuthority} ],

  );

1;
