*** Settings ***
Documentation       Check sd-wan links.

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Ctn Generic Suite Setup
Test Timeout        120s


*** Variables ***
${CMD}                                          ${CENTREON_PLUGINS} --plugin=network::fortinet::fortigate::snmp::plugin

*** Test Cases ***
sdwan ${tc}
    [Tags]    network    sdwan
    ${command}    Catenate
    ...    ${CMD}
    ...    --mode=sdwan
    ...    --hostname=${HOSTNAME}
    ...    --snmp-version=${SNMPVERSION}
    ...    --snmp-port=${SNMPPORT}
    ...    --snmp-community=network/fortinet/fortigate/snmp/sdwan
    ...    --snmp-timeout=10
    ...    --snmp-retries=3
    ...    ${extra_options}
    ...    --debug
 
    Ctn Verify Command Output    ${command}    ${expected_result}

    Examples:        tc    extra_options                                                                                                expected_result    --
            ...      1     --verbose --help                                                                                             OK: All 100 components are ok [100/100 memories]. | 'hardware.memory.count'=100;;;;
            ...      2     --filter-id                                                                                                  UNKNOWN: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing'
            ...      3     --filter-name                                                                                                WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing'
            ...      4     --filter-vdom                                                                                                OK: All 0 components are ok [].
            ...      5     --unknown-status                                                                                             WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing' - memory 'Anonymized-002/mem-22' presence is: 'missing' - memory 'Anonymized-002/mem-12'
            ...      6     --warning-status                                                                                             WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing' - memory 'Anonymized-002/mem-22' presence is: 'missing' - memory 'Anonymized-002/mem-12'
            ...      7     --critical-status='\\\%{state} eq "down"'                                                                    WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing' - memory 'Anonymized-002/mem-22' presence is: 'missing' - memory 'Anonymized-002/mem-12' presence is: 'missing'
            ...      8     --critical-status='' --warning-traffic-in=0 --critical-traffic-in=10                                         CRITICAL: memory 'Anonymized-001/mem-10' presence is: 'equipped' - memory 'Anonymized-001/mem-11' presence is: 'equipped' - memory 'Anonymized-001/mem-13' presence is: 'equipped' - memory 'Anonymized-001/mem-14' presence is: 'equipped' - memory 'Anonymized-001/mem-16' presence is: 'equipped' - memory 'Anonymized-001/mem-17' presence is: 'equipped' - memory 'Anonymized-001/mem-19' presence is: 'equipped' - memory 'Anonymized-001/mem-1' presence is: 'equipped' - memory 'Anonymized-001/mem-2' presence is: 'equipped' - memory 'Anonymized-001/mem-4' presence is: 'equipped' - memory 'Anonymized-001/mem-5' presence is: 'equipped' - memory 'Anonymized-001/mem-7' presence is: 'equipped' - memory 'Anonymized-001/mem-8' presence is: 'equipped' - memory 'Anonymized-001/mem-20' presence is: 'equipped' - memory 'Anonymized-001/mem-22' presence is: 'equipped' - memory 'Anonymized-001/mem-23' presence is: 'equipped'
            ...      9     ${EMPTY}                                                                                                     WARNING: memory 'Anonymized-001/mem-12' presence is: 'missing' - memory 'Anonymized-001/mem-15' presence is: 'missing' - memory 'Anonymized-001/mem-18' presence is: 'missing' - memory 'Anonymized-001/mem-3' presence is: 'missing' - memory 'Anonymized-001/mem-6' presence is: 'missing' - memory 'Anonymized-001/mem-9' presence is: 'missing' - memory 'Anonymized-001/mem-21' presence is: 'missing' - memory 'Anonymized-001/mem-24' presence is: 'missing' - memory 'Anonymized-002/mem-23' presence is: 'missing' - memory 'Anonymized-002/mem-15' presence is: 'missing' - memory 'Anonymized-002/mem-9' presence is: 'missing' - memory 'Anonymized-002/mem-21' presence is: 'missing' - memory 'Anonymized-002/mem-16' presence is: 'missing' - memory 'Anonymized-002/mem-18' presence is: 'missing' - memory 'Anonymized-002/mem-11' presence is: 'missing' - memory 'Anonymized-002/mem-22' presence is: 'missing' - memory 'Anonymized-002/mem-12' presence is: 'missing' - memory 'Anonymized-002/mem-7'