*** Settings ***
Documentation       Check sd-wan links.

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Ctn Generic Suite Setup
Suite Teardown      Ctn Generic Suite Teardown
Test Timeout        120s


*** Variables ***
${CMD}      ${CENTREON_PLUGINS} --plugin=network::fortinet::fortigate::snmp::plugin


*** Test Cases ***
sdwan ${tc}
    [Tags]    network    sdwan
    ${command}    Catenate
    ...    ${CMD}
    ...    --mode=sdwan
    ...    --hostname=${HOSTNAME}
    ...    --snmp-version=${SNMPVERSION}
    ...    --snmp-port=${SNMPPORT}
    ...    --snmp-community=network/fortinet/fortigate/snmp/fortinet-fortigate
    ...    --snmp-timeout=10
    ...    --snmp-retries=3
    ...    ${extra_options}

    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:        tc    extra_options                                                                                                expected_result    --
            ...      1     --include-vdom='root'                                                                                        CRITICAL: sd-wan 'MPLS' [vdom: root] [interface: wan2] state: down | 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.in.bitspersecond'=27453000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.out.bitspersecond'=29552000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.bi.bitspersecond'=57005000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.latency.milliseconds'=8.62ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.jitter.milliseconds'=0.07ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.packetloss.percentage'=0.000%;;;0;100 'root~MPLS~wan2#sdwan.traffic.in.bitspersecond'=65432000b/s;;;0; 'root~MPLS~wan2#sdwan.traffic.out.bitspersecond'=71234000b/s;;;0; 'root~MPLS~wan2#sdwan.traffic.bi.bitspersecond'=136666000b/s;;;0; 'root~MPLS~wan2#sdwan.latency.milliseconds'=18.45ms;;;0; 'root~MPLS~wan2#sdwan.jitter.milliseconds'=0.99ms;;;0; 'root~MPLS~wan2#sdwan.packetloss.percentage'=0.050%;;;0;100 'root~ISP1~wan3#sdwan.traffic.in.bitspersecond'=125000000b/s;;;0; 'root~ISP1~wan3#sdwan.traffic.out.bitspersecond'=98765000b/s;;;0; 'root~ISP1~wan3#sdwan.traffic.bi.bitspersecond'=223765000b/s;;;0; 'root~ISP1~wan3#sdwan.latency.milliseconds'=5.23ms;;;0; 'root~ISP1~wan3#sdwan.jitter.milliseconds'=0.12ms;;;0; 'root~ISP1~wan3#sdwan.packetloss.percentage'=0.010%;;;0;100
            ...      2     --unknown-status='\\\%{vdom} eq "root"' --include-vdom='root' --exclude-interface-name='wan2'                UNKNOWN: sd-wan 'fgVWLHealthCheckLinkName' [vdom: root] [interface: wan1] state: up - sd-wan 'ISP1' [vdom: root] [interface: wan3] state: up | 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.in.bitspersecond'=27453000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.out.bitspersecond'=29552000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.bi.bitspersecond'=57005000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.latency.milliseconds'=8.62ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.jitter.milliseconds'=0.07ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.packetloss.percentage'=0.000%;;;0;100 'root~ISP1~wan3#sdwan.traffic.in.bitspersecond'=125000000b/s;;;0; 'root~ISP1~wan3#sdwan.traffic.out.bitspersecond'=98765000b/s;;;0; 'root~ISP1~wan3#sdwan.traffic.bi.bitspersecond'=223765000b/s;;;0; 'root~ISP1~wan3#sdwan.latency.milliseconds'=5.23ms;;;0; 'root~ISP1~wan3#sdwan.jitter.milliseconds'=0.12ms;;;0; 'root~ISP1~wan3#sdwan.packetloss.percentage'=0.010%;;;0;100
            ...      3     --warning-status='\\\%{state} eq "up"' --include-vdom='root' --include-interface-name='wan1'                 WARNING: sd-wan 'fgVWLHealthCheckLinkName' [vdom: root] [interface: wan1] state: up | 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.in.bitspersecond'=27453000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.out.bitspersecond'=29552000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.bi.bitspersecond'=57005000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.latency.milliseconds'=8.62ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.jitter.milliseconds'=0.07ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.packetloss.percentage'=0.000%;;;0;100
            ...      4     --critical-status='\\\%{state} eq "up"' --include-vdom='root' --include-interface-name='wan1'                CRITICAL: sd-wan 'fgVWLHealthCheckLinkName' [vdom: root] [interface: wan1] state: up | 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.in.bitspersecond'=27453000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.out.bitspersecond'=29552000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.bi.bitspersecond'=57005000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.latency.milliseconds'=8.62ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.jitter.milliseconds'=0.07ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.packetloss.percentage'=0.000%;;;0;100
            ...      5     --critical-status='\\\%{vdom} eq "root"' --warning-traffic-in=0 --critical-traffic-in=8 --include-vdom='root' --include-interface-name='wan1'                     CRITICAL: sd-wan 'fgVWLHealthCheckLinkName' [vdom: root] [interface: wan1] state: up - traffic in: 27.45 Mb/s | 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.in.bitspersecond'=27453000b/s;0:0;0:8;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.out.bitspersecond'=29552000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.bi.bitspersecond'=57005000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.latency.milliseconds'=8.62ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.jitter.milliseconds'=0.07ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.packetloss.percentage'=0.000%;;;0;100
            ...      6     ${EMPTY}                                                                                                     CRITICAL: sd-wan 'ISP2' [vdom: vdom-prod] [interface: port1] state: down - sd-wan 'MPLS' [vdom: root] [interface: wan2] state: down | 'vdom-prod~ISP2~port1#sdwan.traffic.in.bitspersecond'=54321000b/s;;;0; 'vdom-prod~ISP2~port1#sdwan.traffic.out.bitspersecond'=43210000b/s;;;0; 'vdom-prod~ISP2~port1#sdwan.traffic.bi.bitspersecond'=97531000b/s;;;0; 'vdom-prod~ISP2~port1#sdwan.latency.milliseconds'=45.68ms;;;0; 'vdom-prod~ISP2~port1#sdwan.jitter.milliseconds'=3.46ms;;;0; 'vdom-prod~ISP2~port1#sdwan.packetloss.percentage'=2.500%;;;0;100 'vdom-prod~Backup-4G~port2#sdwan.traffic.in.bitspersecond'=12345000b/s;;;0; 'vdom-prod~Backup-4G~port2#sdwan.traffic.out.bitspersecond'=11111000b/s;;;0; 'vdom-prod~Backup-4G~port2#sdwan.traffic.bi.bitspersecond'=23456000b/s;;;0; 'vdom-prod~Backup-4G~port2#sdwan.latency.milliseconds'=12.35ms;;;0; 'vdom-prod~Backup-4G~port2#sdwan.jitter.milliseconds'=0.46ms;;;0; 'vdom-prod~Backup-4G~port2#sdwan.packetloss.percentage'=0.000%;;;0;100 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.in.bitspersecond'=27453000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.out.bitspersecond'=29552000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.traffic.bi.bitspersecond'=57005000b/s;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.latency.milliseconds'=8.62ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.jitter.milliseconds'=0.07ms;;;0; 'root~fgVWLHealthCheckLinkName~wan1#sdwan.packetloss.percentage'=0.000%;;;0;100 'root~MPLS~wan2#sdwan.traffic.in.bitspersecond'=65432000b/s;;;0; 'root~MPLS~wan2#sdwan.traffic.out.bitspersecond'=71234000b/s;;;0; 'root~MPLS~wan2#sdwan.traffic.bi.bitspersecond'=136666000b/s;;;0; 'root~MPLS~wan2#sdwan.latency.milliseconds'=18.45ms;;;0; 'root~MPLS~wan2#sdwan.jitter.milliseconds'=0.99ms;;;0; 'root~MPLS~wan2#sdwan.packetloss.percentage'=0.050%;;;0;100 'root~ISP1~wan3#sdwan.traffic.in.bitspersecond'=125000000b/s;;;0; 'root~ISP1~wan3#sdwan.traffic.out.bitspersecond'=98765000b/s;;;0; 'root~ISP1~wan3#sdwan.traffic.bi.bitspersecond'=223765000b/s;;;0; 'root~ISP1~wan3#sdwan.latency.milliseconds'=5.23ms;;;0; 'root~ISP1~wan3#sdwan.jitter.milliseconds'=0.12ms;;;0; 'root~ISP1~wan3#sdwan.packetloss.percentage'=0.010%;;;0;100
            ...      7     --warning-status='\\\%{vdom} eq "root"' --warning-latency=8 --critical-latency=16 --include-vdom='root' --include-interface-name='wan2'                         CRITICAL: sd-wan 'MPLS' [vdom: root] [interface: wan2] state: down - latency: 18.452ms | 'root~MPLS~wan2#sdwan.traffic.in.bitspersecond'=65432000b/s;;;0; 'root~MPLS~wan2#sdwan.traffic.out.bitspersecond'=71234000b/s;;;0; 'root~MPLS~wan2#sdwan.traffic.bi.bitspersecond'=136666000b/s;;;0; 'root~MPLS~wan2#sdwan.latency.milliseconds'=18.45ms;0:8;0:16;0; 'root~MPLS~wan2#sdwan.jitter.milliseconds'=0.99ms;;;0; 'root~MPLS~wan2#sdwan.packetloss.percentage'=0.050%;;;0;100
            ...      8     --exclude-vdom='root'                                                                                        CRITICAL: sd-wan 'ISP2' [vdom: vdom-prod] [interface: port1] state: down | 'vdom-prod~ISP2~port1#sdwan.traffic.in.bitspersecond'=54321000b/s;;;0; 'vdom-prod~ISP2~port1#sdwan.traffic.out.bitspersecond'=43210000b/s;;;0; 'vdom-prod~ISP2~port1#sdwan.traffic.bi.bitspersecond'=97531000b/s;;;0; 'vdom-prod~ISP2~port1#sdwan.latency.milliseconds'=45.68ms;;;0; 'vdom-prod~ISP2~port1#sdwan.jitter.milliseconds'=3.46ms;;;0; 'vdom-prod~ISP2~port1#sdwan.packetloss.percentage'=2.500%;;;0;100 'vdom-prod~Backup-4G~port2#sdwan.traffic.in.bitspersecond'=12345000b/s;;;0; 'vdom-prod~Backup-4G~port2#sdwan.traffic.out.bitspersecond'=11111000b/s;;;0; 'vdom-prod~Backup-4G~port2#sdwan.traffic.bi.bitspersecond'=23456000b/s;;;0; 'vdom-prod~Backup-4G~port2#sdwan.latency.milliseconds'=12.35ms;;;0; 'vdom-prod~Backup-4G~port2#sdwan.jitter.milliseconds'=0.46ms;;;0; 'vdom-prod~Backup-4G~port2#sdwan.packetloss.percentage'=0.000%;;;0;100
            ...      9     --disco-format                                                                                               <?xml version="1.0" encoding="utf-8"?> <data> <element>name</element> <element>vdom</element> <element>ifName</element> <element>id</element> <element>state</element> </data>
            ...      10    --disco-show                                                                                                 <?xml version="1.0" encoding="utf-8"?> <data> <label id="11" ifName="port2" name="Backup-4G" state="up" vdom="vdom-prod"/> <label id="9" ifName="wan3" name="ISP1" state="up" vdom="root"/> <label id="10" ifName="port1" name="ISP2" state="down" vdom="vdom-prod"/> <label id="8" ifName="wan2" name="MPLS" state="down" vdom="root"/> <label id="7" ifName="wan1" name="fgVWLHealthCheckLinkName" state="up" vdom="root"/> </data>
