name: "test-plugins"
description: "Test plugin that are passed as parameters"
inputs:
  cache-key:
    description: "The packaged plugin's cache key"
    required: true
  plugin-list:
    description: "List of plugins to install from the cache"
    required: true
  package-extension:
    description: "Either 'rpm' or 'deb'. Needed to determine the package manager command (dnf or apt-get)."
    required: true

runs:
  using: "composite"
  steps:

    - name: get the cached plugin
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ./*.${{ inputs.package-extension }}
        key: ${{ inputs.cache-key }}
        fail-on-cache-miss: true

    - name: Install, test and remove plugin
      shell: bash
      run: |
        [[ -f /.venv/bin/activate ]] && source /.venv/bin/activate
        python3 .github/scripts/test-all-plugins.py ${{ inputs.package-extension }} ${{ inputs.plugin-list }}
