name: "test-plugins"
description: "Test plugin that are passed as parameters"
inputs:
  packages-cache-key:
    description: "The packaged plugin's cache key"
    required: true
  get-packages:
    description: "Whether to get the packages from cache or not"
    default: "true"
  plugins-json-cache-key:
    description: "The cache key for plugin's json"
    required: true
  package-extension:
    description: "Either 'rpm' or 'deb'. Needed to determine the package manager command (dnf or apt-get)."
    required: true
  runner-id:
    description: "The GitHub Actions runner id"
    required: true

runs:
  using: "composite"
  steps:

    - name: Get the cached plugin
      if: ${{ inputs.get-packages == 'true' }}
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ./*.${{ inputs.package-extension }}
        key: ${{ inputs.packages-cache-key }}
        fail-on-cache-miss: true

    - name: Get the cached plugins.json
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ./plugins.json
        key: ${{ inputs.plugins-json-cache-key }}
        fail-on-cache-miss: true

    - name: Install, test and remove plugin
      shell: bash
      run: |
        [[ -f /.venv/bin/activate ]] && source /.venv/bin/activate
        python3 .github/scripts/test-plugins.py --extension=${{ inputs.package-extension }} --runner-id=${{ inputs.runner-id }}
