//
// Copyright 2026-Present Centreon (http://www.centreon.com/)
//
// Centreon is a full-fledged industry-strength solution that meets
// the needs in IT infrastructure and application monitoring for
// service performance.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

use crate::compute::lexer;
use crate::compute::ast;

grammar<'input>;

pub Expr: Box<ast::Expr<'input>> = {
    <s:Expr> "+" <p:Product> => Box::new(ast::Expr::OpPlus(<>)),
    <s:Expr> "-" <p:Product> => Box::new(ast::Expr::OpMinus(<>)),
    Product,
};

pub Product: Box<ast::Expr<'input>> = {
    <s:Product> "*" <v:Term> => Box::new(ast::Expr::OpStar(<>)),
    <s:Product> "/" <v:Term> => Box::new(ast::Expr::OpSlash(<>)),
    <v:Term> => <>,
};

pub Function: Box<ast::Expr<'input>> = {
    <f:"id"> "(" <a:Var> ")" => {
      match f {
	b"Average" => return Box::new(ast::Expr::Fn(ast::Func::Average, a)),
	b"Max" => return Box::new(ast::Expr::Fn(ast::Func::Max, a)),
	b"Min" => return Box::new(ast::Expr::Fn(ast::Func::Min, a)),
	// FIXME DBO: This case is an error case...
	_ => return a,
      }
    }
};

pub Term: Box<ast::Expr<'input>> = {
    "num" => Box::new(ast::Expr::Number(<>)),
    Function => <>,
    "(" <v:Expr> ")" => <>,
    Var => <>,
};

pub Var: Box<ast::Expr<'input>> = {
    "{" <"id"> "}" => Box::new(ast::Expr::Id(<>)),
}

extern {
    type Location = usize;
    type Error = lexer::LexicalError;

    // ...

    enum lexer::Tok<'input> {
	"*" => lexer::Tok::OpStar,
	"/" => lexer::Tok::OpSlash,
	"+" => lexer::Tok::OpPlus,
	"-" => lexer::Tok::OpMinus,
	"(" => lexer::Tok::LParen,
	")" => lexer::Tok::RParen,
	"{" => lexer::Tok::LBrace,
	"}" => lexer::Tok::RBrace,
	"num" => lexer::Tok::Num(<f64>),
	"id" => lexer::Tok::Id(<&'input [u8]>),
    }
}
