*** Settings ***
Documentation       apps::backup::veeam::vone::restapi::plugin

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}     ${CURDIR}${/}vone.mockoon.json
${CMD}              ${CENTREON_PLUGINS}
...         --plugin=apps::backup::veeam::vone::restapi::plugin
...         --mode=jobs
...         --hostname=${HOSTNAME}
...         --port=${APIPORT}
...         --proto=http
...         --api-username=UsErNaMe
...         --api-password=P@s$W0Rd


*** Test Cases ***
Jobs ${tc}
    [Tags]    apps    backup    restapi
    ${command}    Catenate
    ...    ${CMD}
    ...    ${extra_options}

    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:
    ...    tc
    ...    extra_options
    ...    expected_result
    ...    --
    ...    1
    ...    ${EMPTY}
    ...    OK: All jobs are ok | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    2
    ...    --add-vm-replication-jobs=1
    ...    OK: All jobs are ok | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    3
    ...    --add-vm-backup-jobs=1
    ...    WARNING: job 'Backup-Job_AZERTY_Daily' [type: vmBackup] status: warning - job 'Backup-Job_QWERTY_Daily' [type: vmBackup] status: warning | 'jobs.detected.count'=2;;;0; 'vmBackup~Backup-Job_AZERTY_Daily#job.status.count'=5;;;0; 'vmBackup~Backup-Job_AZERTY_Daily#job.last.duration.seconds'=41791s;;;0; 'vmBackup~Backup-Job_QWERTY_Daily#job.status.count'=5;;;0; 'vmBackup~Backup-Job_QWERTY_Daily#job.last.duration.seconds'=122184s;;;0;
    ...    4
    ...    --add-backup-copy-jobs=1
    ...    OK: All jobs are ok | 'jobs.detected.count'=11;;;0; 'backupCopy~BackupCopy-Job_AZERTY_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_BBBBBBB_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_CCCCCCC_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_HHHHHHHH_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_LLLLLLLL_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_NNNNNNN_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_OOOOO_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_QQQQQQ_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_VVVVVVV_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_WWWWWW_Daily#job.status.count'=1;;;0; 'backupCopy~BackupCopy-Job_XXXXXX_Daily#job.status.count'=1;;;0;
    ...    5
    ...    --filter-uid=azazaza-ZAZAZZ-21212121-ANOANO
    ...    OK: job 'Replication-Job_EEEEEEE' [type: vmReplication] status: success - last duration time: 2h 33m 33s | 'jobs.detected.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0;
    ...    6
    ...    --filter-name=Replication-Job_ZZZZZZ-Daily
    ...    OK: job 'Replication-Job_ZZZZZZ-Daily' [type: vmReplication] status: success - last duration time: 1h 45m 27s | 'jobs.detected.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    7
    ...    --filter-type=vmReplication
    ...    OK: All jobs are ok | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    8
    ...    --unknown-job-status='%\\\{status\\\} =~ /success/'
    ...    UNKNOWN: job 'Replication-Job-QQQQQQ' [type: vmReplication] status: success - job 'Replication-Job-YYYYY-Daily' [type: vmReplication] status: success - job 'Replication-Job_EEEEEEE' [type: vmReplication] status: success - job 'Replication-Job_FFFFFFF' [type: vmReplication] status: success - job 'Replication-Job_LLLLLLLL' [type: vmReplication] status: success - job 'Replication-Job_RRRRRRR' [type: vmReplication] status: success - job 'Replication-Job_WWWWWWW' [type: vmReplication] status: success - job 'Replication-Job_XXXXX-Daily' [type: vmReplication] status: success - job 'Replication-Job_ZZZZZZ-Daily' [type: vmReplication] status: success | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    9
    ...    --warning-job-status='%\\\{status\\\} =~ /success/'
    ...    WARNING: job 'Replication-Job-QQQQQQ' [type: vmReplication] status: success - job 'Replication-Job-YYYYY-Daily' [type: vmReplication] status: success - job 'Replication-Job_EEEEEEE' [type: vmReplication] status: success - job 'Replication-Job_FFFFFFF' [type: vmReplication] status: success - job 'Replication-Job_LLLLLLLL' [type: vmReplication] status: success - job 'Replication-Job_RRRRRRR' [type: vmReplication] status: success - job 'Replication-Job_WWWWWWW' [type: vmReplication] status: success - job 'Replication-Job_XXXXX-Daily' [type: vmReplication] status: success - job 'Replication-Job_ZZZZZZ-Daily' [type: vmReplication] status: success | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    10
    ...    --critical-job-status='%\\\{status\\\} =~ /success/'
    ...    CRITICAL: job 'Replication-Job-QQQQQQ' [type: vmReplication] status: success - job 'Replication-Job-YYYYY-Daily' [type: vmReplication] status: success - job 'Replication-Job_EEEEEEE' [type: vmReplication] status: success - job 'Replication-Job_FFFFFFF' [type: vmReplication] status: success - job 'Replication-Job_LLLLLLLL' [type: vmReplication] status: success - job 'Replication-Job_RRRRRRR' [type: vmReplication] status: success - job 'Replication-Job_WWWWWWW' [type: vmReplication] status: success - job 'Replication-Job_XXXXX-Daily' [type: vmReplication] status: success - job 'Replication-Job_ZZZZZZ-Daily' [type: vmReplication] status: success | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    11
    ...    --warning-job-last-duration=:1
    ...    WARNING: job 'Replication-Job-QQQQQQ' [type: vmReplication] last duration time: 52m 3s - job 'Replication-Job-YYYYY-Daily' [type: vmReplication] last duration time: 27m 57s - job 'Replication-Job_EEEEEEE' [type: vmReplication] last duration time: 2h 33m 33s - job 'Replication-Job_FFFFFFF' [type: vmReplication] last duration time: 29m 40s - job 'Replication-Job_LLLLLLLL' [type: vmReplication] last duration time: 2h 16m 6s - job 'Replication-Job_RRRRRRR' [type: vmReplication] last duration time: 2h 4m 5s - job 'Replication-Job_WWWWWWW' [type: vmReplication] last duration time: 1h 7m 18s - job 'Replication-Job_XXXXX-Daily' [type: vmReplication] last duration time: 1h 28m 12s - job 'Replication-Job_ZZZZZZ-Daily' [type: vmReplication] last duration time: 1h 45m 27s | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;0:1;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;0:1;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;0:1;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;0:1;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;0:1;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;0:1;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;0:1;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;0:1;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;0:1;;0;
    ...    12
    ...    --critical-job-last-duration=:1
    ...    CRITICAL: job 'Replication-Job-QQQQQQ' [type: vmReplication] last duration time: 52m 3s - job 'Replication-Job-YYYYY-Daily' [type: vmReplication] last duration time: 27m 57s - job 'Replication-Job_EEEEEEE' [type: vmReplication] last duration time: 2h 33m 33s - job 'Replication-Job_FFFFFFF' [type: vmReplication] last duration time: 29m 40s - job 'Replication-Job_LLLLLLLL' [type: vmReplication] last duration time: 2h 16m 6s - job 'Replication-Job_RRRRRRR' [type: vmReplication] last duration time: 2h 4m 5s - job 'Replication-Job_WWWWWWW' [type: vmReplication] last duration time: 1h 7m 18s - job 'Replication-Job_XXXXX-Daily' [type: vmReplication] last duration time: 1h 28m 12s - job 'Replication-Job_ZZZZZZ-Daily' [type: vmReplication] last duration time: 1h 45m 27s | 'jobs.detected.count'=9;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;0:1;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;0:1;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;0:1;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;0:1;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;0:1;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;0:1;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;0:1;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;0:1;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;0:1;0;
    ...    13
    ...    --warning-jobs-detected=:1
    ...    WARNING: Number of jobs detected: 9 | 'jobs.detected.count'=9;0:1;;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    14
    ...    --critical-jobs-detected=:1
    ...    CRITICAL: Number of jobs detected: 9 | 'jobs.detected.count'=9;;0:1;0; 'vmReplication~Replication-Job-QQQQQQ#job.status.count'=1;;;0; 'vmReplication~Replication-Job-QQQQQQ#job.last.duration.seconds'=3123s;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job-YYYYY-Daily#job.last.duration.seconds'=1677s;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.status.count'=1;;;0; 'vmReplication~Replication-Job_EEEEEEE#job.last.duration.seconds'=9213s;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.status.count'=1;;;0; 'vmReplication~Replication-Job_FFFFFFF#job.last.duration.seconds'=1780s;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.status.count'=1;;;0; 'vmReplication~Replication-Job_LLLLLLLL#job.last.duration.seconds'=8166s;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.status.count'=1;;;0; 'vmReplication~Replication-Job_RRRRRRR#job.last.duration.seconds'=7445s;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.status.count'=1;;;0; 'vmReplication~Replication-Job_WWWWWWW#job.last.duration.seconds'=4038s;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_XXXXX-Daily#job.last.duration.seconds'=5292s;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.status.count'=1;;;0; 'vmReplication~Replication-Job_ZZZZZZ-Daily#job.last.duration.seconds'=6327s;;;0;
    ...    15
    ...    --disco-format
    ...    <?xml version="1.0" encoding="utf-8"?> <data> <element>uid</element> <element>name</element> <element>type</element> <element>status</element> </data>
    ...    16
    ...    --disco-show --filter-uid=azazaza-ZAZAZZ-21212121-ANOANO
    ...    <?xml version="1.0" encoding="utf-8"?> <data> <label name="Replication-Job_EEEEEEE" status="success" type="vmReplication" uid="azazaza-ZAZAZZ-21212121-ANOANO"/> </data>
