#! /usr/bin/perl -w
#
# $Id: check_packetsErrors.pl,v 1.2 2005/07/27 22:21:49 Julio $
#
# Oreon's plugins are developped with GPL Licence :
# http://www.fsf.org/licenses/gpl.txt
# Developped by : Julien Mathis - Romain Le Merlus - Sugumaran Mat
#
# Modified for Oreon Project by : Mathieu Chateau - Christophe Coraboeuf
# Modified By Julien Mathis For Merethis Company
#
# The Software is provided to you AS IS and WITH ALL FAULTS.
# OREON makes no representation and gives no warranty whatsoever,
# whether express or implied, and without limitation, with regard to the quality,
# safety, contents, performance, merchantability, non-infringement or suitability for
# any particular or intended purpose of the Software found on the OREON web site.
# In no event will OREON be liable for any direct, indirect, punitive, special,
# incidental or consequential damages however they may arise and even if OREON has
# been previously advised of the possibility of such damages.

#
# Plugin init
#

use strict;
use FindBin;

use vars qw($PROGNAME);
use Getopt::Long;
use vars qw($opt_h $opt_s $opt_o);

#################################################
### Plugin var init
##
$PROGNAME = "$0";

sub print_help ();
sub print_usage ();

Getopt::Long::Configure('bundling');
GetOptions
    ("h"   => \$opt_h, "help"         => \$opt_h,
     "s=s" => \$opt_s, "status=s"     => \$opt_s,
     "o=s" => \$opt_o, "output=s"     => \$opt_o);


##################################################
#### Verify Options
##

if ($opt_h) {
    print_help();
    exit 0;
}

if (!defined($opt_s)) {
    print_usage && exit 0;
}
if ($opt_s ne "0" && $opt_s ne "0" && $opt_s ne "0" && $opt_s ne "0") {
    print_usage;
    exit 0;
} 
if (!$opt_o) {
    $opt_o = "OK";
}

#################################################
## result
#

$opt_o .= "\n";
print $opt_o;
exit $opt_s;

sub print_usage () {
    print "Usage:";
    print "$PROGNAME\n";
    print "   -s (--status)     status that must be returned [0-3]\n";
    print "   -o (--output)     output that must be returned\n";
    print "   -h (--help)       usage help\n";
}

sub print_help () {
    print "##########################################\n";
    print "#  Copyright (c) 2004-2006 Oreon         #\n";
    print "#  Bugs to http://www.oreon-project.org/ #\n";
    print "##########################################\n";
    print_usage();
    print "\n";
}
