*** Settings ***
Documentation       Check the LatenceTech latency mode with api custom mode

Resource            ${CURDIR}${/}..${/}..${/}..${/}..${/}resources/import.resource

Suite Setup         Start Mockoon    ${MOCKOON_JSON}
Suite Teardown      Stop Mockoon
Test Timeout        120s


*** Variables ***
${MOCKOON_JSON}     ${CURDIR}${/}mockoon.json

${cmd}              ${CENTREON_PLUGINS}
...                 --plugin=apps::monitoring::latencetech::restapi::plugin
...                 --custommode=api
...                 --mode=latency
...                 --hostname=${HOSTNAME}
...                 --api-key=key
...                 --port=${APIPORT}
...                 --proto=http


*** Test Cases ***
Latency ${tc}
    [Documentation]    Check the agent latency statistics
    [Tags]    apps    monitoring    latencetech    restapi

    ${command}    Catenate
    ...    ${cmd}
    ...    --customer-id=0
    ...    --agent-id=2
    ...    ${extraoptions}
    Log    ${cmd}
    Ctn Run Command And Check Result As Strings    ${command}    ${expected_result}

    Examples:         tc    extraoptions    expected_result    --
            ...       1     ${EMPTY}
            ...       OK: All latencies are OK | 'http_result#latency.average.milliseconds'=9.18ms;;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;;0; 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0; 'icmp_result#latency.average.milliseconds'=9.16ms;;;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;;;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;;;0; 'tcp_result#latency.average.milliseconds'=9.35ms;;;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;;;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;;;0; 'twamp_result#latency.average.milliseconds'=9.16ms;;;0; 'twamp_result#latency.minimum.milliseconds'=8.36ms;;;0; 'twamp_result#latency.maximum.milliseconds'=15.86ms;;;0; 'udp_result#latency.average.milliseconds'=9.36ms;;;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;;;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;;;0;
            ...       2     --filter-protocol=tcp
            ...       OK: Latency for Agent 2, Protocol tcp_result (150 points): average: 9.35ms, minimum: 8.38ms, maximum: 22.56ms | 'tcp_result#latency.average.milliseconds'=9.35ms;;;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;;;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;;;0;
            ...       3     --filter-protocol='http.*'
            ...       OK: All latencies are OK | 'http_result#latency.average.milliseconds'=9.18ms;;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;;0; 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0;
            ...       4     --filter-protocol='http(s)?'
            ...       OK: All latencies are OK | 'http_result#latency.average.milliseconds'=9.18ms;;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;;0; 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0;
            ...       5     --filter-protocol='https|icmp'
            ...       OK: All latencies are OK | 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0; 'icmp_result#latency.average.milliseconds'=9.16ms;;;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;;;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;;;0;
            ...       6     --warning-latency-average=8
            ...       WARNING: Latency for Agent 2, Protocol http_result (149 points): average: 9.18ms - Latency for Agent 2, Protocol https_result (146 points): average: 18.05ms - Latency for Agent 2, Protocol icmp_result (149 points): average: 9.16ms - Latency for Agent 2, Protocol tcp_result (150 points): average: 9.35ms - Latency for Agent 2, Protocol twamp_result (142 points): average: 9.16ms - Latency for Agent 2, Protocol udp_result (150 points): average: 9.36ms | 'http_result#latency.average.milliseconds'=9.18ms;0:8;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;;0; 'https_result#latency.average.milliseconds'=18.05ms;0:8;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0; 'icmp_result#latency.average.milliseconds'=9.16ms;0:8;;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;;;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;;;0; 'tcp_result#latency.average.milliseconds'=9.35ms;0:8;;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;;;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;;;0; 'twamp_result#latency.average.milliseconds'=9.16ms;0:8;;0; 'twamp_result#latency.minimum.milliseconds'=8.36ms;;;0; 'twamp_result#latency.maximum.milliseconds'=15.86ms;;;0; 'udp_result#latency.average.milliseconds'=9.36ms;0:8;;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;;;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;;;0;
            ...       7     --critical-latency-average=9
            ...       CRITICAL: Latency for Agent 2, Protocol http_result (149 points): average: 9.18ms - Latency for Agent 2, Protocol https_result (146 points): average: 18.05ms - Latency for Agent 2, Protocol icmp_result (149 points): average: 9.16ms - Latency for Agent 2, Protocol tcp_result (150 points): average: 9.35ms - Latency for Agent 2, Protocol twamp_result (142 points): average: 9.16ms - Latency for Agent 2, Protocol udp_result (150 points): average: 9.36ms | 'http_result#latency.average.milliseconds'=9.18ms;;0:9;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;;0; 'https_result#latency.average.milliseconds'=18.05ms;;0:9;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0; 'icmp_result#latency.average.milliseconds'=9.16ms;;0:9;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;;;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;;;0; 'tcp_result#latency.average.milliseconds'=9.35ms;;0:9;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;;;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;;;0; 'twamp_result#latency.average.milliseconds'=9.16ms;;0:9;0; 'twamp_result#latency.minimum.milliseconds'=8.36ms;;;0; 'twamp_result#latency.maximum.milliseconds'=15.86ms;;;0; 'udp_result#latency.average.milliseconds'=9.36ms;;0:9;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;;;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;;;0;
            ...       8     --warning-latency-minimum=7
            ...       WARNING: Latency for Agent 2, Protocol http_result (149 points): minimum: 8.51ms - Latency for Agent 2, Protocol https_result (146 points): minimum: 16.72ms - Latency for Agent 2, Protocol icmp_result (149 points): minimum: 8.37ms - Latency for Agent 2, Protocol tcp_result (150 points): minimum: 8.38ms - Latency for Agent 2, Protocol twamp_result (142 points): minimum: 8.36ms - Latency for Agent 2, Protocol udp_result (150 points): minimum: 8.57ms | 'http_result#latency.average.milliseconds'=9.18ms;;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;0:7;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;;0; 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;0:7;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0; 'icmp_result#latency.average.milliseconds'=9.16ms;;;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;0:7;;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;;;0; 'tcp_result#latency.average.milliseconds'=9.35ms;;;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;0:7;;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;;;0; 'twamp_result#latency.average.milliseconds'=9.16ms;;;0; 'twamp_result#latency.minimum.milliseconds'=8.36ms;0:7;;0; 'twamp_result#latency.maximum.milliseconds'=15.86ms;;;0; 'udp_result#latency.average.milliseconds'=9.36ms;;;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;0:7;;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;;;0;
            ...       9     --critical-latency-minimum=8
            ...       CRITICAL: Latency for Agent 2, Protocol http_result (149 points): minimum: 8.51ms - Latency for Agent 2, Protocol https_result (146 points): minimum: 16.72ms - Latency for Agent 2, Protocol icmp_result (149 points): minimum: 8.37ms - Latency for Agent 2, Protocol tcp_result (150 points): minimum: 8.38ms - Latency for Agent 2, Protocol twamp_result (142 points): minimum: 8.36ms - Latency for Agent 2, Protocol udp_result (150 points): minimum: 8.57ms | 'http_result#latency.average.milliseconds'=9.18ms;;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;0:8;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;;0; 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;0:8;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;;0; 'icmp_result#latency.average.milliseconds'=9.16ms;;;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;;0:8;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;;;0; 'tcp_result#latency.average.milliseconds'=9.35ms;;;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;;0:8;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;;;0; 'twamp_result#latency.average.milliseconds'=9.16ms;;;0; 'twamp_result#latency.minimum.milliseconds'=8.36ms;;0:8;0; 'twamp_result#latency.maximum.milliseconds'=15.86ms;;;0; 'udp_result#latency.average.milliseconds'=9.36ms;;;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;;0:8;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;;;0;
            ...       10    --warning-latency-maximum=14
            ...       WARNING: Latency for Agent 2, Protocol http_result (149 points): maximum: 15.62ms - Latency for Agent 2, Protocol https_result (146 points): maximum: 27.29ms - Latency for Agent 2, Protocol icmp_result (149 points): maximum: 22.10ms - Latency for Agent 2, Protocol tcp_result (150 points): maximum: 22.56ms - Latency for Agent 2, Protocol twamp_result (142 points): maximum: 15.86ms - Latency for Agent 2, Protocol udp_result (150 points): maximum: 22.13ms | 'http_result#latency.average.milliseconds'=9.18ms;;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;0:14;;0; 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;0:14;;0; 'icmp_result#latency.average.milliseconds'=9.16ms;;;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;;;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;0:14;;0; 'tcp_result#latency.average.milliseconds'=9.35ms;;;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;;;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;0:14;;0; 'twamp_result#latency.average.milliseconds'=9.16ms;;;0; 'twamp_result#latency.minimum.milliseconds'=8.36ms;;;0; 'twamp_result#latency.maximum.milliseconds'=15.86ms;0:14;;0; 'udp_result#latency.average.milliseconds'=9.36ms;;;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;;;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;0:14;;0;
            ...       11    --critical-latency-maximum=15
            ...       CRITICAL: Latency for Agent 2, Protocol http_result (149 points): maximum: 15.62ms - Latency for Agent 2, Protocol https_result (146 points): maximum: 27.29ms - Latency for Agent 2, Protocol icmp_result (149 points): maximum: 22.10ms - Latency for Agent 2, Protocol tcp_result (150 points): maximum: 22.56ms - Latency for Agent 2, Protocol twamp_result (142 points): maximum: 15.86ms - Latency for Agent 2, Protocol udp_result (150 points): maximum: 22.13ms | 'http_result#latency.average.milliseconds'=9.18ms;;;0; 'http_result#latency.minimum.milliseconds'=8.51ms;;;0; 'http_result#latency.maximum.milliseconds'=15.62ms;;0:15;0; 'https_result#latency.average.milliseconds'=18.05ms;;;0; 'https_result#latency.minimum.milliseconds'=16.72ms;;;0; 'https_result#latency.maximum.milliseconds'=27.29ms;;0:15;0; 'icmp_result#latency.average.milliseconds'=9.16ms;;;0; 'icmp_result#latency.minimum.milliseconds'=8.37ms;;;0; 'icmp_result#latency.maximum.milliseconds'=22.10ms;;0:15;0; 'tcp_result#latency.average.milliseconds'=9.35ms;;;0; 'tcp_result#latency.minimum.milliseconds'=8.38ms;;;0; 'tcp_result#latency.maximum.milliseconds'=22.56ms;;0:15;0; 'twamp_result#latency.average.milliseconds'=9.16ms;;;0; 'twamp_result#latency.minimum.milliseconds'=8.36ms;;;0; 'twamp_result#latency.maximum.milliseconds'=15.86ms;;0:15;0; 'udp_result#latency.average.milliseconds'=9.36ms;;;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;;;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;;0:15;0;
            ...       12    --filter-protocol=udp --critical-latency-maximum=20
            ...       CRITICAL: Latency for Agent 2, Protocol udp_result (150 points): maximum: 22.13ms | 'udp_result#latency.average.milliseconds'=9.36ms;;;0; 'udp_result#latency.minimum.milliseconds'=8.57ms;;;0; 'udp_result#latency.maximum.milliseconds'=22.13ms;;0:20;0;
