name: connector-vmware

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/connector-vmware.yml'
      - 'connectors/vmware/src/**'
      - 'connectors/vmware/packaging/**'
      - '.github/docker/connector/Dockerfile.connector-vmware'
      - '.github/docker/connector/entrypoint/**'
  push:
    branches:
      - develop
      - master
    paths:
      - '.github/workflows/connector-vmware.yml'
      - 'connectors/vmware/src/**'
      - 'connectors/vmware/packaging/**'
      - '.github/docker/connector/Dockerfile.connector-vmware'
      - '.github/docker/connector/entrypoint/**'

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  get-environment:
    needs: [dependency-scan]
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: connectors/vmware/src/centreon/script/centreon_vmware.pm

  package:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - package_extension: rpm
            image: packaging-plugins-alma8
            distrib: el8
          - package_extension: rpm
            image: packaging-plugins-alma9
            distrib: el9
          - package_extension: rpm
            image: packaging-plugins-alma10
            distrib: el10
          - package_extension: deb
            image: packaging-plugins-bullseye
            distrib: bullseye
          - package_extension: deb
            image: packaging-plugins-bookworm
            distrib: bookworm
          - package_extension: deb
            image: packaging-plugins-trixie
            distrib: trixie
          - package_extension: deb
            image: packaging-plugins-jammy
            distrib: jammy
          - package_extension: deb
            image: packaging-plugins-noble
            distrib: noble

    container:
      image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.image }}
      credentials:
        username: ${{ secrets.HARBOR_CENTREON_PULL_USERNAME }}
        password: ${{ secrets.HARBOR_CENTREON_PULL_TOKEN }}

    name: package ${{ matrix.distrib }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Package
        uses: ./.github/actions/package-nfpm
        with:
          nfpm_file_pattern: "connectors/vmware/packaging/centreon-plugin-virtualization-vmware-daemon.yaml"
          distrib: ${{ matrix.distrib }}
          package_extension: ${{ matrix.package_extension }}
          version: ${{ needs.get-environment.outputs.version }}
          release: 1
          commit_hash: ${{ github.sha }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          rpm_gpg_key: ${{ secrets.RPM_GPG_SIGNING_KEY }}
          rpm_gpg_signing_key_id: ${{ secrets.RPM_GPG_SIGNING_KEY_ID }}
          rpm_gpg_signing_passphrase: ${{ secrets.RPM_GPG_SIGNING_PASSPHRASE }}
          stability: ${{ needs.get-environment.outputs.stability }}
      - name: Upload apt/dnf packages as artifacts if asked
        if: ${{ contains(github.event.pull_request.labels.*.name, 'upload-artifacts') }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: vmware-connector-daemon-${{ matrix.distrib }}
          path: centreon-plugin*
          retention-days: 1

  deliver-packages:
    needs: [get-environment, package]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      (contains(fromJson('["testing", "unstable"]'), needs.get-environment.outputs.stability) || ( needs.get-environment.outputs.stability == 'stable' && github.event_name != 'workflow_dispatch')) &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - distrib: el8
            package_extension: rpm
          - distrib: el9
            package_extension: rpm
          - distrib: el10
            package_extension: rpm
          - distrib: bullseye
            package_extension: deb
          - distrib: bookworm
            package_extension: deb
          - distrib: trixie
            package_extension: deb
          - distrib: jammy
            package_extension: deb
          - distrib: noble
            package_extension: deb

    name: deliver ${{ matrix.distrib }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Delivery
        uses: ./.github/actions/package-delivery
        with:
          module_name: connector-vmware
          distrib: ${{ matrix.distrib }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          stability: ${{ needs.get-environment.outputs.stability }}
          release_type: ${{ needs.get-environment.outputs.release_type }}
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

  docker-build:
    needs: [get-environment, package]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable' &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - package_extension: deb
            distrib: trixie
    name: docker build connector-vmware ${{ matrix.distrib }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Restore ${{ matrix.distrib }} package from cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ./*.${{ matrix.package_extension }}
          key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          fail-on-cache-miss: true

      - name: Prepare packages-centreon directory
        run: |
          mkdir -p packages-centreon
          mv ./*.${{ matrix.package_extension }} packages-centreon/
        shell: bash

      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build Docker image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          file: .github/docker/connector/Dockerfile.connector-vmware
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PACKAGE_SOURCE=mount
            WITH_SDK=false
          push: false

  set-skip-label:
    needs: [get-environment, deliver-packages]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled')
    uses: ./.github/workflows/set-pull-request-skip-label.yml
