name: security-checks

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1-5

jobs:
  secrets_scan:
    uses: centreon/security-tools/.github/workflows/gitleaks-analysis.yml@main

  code_scan:
    uses: centreon/security-tools/.github/workflows/checkmarx-analysis.yml@main
    with:
      module_directory:
      module_name: centreon-plugins
      exclude_list:
    secrets:
      base_uri: ${{ secrets.AST_RND_SCANS_BASE_URI }}
      cx_tenant: ${{ secrets.AST_RND_SCANS_TENANT }}
      cx_client_id: ${{ secrets.AST_RND_SCANS_CLIENT_ID }}
      cx_client_secret: ${{ secrets.AST_RND_SCANS_CLIENT_SECRET }}
