name: test plugin vmware arm

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/testarm.yml'
  push:
    paths:
      - '.github/workflows/testarm.yml'

jobs:

  test_arm:
    runs-on: ["self-hosted", "collect-arm64"]

    container:
      image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/testing-plugins-bullseye
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_ID }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

    name: "test bullseye amr"

    steps:
      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - run: |
          apt update
          apt install centreon-plugin-virtualization-vmware2-connector-plugin
        shell: bash
