ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:trixie

RUN bash -e <<EOF

apt-get update
apt-get install -y \
  ca-certificates \
  git \
  maven=3.9.9-1 \
  openjdk-21-jdk-headless \
  zstd

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list

apt-get update
apt-get install -y nfpm=2.41.0

apt-get clean all

EOF

WORKDIR /src