ARG REGISTRY_URL=docker.io

FROM ${REGISTRY_URL}/ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

# fix locale
RUN bash -e <<EOF

apt-get update
apt-get install -y locales
rm -rf /var/lib/apt/lists/*
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
apt-get clean

EOF

ENV LANG=en_US.utf8

RUN bash -e <<EOF

apt-get update

echo 'http://deb.debian.org/debian' | apt-get install -y pbuilder

apt-get install -y \
  aptitude \
  ca-certificates \
  cpanminus \
  curl \
  debmake \
  devscripts \
  dh-make \
  dh-make-perl \
  fakeroot \
  gcc \
  git \
  git-buildpackage \
  jq \
  libapp-fatpacker-perl \
  libcurl4-openssl-dev \
  libczmq-dev \
  libczmq-dev\
  libfile-copy-recursive-perl \
  libjson-perl \
  libmodule-build-tiny-perl \
  libmodule-install-perl \
  libssh-dev \
  lintian \
  python3 \
  quilt \
  ruby \
  uuid-dev \
  zstd

cpanm Module::Build::Tiny
cpanm Module::Install
cpanm Crypt::OpenSSL::Guess

gem install fpm

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
apt-get update
apt-get install -y nfpm

apt-get clean

EOF
